// GENERATED BY CLOESCE. DO NOT MODIFY.
import { HttpResult, KValue, CloesceApp, Orm, IncludeTree, DeepPartial, Paginated } from "cloesce";
import { R2Bucket, KVNamespace, D1Database, R2Object, D1PreparedStatement, R2ObjectBody, ReadableStream } from "@cloudflare/workers-types";

export type CfReadableStream = ReadableStream;
export type MaybePromise<T> = T | Promise<T>;
export type MaybeHttpResult<T> = T | HttpResult<T>;
export interface Env {
    db: D1Database;
    bucket1: R2Bucket;
    bucket2: R2Bucket;
}
export namespace D1BackedModel {
    export const Tag = "D1BackedModel";
    export const Meta = cidl.models.D1BackedModel as any;

    export interface Self {
        id: number;
        keyParam: string;
        someColumn: number;
        someOtherColumn: string;
        r2Data: R2ObjectBody;
    }

    export namespace KeyFormat {
        export function r2Data(id: number,keyParam: string,someColumn: number,someOtherColumn: string,): string {
            return `d1Backed/${id}/${keyParam}/${someColumn}/${someOtherColumn}`;
        }
    }

    export abstract class Api {
        readonly tag = Tag;
        abstract uploadData(self: D1BackedModel.Self, e: Env, data: CfReadableStream): MaybePromise<MaybeHttpResult<void>>;
    }

    export namespace DataSources {
        export const Default = {
            include: {"r2Data":{}},
            getQuery: (env: Env, id: number) => env.db.prepare(`SELECT "D1BackedModel"."id" AS "id", "D1BackedModel"."someColumn" AS "someColumn", "D1BackedModel"."someOtherColumn" AS "someOtherColumn" FROM "D1BackedModel" WHERE "D1BackedModel"."id" = ?1`).bind(id),
            async get(env: Env, id: number, keyParam: string): Promise<D1BackedModel.Self | null> {
                return await Orm.fromEnv(env).get<D1BackedModel.Self>(D1BackedModel.Meta, D1BackedModel.DataSources.Default.getQuery(env, id), D1BackedModel.DataSources.Default.include, { keyParam });
            },
            listQuery: (env: Env, lastSeen_id: number, limit: number) => env.db.prepare(`SELECT "D1BackedModel"."id" AS "id", "D1BackedModel"."someColumn" AS "someColumn", "D1BackedModel"."someOtherColumn" AS "someOtherColumn" FROM "D1BackedModel" WHERE "D1BackedModel"."id" > ?1 ORDER BY "D1BackedModel"."id" ASC LIMIT ?2`).bind(lastSeen_id, limit),
            async list(env: Env, lastSeen_id: number, limit: number): Promise<D1BackedModel.Self[]> {
                return await Orm.fromEnv(env).list<D1BackedModel.Self>(D1BackedModel.Meta, D1BackedModel.DataSources.Default.listQuery(env, lastSeen_id, limit), D1BackedModel.DataSources.Default.include);
            },
        }
    }

    export async function save(env: Env, newModel: DeepPartial<Self>, include: IncludeTree<Self> = DataSources.Default.include): Promise<Self | null> {
        return await Orm.fromEnv(env).upsert<Self>(Meta, newModel, include);
    }

    export async function get(env: Env, args: { query?: D1PreparedStatement, include?: IncludeTree<Self>, keyFields?: { keyParam?: string } }): Promise<Self | null> {
        args.include ??= DataSources.Default.include;
        return await Orm.fromEnv(env).get<Self>(Meta, args.query, args.include, args.keyFields ?? {});
    }

    export async function list(env: Env, args: { query?: D1PreparedStatement, include?: IncludeTree<Self> }): Promise<Self[]> {
        args.include ??= DataSources.Default.include;
        return await Orm.fromEnv(env).list<Self>(Meta, args.query, args.include);
    }
}
export namespace PureR2Model {
    export const Tag = "PureR2Model";
    export const Meta = cidl.models.PureR2Model as any;

    export interface Self {
        id: string;
        data: R2ObjectBody;
        otherData: R2ObjectBody;
        allData: Paginated<R2ObjectBody>;
    }

    export namespace KeyFormat {
        export function data(id: string,): string {
            return `path/to/data/${id}`;
        }
        export function otherData(id: string,): string {
            return `path/to/other/${id}`;
        }
        export function allData(): string {
            return `path/`;
        }
    }

    export abstract class Api {
        readonly tag = Tag;
        abstract uploadData(self: PureR2Model.Self, e: Env, data: CfReadableStream): MaybePromise<MaybeHttpResult<void>>;
        abstract uploadOtherData(self: PureR2Model.Self, e: Env, data: CfReadableStream): MaybePromise<MaybeHttpResult<void>>;
    }

    export namespace DataSources {
        export const Default = {
            include: {"allData":{},"data":{},"otherData":{}},
            async get(env: Env, id: string): Promise<PureR2Model.Self | null> {
                return await Orm.fromEnv(env).get<PureR2Model.Self>(PureR2Model.Meta, null, PureR2Model.DataSources.Default.include, { id });
            },
        }
    }

    export async function save(env: Env, newModel: DeepPartial<Self>, include: IncludeTree<Self> = DataSources.Default.include): Promise<Self | null> {
        return await Orm.fromEnv(env).upsert<Self>(Meta, newModel, include);
    }

    export async function get(env: Env, args: { query?: D1PreparedStatement, include?: IncludeTree<Self>, keyFields?: { id?: string } }): Promise<Self | null> {
        args.include ??= DataSources.Default.include;
        return await Orm.fromEnv(env).get<Self>(Meta, args.query, args.include, args.keyFields ?? {});
    }

    export async function list(env: Env, args: { query?: D1PreparedStatement, include?: IncludeTree<Self> }): Promise<Self[]> {
        args.include ??= DataSources.Default.include;
        return await Orm.fromEnv(env).list<Self>(Meta, args.query, args.include);
    }
}
import cidl from "./cidl.json" with { type: "json" };
(cidl.models.D1BackedModel.data_sources["Default"] as any).gen = D1BackedModel.DataSources.Default;
(cidl.models.PureR2Model.data_sources["Default"] as any).gen = PureR2Model.DataSources.Default;

export async function cloesce(): Promise<CloesceApp> {
    return await CloesceApp.init(cidl as any, "http://localhost:5538/api")
}

// Default entrypoint for a Cloesce app. 
// Replace with a custom fetch handler to register API implementations, add middleware, etc.
export default {
    async fetch(request: Request, env: Env): Promise<Response> {
        const app = await cloesce();
        return await app.run(request, env);
    }
}