import { D1Database } from "@cloudflare/workers-types/experimental/index.js";
import {
  HttpResult,
  Either,
  ModelMethod,
  left,
  CidlType,
  right,
  CloesceAst,
  isNullableType,
  Model,
  getNavigationPropertyCidlType,
  CidlIncludeTree,
} from "./common.js";
import { IncludeTree } from "./index.js";

/**
 * A map of model names to their respective constructor.
 *
 * The value accepted into the `cloesce` function is generated by the Cloesce compiler, and
 * is guaranteed to contain all model definitions.
 */
type ModelConstructorRegistry = Record<string, new () => UserDefinedModel>;

/**
 * A dependency injection container, mapping an object type name to an instance of that object.
 *
 * The value accepted into the `cloesce` function is generated by the Cloesce compiler, and is
 * guaranteed to contain all injected model method parameters.
 */
type InstanceRegistry = Map<string, any>;

/**
 * Singleton instances of the MetaCidl and Constructor Registry.
 * These values are guaranteed to never change throughout a workers lifetime.
 */
class MetaContainer {
  private static instance: MetaContainer | undefined;
  private constructor(
    public readonly ast: CloesceAst,
    public readonly constructorRegistry: ModelConstructorRegistry,
  ) {}

  static init(ast: CloesceAst, constructorRegistry: ModelConstructorRegistry) {
    if (!this.instance) {
      this.instance = new MetaContainer(ast, constructorRegistry);
    }
  }

  static get(): MetaContainer {
    return this.instance!;
  }
}

/**
 * Users will create Cloesce models, which have metadata for them in the ast.
 * For TypeScript's purposes, these models can be anything. We can assume any
 * `UserDefinedModel` has been verified by the compiler.
 */
type UserDefinedModel = any;
type InstantiatedUserDefinedModel = object;

/**
 * Given a request, this represents a map of each body / url  param name to
 * its actual value. Unknown, as the a request can be anything.
 */
type RequestParamMap = Record<string, unknown>;

/**
 * Meta information on the wrangler env and db bindings
 */
interface MetaWranglerEnv {
  envName: string;
  dbName: string; // TODO: support many db's
}

/**
 * Creates model instances given a properly formatted SQL record
 * (either a foreign-key-less model or derived from a Cloesce generated view)
 * @param ctor The type of the model
 * @param records SQL records
 * @param includeTree The include tree to use when parsing the records
 * @returns
 */
export function modelsFromSql<T>(
  ctor: new () => T,
  records: Record<string, any>[],
  includeTree: IncludeTree<T> | null,
): T[] {
  const { ast, constructorRegistry } = MetaContainer.get();
  return _modelsFromSql(
    ctor.name,
    ast,
    constructorRegistry,
    records,
    includeTree,
  ) as T[];
}

/**
 * Cloesce entry point. Given a request, undergoes routing, validating,
 * hydrating, and method dispatch.
 * @param ast The CIDL AST
 * @param constructorRegistry A mapping of user defined class names to their respective constructor
 * @param instanceRegistry A mapping of a dependency class name to its instantiated object.
 * @param request An incoming request to the workers server
 * @param api_route The url's path to the api, e.g. api/v1/fooapi/
 * @param envMeta Meta information on the wrangler env and D1 databases
 * @returns A Response with an `HttpResult` JSON body.
 */
export async function cloesce(
  request: Request,
  ast: CloesceAst,
  constructorRegistry: ModelConstructorRegistry,
  instanceRegistry: InstanceRegistry,
  envMeta: MetaWranglerEnv,
  api_route: string,
): Promise<Response> {
  MetaContainer.init(ast, constructorRegistry);
  const d1: D1Database = instanceRegistry.get(envMeta.envName)[envMeta.dbName];

  // Match the route to a model method
  const route = matchRoute(request, ast, api_route);
  if (!route.ok) {
    return toResponse(route.value);
  }
  const { method, model, id } = route.value;

  // Validate request body to the model method
  const isValidRequest = await validateRequest(request, ast, model, method, id);
  if (!isValidRequest.ok) {
    return toResponse(isValidRequest.value);
  }
  const [requestParamMap, dataSource] = isValidRequest.value;

  // Instantatiate the model
  let instance: object;
  if (method.is_static) {
    instance = constructorRegistry[model.name];
  } else {
    const successfulModel = await hydrateModel(
      ast,
      constructorRegistry,
      d1,
      model,
      id!,
      dataSource,
    );

    if (!successfulModel.ok) {
      return toResponse(successfulModel.value);
    }

    instance = successfulModel.value;
  }

  // Dispatch a method on the model and return the result
  return toResponse(
    await methodDispatch(
      instance,
      instanceRegistry,
      envMeta,
      method,
      requestParamMap,
    ),
  );
}

/**
 * Matches a request to a method on a model.
 * @param api_route The route from the domain to the actual API, ie https://foo.com/route/to/api => route/to/api/
 * @returns 404 or a `MatchedRoute`
 */
function matchRoute(
  request: Request,
  ast: CloesceAst,
  api_route: string,
): Either<HttpResult, MatchedRoute> {
  const url = new URL(request.url);

  const notFound = (e: string) =>
    left(error_state(404, `Path not found: ${e} ${url.pathname}`));

  const routeParts = url.pathname
    .slice(api_route.length)
    .split("/")
    .filter(Boolean);

  if (routeParts.length < 2) {
    return notFound("Expected /model/method or /model/:id/method");
  }

  // Attempt to extract from routeParts
  const modelName = routeParts[0];
  const methodName = routeParts[routeParts.length - 1];
  const id = routeParts.length === 3 ? routeParts[1] : null;

  const model = ast.models[modelName];
  if (!model) {
    return notFound(`Unknown model ${modelName}`);
  }

  const method = model.methods[methodName];
  if (!method) {
    return notFound(`Unknown method ${modelName}.${methodName}`);
  }

  if (request.method !== method.http_verb) {
    return notFound("Unmatched HTTP method");
  }

  return right({
    model,
    method,
    id,
  });
}

/**
 * Validates the request's body/search params against a ModelMethod
 * @returns 400 or a `RequestParamMap` consisting of each parameters name mapped to its value, and
 * a data source
 */
async function validateRequest(
  request: Request,
  ast: CloesceAst,
  model: Model,
  method: ModelMethod,
  id: string | null,
): Promise<Either<HttpResult, [RequestParamMap, string | null]>> {
  // Error state: any missing parameter, body, or malformed input will exit with 400.
  const invalid_request = (e: string) =>
    left(error_state(400, `Invalid Request Body: ${e}`));

  if (!method.is_static && id == null) {
    return invalid_request("Id's are required for instantiated methods.");
  }

  // Filter out any injected parameters that will not be passed
  // by the query.
  const requiredParams = method.parameters.filter(
    (p) =>
      !(
        typeof p.cidl_type === "object" &&
        p.cidl_type !== null &&
        "Inject" in p.cidl_type
      ),
  );

  // Extract data source
  const url = new URL(request.url);
  let dataSource = url.searchParams.get("dataSource");

  // Extract url or body parameters
  let requestBodyMap: RequestParamMap;
  if (method.http_verb === "GET") {
    requestBodyMap = Object.fromEntries(url.searchParams.entries());
  } else {
    try {
      requestBodyMap = await request.json();
    } catch {
      return invalid_request("Could not retrieve JSON body.");
    }
  }

  // Validate data source if exists
  if (dataSource && !(dataSource in model.data_sources)) {
    return invalid_request(`Unknown data source ${dataSource}`);
  }

  // Ensure all required params exist
  if (!requiredParams.every((p) => p.name in requestBodyMap)) {
    return invalid_request(`Missing parameters.`);
  }

  // Validate all parameters type
  for (const p of requiredParams) {
    const value = requestBodyMap[p.name];
    if (!validateCidlType(ast, value, p.cidl_type)) {
      return invalid_request("Invalid parameters.");
    }
  }

  return right([requestBodyMap, dataSource]);
}

/**
 * Queries D1 for a particular model's ID, then transforms the SQL column output into
 * an instance of a model using the provided include tree and metadata as a guide.
 * @returns 404 if no record was found for the provided ID
 * @returns 500 if the D1 database is not synced with Cloesce and yields an error
 * @returns The instantiated model on success
 */
async function hydrateModel(
  ast: CloesceAst,
  constructorRegistry: ModelConstructorRegistry,
  d1: D1Database,
  model: Model,
  id: string,
  dataSource: string | null,
): Promise<Either<HttpResult, object>> {
  // Error state: If the D1 database has been tweaked outside of Cloesce
  // resulting in a malformed query, exit with a 500.
  const malformedQuery = (e: any) =>
    left(
      error_state(
        500,
        `Error in hydration query, is the database out of sync with the backend?: ${e instanceof Error ? e.message : String(e)}`,
      ),
    );

  // Error state: If no record is found for the id, return a 404
  const missingRecord = left(error_state(404, "Record not found"));

  const pk = model.primary_key.name;
  const query =
    dataSource !== null
      ? `SELECT * FROM ${model.name}_${dataSource} WHERE ${model.name}_${pk} = ?`
      : `SELECT * FROM ${model.name} WHERE ${pk} = ?`;

  // Query DB
  let records;
  try {
    records = await d1.prepare(query).bind(id).run();
    if (!records) {
      return missingRecord;
    }
  } catch (e) {
    return malformedQuery(e);
  }

  // Get include tree
  const includeTree: CidlIncludeTree =
    dataSource !== null ? model.data_sources[dataSource].tree : {};

  // Hydrate
  const models: object[] = _modelsFromSql(
    model.name,
    ast,
    constructorRegistry,
    records.results,
    includeTree,
  );

  return right(models[0]);
}

/**
 * Calls a method on a model given a list of parameters.
 * @returns 500 on an uncaught client error, 200 with a result body on success
 */
async function methodDispatch(
  instance: InstantiatedUserDefinedModel,
  instanceRegistry: InstanceRegistry,
  envMeta: MetaWranglerEnv,
  method: ModelMethod,
  params: Record<string, unknown>,
): Promise<HttpResult<unknown>> {
  // Error state: Client code ran into an uncaught exception.
  const uncaughtException = (e: any) =>
    error_state(
      500,
      `Uncaught exception in method dispatch: ${e instanceof Error ? e.message : String(e)}`,
    );

  // For now, the only injected dependency is the wrangler env,
  // so we will assume that is what this is
  const paramArray = method.parameters.map((p) =>
    params[p.name] == undefined
      ? instanceRegistry.get(envMeta.envName)
      : params[p.name],
  );

  // Ensure the result is always some HttpResult
  const resultWrapper = (res: any): HttpResult<unknown> => {
    const rt = method.return_type;

    if (rt === null) {
      return { ok: true, status: 200 };
    }

    if (typeof rt === "object" && rt !== null && "HttpResult" in rt) {
      return res as HttpResult<unknown>;
    }

    return { ok: true, status: 200, data: res };
  };

  try {
    return resultWrapper(await (instance as any)[method.name](...paramArray));
  } catch (e) {
    return uncaughtException(e);
  }
}

function validateCidlType(
  ast: CloesceAst,
  value: unknown,
  cidlType: CidlType,
): boolean {
  if (value === undefined) return false;

  // TODO: consequences of null checking like this? 'null' is passed in
  // as a string for GET requests...
  const nullable = isNullableType(cidlType);
  if (value == null || value === "null") return nullable;

  if (nullable) {
    cidlType = (cidlType as any).Nullable; // Unwrap the nullable type
  }

  // Handle primitive string types with switch
  if (typeof cidlType === "string") {
    switch (cidlType) {
      case "Integer":
        return Number.isInteger(Number(value));
      case "Real":
        return !Number.isNaN(Number(value));
      case "Text":
        return typeof value === "string";
      case "Blob":
        return value instanceof Blob || value instanceof ArrayBuffer;
      default:
        return false;
    }
  }

  // Handle Models
  if ("Object" in cidlType && ast.models[cidlType.Object]) {
    const model = ast.models[cidlType.Object];
    if (!model || typeof value !== "object") return false;
    const valueObj = value as Record<string, unknown>;

    // Validate attributes
    if (
      !model.attributes.every((attr) =>
        validateCidlType(ast, valueObj[attr.value.name], attr.value.cidl_type),
      )
    ) {
      return false;
    }

    // Validate navigation properties
    return model.navigation_properties.every((nav) => {
      const navValue = valueObj[nav.var_name];

      return (
        navValue == null ||
        validateCidlType(ast, navValue, getNavigationPropertyCidlType(nav))
      );
    });
  }

  // Handle Plain Old Objects
  if ("Object" in cidlType && ast.poos[cidlType.Object]) {
    const poo = ast.poos[cidlType.Object];
    if (!poo || typeof value !== "object") return false;
    const valueObj = value as Record<string, unknown>;

    // Validate attributes
    if (
      !poo.attributes.every((attr) =>
        validateCidlType(ast, valueObj[attr.name], attr.cidl_type),
      )
    ) {
      return false;
    }
  }

  if ("Array" in cidlType) {
    const arr = cidlType.Array;
    return (
      Array.isArray(value) && value.every((v) => validateCidlType(ast, v, arr))
    );
  }

  if ("HttpResult" in cidlType) {
    if (value === null) return cidlType.HttpResult === null;
    if (cidlType.HttpResult === null) return false;
    return validateCidlType(ast, value, cidlType.HttpResult);
  }

  return false;
}

/**
 * Actual implementation of sql to model mapping.
 *
 * TODO: If we don't want to write this in every language, would it be possible to create a
 * single WASM binary for this method?
 *
 * @throws generic errors if the metadata is missing some value
 */
function _modelsFromSql(
  modelName: string,
  ast: CloesceAst,
  constructorRegistry: ModelConstructorRegistry,
  records: Record<string, any>[],
  includeTree: Record<string, UserDefinedModel> | null,
): InstantiatedUserDefinedModel[] {
  if (!records.length) return [];

  const modelMeta = ast.models[modelName];
  if (!modelMeta) throw new Error(`Model ${modelName} not found in ast`);

  const pk = modelMeta.primary_key;
  if (!pk) throw new Error(`Primary key not found for ${modelName}`);

  const pkName = pk.name;
  const itemsById: Record<string, any> = {};
  const seenNestedIds: Record<string, Set<string>> = {};

  // Create all root entities with initialized arrays
  for (const row of records) {
    const isPrefixed = Object.keys(row).some((k) =>
      k.startsWith(`${modelName}_`),
    );
    const rootId = String(isPrefixed ? row[`${modelName}_id`] : row[pkName]);

    if (!itemsById[rootId]) {
      const instance = new constructorRegistry[modelName]();

      // Assign primary key
      instance[modelMeta.primary_key.name] = getCol(
        modelMeta,
        modelMeta.primary_key.name,
        row,
        isPrefixed,
      );

      // Assign scalar attributes
      for (const attr of modelMeta.attributes) {
        instance[attr.value.name] = getCol(
          modelMeta,
          attr.value.name,
          row,
          isPrefixed,
        );
      }

      // Initialize all array navigation properties
      for (const nav of modelMeta.navigation_properties) {
        const navCidlType = getNavigationPropertyCidlType(nav);
        if (isCidlArray(navCidlType)) {
          instance[nav.var_name] = [];
        }
      }

      itemsById[rootId] = instance;
    }
  }

  // Populate navigation properties
  for (const row of records) {
    const isPrefixed = Object.keys(row).some((k) =>
      k.startsWith(`${modelName}_`),
    );
    const rootId = String(isPrefixed ? row[`${modelName}_id`] : row[pkName]);
    const existing = itemsById[rootId];

    // Process navigation properties
    for (const nav of modelMeta.navigation_properties) {
      const navName = nav.var_name;
      const navCidlType = getNavigationPropertyCidlType(nav);
      let navModelName: string | undefined;

      if (isCidlArray(navCidlType)) {
        if (isCidlObject(navCidlType.Array)) {
          navModelName = navCidlType.Array.Object;
        }
      } else if (isCidlObject(navCidlType)) {
        navModelName = navCidlType.Object;
      }

      if (!navModelName) continue;

      const navMeta = ast.models[navModelName];
      if (!navMeta) continue;

      const nestedPk = navMeta.primary_key.name;
      const nestedId = row[`${navMeta.name}_${nestedPk}`];
      const isArray = isCidlArray(navCidlType);

      // Only process if we're supposed to include this navigation property AND there's data
      if (includeTree?.[navName] && nestedId != null) {
        const nestedObj = buildInstance(
          navMeta,
          row,
          includeTree[navName],
          true,
        );

        if (isArray) {
          addUnique(
            existing[navName],
            nestedObj,
            `${modelMeta.name}_${navName}`,
            navModelName,
          );
        } else {
          existing[navName] = nestedObj;
        }
      }
    }
  }

  return Object.values(itemsById);

  function isCidlObject(value: CidlType): value is { Object: string } {
    return typeof value === "object" && value !== null && "Object" in value;
  }

  function isCidlArray(value: CidlType): value is { Array: CidlType } {
    return typeof value === "object" && value !== null && "Array" in value;
  }

  function getCol(
    meta: Model,
    attrName: string,
    row: Record<string, any>,
    prefixed: boolean,
  ) {
    return row[prefixed ? `${meta.name}_${attrName}` : attrName] ?? null;
  }

  function addUnique(arr: any[], item: any, key: string, navModelName: string) {
    seenNestedIds[key] = seenNestedIds[key] || new Set();

    // Get the primary key name for the nested model
    const navMeta = ast.models[navModelName];
    const nestedPkAttr = navMeta?.primary_key;
    const nestedPkName = nestedPkAttr?.name || "id";

    const id = String(item[nestedPkName]);
    if (!seenNestedIds[key].has(id)) {
      arr.push(item);
      seenNestedIds[key].add(id);
    }
  }

  function buildInstance(
    meta: Model,
    row: Record<string, any>,
    tree: Record<string, any>,
    prefixed: boolean,
  ): any {
    const instance = new constructorRegistry[meta.name]();

    // Assign PK
    instance[meta.primary_key.name] = getCol(
      meta,
      meta.primary_key.name,
      row,
      prefixed,
    );

    // Assign scalar attributes
    for (const attr of meta.attributes) {
      instance[attr.value.name] = getCol(meta, attr.value.name, row, prefixed);
    }

    // Assign navigation properties
    for (const nav of meta.navigation_properties) {
      const navName = nav.var_name;
      const navCidlType = getNavigationPropertyCidlType(nav);
      let navModelName: string | undefined;

      if (isCidlArray(navCidlType)) {
        if (isCidlObject(navCidlType.Array)) {
          navModelName = navCidlType.Array.Object;
        }
      } else if (isCidlObject(navCidlType)) {
        navModelName = navCidlType.Object;
      }

      if (!navModelName) continue;

      const navMeta = ast.models[navModelName];
      if (!navMeta) continue;

      const nestedPk = navMeta.primary_key;
      const nestedId = row[`${navMeta.name}_${nestedPk.name}`];
      const isArray = isCidlArray(navCidlType);

      // Always initialize arrays, even if empty
      if (isArray) {
        instance[navName] = instance[navName] || [];
      }

      if (tree?.[navName] && nestedId != null) {
        const nestedObj = buildInstance(navMeta, row, tree[navName], true);
        if (isArray) {
          addUnique(
            instance[navName],
            nestedObj,
            `${meta.name}_${navName}`,
            navModelName,
          );
        } else {
          instance[navName] = nestedObj;
        }
      }
    }
    return instance;
  }
}

function error_state(status: number, message: string): HttpResult {
  return { ok: false, status, message };
}

function toResponse(r: HttpResult): Response {
  return new Response(JSON.stringify(r), {
    status: r.status,
    headers: { "Content-Type": "application/json" },
  });
}

interface MatchedRoute {
  model: Model;
  method: ModelMethod;
  id: string | null;
}

/**
 * Each individual state of the `cloesce` function for testing purposes.
 */
export const _cloesceInternal = {
  matchRoute,
  validateRequest,
  hydrateModel,
  methodDispatch,
  _modelsFromSql,
};
