[package]
name = "runtime"
version = "0.0.3"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = "1.0.219"
serde_json = "1.0.143"
common = { path = "../generator/common" }

[profile.release]
opt-level = "z"
panic = "abort"
