// GENERATED BY CLOESCE. DO NOT MODIFY.
import { HttpResult, KValue, CloesceApp, Orm as CloesceOrm, IncludeTree, DeepPartial, CloesceResult, CloesceError, SqlStatement, applyDurableMigrations, DurableMigration } from "cloesce";
import { DurableObject } from "cloudflare:workers";

export type CfReadableStream = ReadableStream;
export type MaybePromise<T> = T | Promise<T>;
export type MaybeHttpResult<T> = T | HttpResult<T>;
export type ApiResult<T> = MaybePromise<MaybeHttpResult<T>>;

export interface CfEnv {
    GlobalSubRedditMetadata: KVNamespace;
    GlobalDo: DurableObjectNamespace;
    SubRedditDo: DurableObjectNamespace;
}
// @ts-ignore
export abstract class GlobalDo extends DurableObject<CfEnv> {
    constructor(public state: DurableObjectState, env: CfEnv) {
        super(state, env);
    }

    static readonly Shard = {
        template: (): string =>
            `GlobalDo`,
        id: (namespace: DurableObjectNamespace): DurableObjectId =>
            namespace.idFromName(GlobalDo.Shard.template()),
    };

    readonly metadata = {
        template: (): string =>
            `metadata`,
        get: (): unknown | null | undefined =>
            this.state.storage.kv.get(this.metadata.template()),
        put: ( value: unknown) =>
            this.state.storage.kv.put(this.metadata.template(), value),
        list: () =>
            this.state.storage.kv.list({ prefix: `metadata` }),
    };

    protected cloesce(env: CfEnv, migrations: DurableMigration[] = []): CloesceApp {
        if (migrations.length > 0) {
            this.state.blockConcurrencyWhile(() => applyDurableMigrations(this.state.storage, migrations));
        }
        // @ts-expect-error
        return new CloesceApp(cidl as any, "http://localhost:5843/api", upgradeEnv(env), this);
    }
}
// @ts-ignore
export abstract class SubRedditDo extends DurableObject<CfEnv> {
    constructor(public state: DurableObjectState, env: CfEnv) {
        super(state, env);
    }

    static readonly Shard = {
        template: (id: number): string =>
            `SubRedditDo/${id}`,
        id: (id: number, namespace: DurableObjectNamespace): DurableObjectId =>
            namespace.idFromName(SubRedditDo.Shard.template(id)),
    };

    readonly metadata = {
        template: (): string =>
            `metadata`,
        get: (): unknown | null | undefined =>
            this.state.storage.kv.get(this.metadata.template()),
        put: ( value: unknown) =>
            this.state.storage.kv.put(this.metadata.template(), value),
        list: () =>
            this.state.storage.kv.list({ prefix: `metadata` }),
    };

    protected cloesce(env: CfEnv, migrations: DurableMigration[] = []): CloesceApp {
        if (migrations.length > 0) {
            this.state.blockConcurrencyWhile(() => applyDurableMigrations(this.state.storage, migrations));
        }
        // @ts-expect-error
        return new CloesceApp(cidl as any, "http://localhost:5843/api", upgradeEnv(env), this);
    }
}
function GlobalSubRedditMetadataHelpers(namespace: KVNamespace) {
    return {
        metadata: {
            template: (subId: number): string =>
                `metadata/${subId}`,
            get: (subId: number): Promise<unknown | null> =>
                namespace.get(`metadata/${subId}`) as any,
            put: (subId: number, value: unknown): Promise<void> =>
                namespace.put(`metadata/${subId}`, value as any),
            list: (options?: { limit?: number, cursor?: string }) =>
                namespace.list({ ...options, prefix: `metadata/` }),
        },
    };
}
function GlobalDoHelpers(namespace: DurableObjectNamespace) {
    return {
        instance: <T extends GlobalDo = GlobalDo>(): DurableObjectStub & T =>
            namespace.get(GlobalDo.Shard.id(namespace)) as DurableObjectStub & T,
    };
}
function SubRedditDoHelpers(namespace: DurableObjectNamespace) {
    return {
        instance: <T extends SubRedditDo = SubRedditDo>(id: number): DurableObjectStub & T =>
            namespace.get(SubRedditDo.Shard.id(id, namespace)) as DurableObjectStub & T,
    };
}

export namespace Env {
    export type GlobalSubRedditMetadata = CfEnv["GlobalSubRedditMetadata"] & ReturnType<typeof GlobalSubRedditMetadataHelpers>;
    export type GlobalDo = CfEnv["GlobalDo"] & ReturnType<typeof GlobalDoHelpers>;
    export type SubRedditDo = CfEnv["SubRedditDo"] & ReturnType<typeof SubRedditDoHelpers>;
}

export type Env = CfEnv & {
    GlobalSubRedditMetadata: Env.GlobalSubRedditMetadata;
    GlobalDo: Env.GlobalDo;
    SubRedditDo: Env.SubRedditDo;
};

export function upgradeEnv(env: CfEnv): Env {
    Object.assign(env.GlobalSubRedditMetadata, GlobalSubRedditMetadataHelpers(env.GlobalSubRedditMetadata));
    Object.assign(env.GlobalDo, GlobalDoHelpers(env.GlobalDo));
    Object.assign(env.SubRedditDo, SubRedditDoHelpers(env.SubRedditDo));
    return env as Env;
}
export namespace Global {
    export const Tag = "Global" as const;
    export const Meta = cidl.models.Global as any;

    export interface Self {
        metadata: unknown;
    }

    export interface Api {
        newGlobal(
        ): ApiResult<Global.Self>;
        getMetadata(
            self: Global.Self,
            env: {
                ctx: GlobalDo,
            },
        ): ApiResult<unknown>;
    }
    export const _api = undefined as unknown as Api;

    export interface Sources {
    }

    export namespace GeneratedSource {
        export const Default = {
            tree: {"metadata":{}},
            async get(env: { ctx: GlobalDo, GlobalDo: Env["GlobalDo"] }): Promise<HttpResult<Self | null>> {
                const base = {  } as DeepPartial<Self>;
                const res = await CloesceOrm.fromEnv(env).hydrate<Self>(Meta, base, this.tree);
                if (res.errors.length > 0) {
                    return HttpResult.fail(400, CloesceError.displayErrors(res));
                }
                return HttpResult.ok(200, res.value);
            },
            async save(env: { ctx: GlobalDo, GlobalDo: Env["GlobalDo"] }, model: DeepPartial<Global.Self>): Promise<HttpResult<Self | null>> {
                const res = await CloesceOrm.fromEnv(env).upsert<Self>(Meta, { ...model } as DeepPartial<Self>, this.tree);
                if (res.errors.length > 0) {
                    return HttpResult.fail(400, CloesceError.displayErrors(res));
                }
                if (res.value === null) {
                    return HttpResult.fail(404);
                }
                return HttpResult.ok(200, res.value);
            },
        };
    }

    export function impl<Impl extends Api & Sources>(implObj: Impl & ThisType<{ tag: string; Orm: typeof Orm; Default: typeof GeneratedSource.Default } & Impl>): { tag: string; Orm: typeof Orm; Default: typeof GeneratedSource.Default } & Impl {
        return _impl("Global", { Orm, Default: GeneratedSource.Default }, implObj) as any;
    }

    export namespace Orm {

        export async function save(ctx: GlobalDo, newModel: DeepPartial<Self>, include: IncludeTree<Self> = GeneratedSource.Default.tree): Promise<CloesceResult<Self | null>> {
            return await CloesceOrm.fromEnv({ ctx: ctx }).upsert<Self>(Meta, newModel, include);
        }

        export async function get(ctx: GlobalDo, args: { include?: IncludeTree<Self> }): Promise<CloesceResult<Self>> {
            const include = args.include ?? GeneratedSource.Default.tree;
            const base = {  } as DeepPartial<Self>;
            return await CloesceOrm.fromEnv({ ctx: ctx }).hydrate<Self>(Meta, base, include);
        }

        export async function hydrate(ctx: GlobalDo, base: DeepPartial<Self>, include: IncludeTree<Self> = GeneratedSource.Default.tree): Promise<CloesceResult<Self>> {
            return await CloesceOrm.fromEnv({ ctx: ctx }).hydrate<Self>(Meta, base, include);
        }
    }
}
export namespace Post {
    export const Tag = "Post" as const;
    export const Meta = cidl.models.Post as any;

    export interface Self {
        id: number;
        title: string;
        content: string;
        subId: number;
        comments: Comment.Self[];
    }

    export interface Api {
    }
    export const _api = undefined as unknown as Api;

    export interface Sources {
        Custom: Custom.Impl;
    }

    export namespace GeneratedSource {
        export const Custom = {
            tree: {},
            selectQuery: `SELECT "Post"."id" AS "id", "Post"."title" AS "title", "Post"."content" AS "content" FROM "Post"`,

            getQuery(subId: number): SqlStatement {
                return { query: `SELECT "Post"."id" AS "id", "Post"."title" AS "title", "Post"."content" AS "content" FROM "Post" WHERE "Post"."id" = ?1`, values: [subId] };
            },
            listQuery(): SqlStatement {
                return { query: `SELECT "Post"."id" AS "id", "Post"."title" AS "title", "Post"."content" AS "content" FROM "Post" WHERE "Post"."id" > ?1 ORDER BY "Post"."id" ASC LIMIT ?2`, values: [] };
            },
        };
        export const Default = {
            tree: {"comments":{}},
            selectQuery: `SELECT "Post"."id" AS "id", "Post"."title" AS "title", "Post"."content" AS "content", "Comment_1"."id" AS "comments.id", "Comment_1"."content" AS "comments.content", "Comment_1"."upvotes" AS "comments.upvotes", "Comment_1"."postId" AS "comments.postId" FROM "Post" LEFT JOIN "Comment" AS "Comment_1" ON "Post"."id" = "Comment_1"."postId"`,

            getQuery(id: number): SqlStatement {
                return { query: `SELECT "Post"."id" AS "id", "Post"."title" AS "title", "Post"."content" AS "content", "Comment_1"."id" AS "comments.id", "Comment_1"."content" AS "comments.content", "Comment_1"."upvotes" AS "comments.upvotes", "Comment_1"."postId" AS "comments.postId" FROM "Post" LEFT JOIN "Comment" AS "Comment_1" ON "Post"."id" = "Comment_1"."postId" WHERE "Post"."id" = ?1`, values: [id] };
            },
            listQuery(lastSeen_id: number, limit: number): SqlStatement {
                return { query: `SELECT "Post"."id" AS "id", "Post"."title" AS "title", "Post"."content" AS "content", "Comment_1"."id" AS "comments.id", "Comment_1"."content" AS "comments.content", "Comment_1"."upvotes" AS "comments.upvotes", "Comment_1"."postId" AS "comments.postId" FROM "Post" LEFT JOIN "Comment" AS "Comment_1" ON "Post"."id" = "Comment_1"."postId" WHERE "Post"."id" > ?1 ORDER BY "Post"."id" ASC LIMIT ?2`, values: [lastSeen_id, limit] };
            },
            async get(env: { ctx: SubRedditDo }, subId: number, id: number): Promise<HttpResult<Self | null>> {
                const stmt = this.getQuery(id);
                const seed = { subId,  } as DeepPartial<Self>;
                const res = await CloesceOrm.fromEnv(env).get<Self>(Meta, stmt, this.tree, seed);
                if (res.errors.length > 0) {
                    return HttpResult.fail(400, CloesceError.displayErrors(res));
                }
                if (res.value === null) {
                    return HttpResult.fail(404);
                }
                return HttpResult.ok(200, res.value);
            },
            async list(env: { ctx: SubRedditDo }, subId: number, lastSeen_id: number, limit: number): Promise<HttpResult<Self[]>> {
                const stmt = this.listQuery(lastSeen_id, limit);
                const seed = { subId,  } as DeepPartial<Self>;
                const res = await CloesceOrm.fromEnv(env).list<Self>(Meta, stmt, this.tree, seed);
                if (res.errors.length > 0) {
                    return HttpResult.fail(400, CloesceError.displayErrors(res));
                }
                return HttpResult.ok(200, res.value!);
            },
            async save(env: { ctx: SubRedditDo }, subId: number, model: DeepPartial<Post.Self>): Promise<HttpResult<Self | null>> {
                const res = await CloesceOrm.fromEnv(env).upsert<Self>(Meta, { ...model, subId } as DeepPartial<Self>, this.tree);
                if (res.errors.length > 0) {
                    return HttpResult.fail(400, CloesceError.displayErrors(res));
                }
                if (res.value === null) {
                    return HttpResult.fail(404);
                }
                return HttpResult.ok(200, res.value);
            },
        };
    }
    export namespace Custom {
        export interface Crud {
            get(env: { SubRedditDo: Env["SubRedditDo"] }, id: number, subId: number): ApiResult<Self>;
            list(env: { SubRedditDo: Env["SubRedditDo"] }, subId: number): ApiResult<Self[]>;
            save(env: { SubRedditDo: Env["SubRedditDo"] }, post: DeepPartial<Post.Self>, subId: number): ApiResult<Self>;
        }
        export type Impl = typeof GeneratedSource.Custom & Crud;
        export function impl<I extends Crud>(implObj: I & ThisType<typeof GeneratedSource.Custom & I>): typeof GeneratedSource.Custom & I {
            return _implDs(GeneratedSource.Custom, implObj);
        }
    }

    export function impl<Impl extends Api & Sources>(implObj: Impl & ThisType<{ tag: string; Orm: typeof Orm; Default: typeof GeneratedSource.Default } & Impl>): { tag: string; Orm: typeof Orm; Default: typeof GeneratedSource.Default } & Impl {
        return _impl("Post", { Orm, Default: GeneratedSource.Default }, implObj) as any;
    }

    export namespace Orm {

        export async function save(ctx: SubRedditDo, newModel: DeepPartial<Self>, include: IncludeTree<Self> = GeneratedSource.Default.tree): Promise<CloesceResult<Self | null>> {
            return await CloesceOrm.fromEnv({ ctx: ctx }).upsert<Self>(Meta, newModel, include);
        }

        export async function get(ctx: SubRedditDo, args: { subId: number, include?: IncludeTree<Self> }): Promise<CloesceResult<Self>> {
            const include = args.include ?? GeneratedSource.Default.tree;
            const base = { subId: args.subId,  } as DeepPartial<Self>;
            return await CloesceOrm.fromEnv({ ctx: ctx }).hydrate<Self>(Meta, base, include);
        }

        export async function hydrate(ctx: SubRedditDo, base: DeepPartial<Self>, include: IncludeTree<Self> = GeneratedSource.Default.tree): Promise<CloesceResult<Self>> {
            return await CloesceOrm.fromEnv({ ctx: ctx }).hydrate<Self>(Meta, base, include);
        }
    }
}
export namespace SubReddit {
    export const Tag = "SubReddit" as const;
    export const Meta = cidl.models.SubReddit as any;

    export interface Self {
        subId: number;
        metadata: unknown;
        globalMetadata: KValue<unknown>;
    }

    export interface Api {
        newSubReddit(
        ): ApiResult<SubReddit.Self>;
        feed(
            self: SubReddit.Self,
            env: {
                ctx: SubRedditDo,
            },
            subId: number,
        ): ApiResult<Post.Self[]>;
    }
    export const _api = undefined as unknown as Api;

    export interface Sources {
    }

    export namespace GeneratedSource {
        export const Default = {
            tree: {"globalMetadata":{},"metadata":{}},
            async get(env: { ctx: SubRedditDo, GlobalSubRedditMetadata: Env["GlobalSubRedditMetadata"], SubRedditDo: Env["SubRedditDo"] }, subId: number): Promise<HttpResult<Self | null>> {
                const base = { subId } as DeepPartial<Self>;
                const res = await CloesceOrm.fromEnv(env).hydrate<Self>(Meta, base, this.tree);
                if (res.errors.length > 0) {
                    return HttpResult.fail(400, CloesceError.displayErrors(res));
                }
                return HttpResult.ok(200, res.value);
            },
            async save(env: { ctx: SubRedditDo, GlobalSubRedditMetadata: Env["GlobalSubRedditMetadata"], SubRedditDo: Env["SubRedditDo"] }, subId: number, model: DeepPartial<SubReddit.Self>): Promise<HttpResult<Self | null>> {
                const res = await CloesceOrm.fromEnv(env).upsert<Self>(Meta, { ...model, subId } as DeepPartial<Self>, this.tree);
                if (res.errors.length > 0) {
                    return HttpResult.fail(400, CloesceError.displayErrors(res));
                }
                if (res.value === null) {
                    return HttpResult.fail(404);
                }
                return HttpResult.ok(200, res.value);
            },
        };
    }

    export function impl<Impl extends Api & Sources>(implObj: Impl & ThisType<{ tag: string; Orm: typeof Orm; Default: typeof GeneratedSource.Default } & Impl>): { tag: string; Orm: typeof Orm; Default: typeof GeneratedSource.Default } & Impl {
        return _impl("SubReddit", { Orm, Default: GeneratedSource.Default }, implObj) as any;
    }

    export namespace Orm {

        export async function save(ctx: SubRedditDo, newModel: DeepPartial<Self>, include: IncludeTree<Self> = GeneratedSource.Default.tree): Promise<CloesceResult<Self | null>> {
            return await CloesceOrm.fromEnv({ ctx: ctx }).upsert<Self>(Meta, newModel, include);
        }

        export async function get(ctx: SubRedditDo, args: { subId: number, include?: IncludeTree<Self> }): Promise<CloesceResult<Self>> {
            const include = args.include ?? GeneratedSource.Default.tree;
            const base = { subId: args.subId,  } as DeepPartial<Self>;
            return await CloesceOrm.fromEnv({ ctx: ctx }).hydrate<Self>(Meta, base, include);
        }

        export async function hydrate(ctx: SubRedditDo, base: DeepPartial<Self>, include: IncludeTree<Self> = GeneratedSource.Default.tree): Promise<CloesceResult<Self>> {
            return await CloesceOrm.fromEnv({ ctx: ctx }).hydrate<Self>(Meta, base, include);
        }
    }
}
export namespace Comment {
    export const Tag = "Comment" as const;
    export const Meta = cidl.models.Comment as any;

    export interface Self {
        id: number;
        content: string;
        upvotes: number;
        postId: number;
        subId: number;
    }

    export interface Api {
    }
    export const _api = undefined as unknown as Api;

    export interface Sources {
    }

    export namespace GeneratedSource {
        export const Default = {
            tree: {},
            selectQuery: `SELECT "Comment"."id" AS "id", "Comment"."content" AS "content", "Comment"."upvotes" AS "upvotes", "Comment"."postId" AS "postId" FROM "Comment"`,

            getQuery(id: number): SqlStatement {
                return { query: `SELECT "Comment"."id" AS "id", "Comment"."content" AS "content", "Comment"."upvotes" AS "upvotes", "Comment"."postId" AS "postId" FROM "Comment" WHERE "Comment"."id" = ?1`, values: [id] };
            },
            listQuery(lastSeen_id: number, limit: number): SqlStatement {
                return { query: `SELECT "Comment"."id" AS "id", "Comment"."content" AS "content", "Comment"."upvotes" AS "upvotes", "Comment"."postId" AS "postId" FROM "Comment" WHERE "Comment"."id" > ?1 ORDER BY "Comment"."id" ASC LIMIT ?2`, values: [lastSeen_id, limit] };
            },
            async get(env: { ctx: SubRedditDo }, subId: number, id: number): Promise<HttpResult<Self | null>> {
                const stmt = this.getQuery(id);
                const seed = { subId,  } as DeepPartial<Self>;
                const res = await CloesceOrm.fromEnv(env).get<Self>(Meta, stmt, this.tree, seed);
                if (res.errors.length > 0) {
                    return HttpResult.fail(400, CloesceError.displayErrors(res));
                }
                if (res.value === null) {
                    return HttpResult.fail(404);
                }
                return HttpResult.ok(200, res.value);
            },
            async list(env: { ctx: SubRedditDo }, subId: number, lastSeen_id: number, limit: number): Promise<HttpResult<Self[]>> {
                const stmt = this.listQuery(lastSeen_id, limit);
                const seed = { subId,  } as DeepPartial<Self>;
                const res = await CloesceOrm.fromEnv(env).list<Self>(Meta, stmt, this.tree, seed);
                if (res.errors.length > 0) {
                    return HttpResult.fail(400, CloesceError.displayErrors(res));
                }
                return HttpResult.ok(200, res.value!);
            },
            async save(env: { ctx: SubRedditDo }, subId: number, model: DeepPartial<Comment.Self>): Promise<HttpResult<Self | null>> {
                const res = await CloesceOrm.fromEnv(env).upsert<Self>(Meta, { ...model, subId } as DeepPartial<Self>, this.tree);
                if (res.errors.length > 0) {
                    return HttpResult.fail(400, CloesceError.displayErrors(res));
                }
                if (res.value === null) {
                    return HttpResult.fail(404);
                }
                return HttpResult.ok(200, res.value);
            },
        };
    }

    export function impl<Impl extends Api & Sources>(implObj: Impl & ThisType<{ tag: string; Orm: typeof Orm; Default: typeof GeneratedSource.Default } & Impl>): { tag: string; Orm: typeof Orm; Default: typeof GeneratedSource.Default } & Impl {
        return _impl("Comment", { Orm, Default: GeneratedSource.Default }, implObj) as any;
    }

    export namespace Orm {

        export async function save(ctx: SubRedditDo, newModel: DeepPartial<Self>, include: IncludeTree<Self> = GeneratedSource.Default.tree): Promise<CloesceResult<Self | null>> {
            return await CloesceOrm.fromEnv({ ctx: ctx }).upsert<Self>(Meta, newModel, include);
        }

        export async function get(ctx: SubRedditDo, args: { subId: number, include?: IncludeTree<Self> }): Promise<CloesceResult<Self>> {
            const include = args.include ?? GeneratedSource.Default.tree;
            const base = { subId: args.subId,  } as DeepPartial<Self>;
            return await CloesceOrm.fromEnv({ ctx: ctx }).hydrate<Self>(Meta, base, include);
        }

        export async function hydrate(ctx: SubRedditDo, base: DeepPartial<Self>, include: IncludeTree<Self> = GeneratedSource.Default.tree): Promise<CloesceResult<Self>> {
            return await CloesceOrm.fromEnv({ ctx: ctx }).hydrate<Self>(Meta, base, include);
        }
    }
}

function _impl(modelName: string, extras: Record<string, any>, implObj: any) {
    const base: any = { ...implObj, ...extras, tag: modelName };
    for (const key of Object.keys(base)) {
        const v = base[key];
        if (typeof v === "function") base[key] = v.bind(base);
    }
    return base;
}

function _implDs(generated: Record<string, any>, user: Record<string, any>) {
    const merged: any = { ...generated, ...user };
    for (const key of Object.keys(merged)) {
        const v = merged[key];
        if (typeof v === "function") merged[key] = v.bind(merged);
    }
    return merged;
}

import cidl from "./cidl.json" with { type: "json" };

export function cloesce(env: CfEnv): CloesceApp {
    // @ts-expect-error
    return new CloesceApp(cidl as any, "http://localhost:5843/api", upgradeEnv(env));
}

// Default entrypoint for a Cloesce app.
// Replace with a custom fetch handler to register API implementations, add middleware, etc.
export default {
    async fetch(request: Request, env: CfEnv): Promise<Response> {
        const app = cloesce(env);
        return await app.run(request);
    }
}