import { D1Database } from "@cloudflare/workers-types/experimental/index.js";

import { OrmWasmExports, mapSql, loadOrmWasm } from "./wasm.js";
import { CrudContext } from "./crud.js";
import { HttpResult, IncludeTree, Orm } from "../ui/backend.js";
import { Either, KeysOfType } from "../ui/common.js";
import {
  CidlType,
  CloesceAst,
  Model,
  ModelMethod,
  NO_DATA_SOURCE,
  getNavigationPropertyCidlType,
  isNullableType,
} from "../ast.js";

/**
 * Dependency injection container, mapping an object type name to an instance of that object.
 *
 * Comes with the WranglerEnv and Request by default.
 */
export type DependencyInjector = Map<string, any>;

/**
 * Map of model names to their respective constructor.
 *
 * The value accepted into the `cloesce` function is generated by the Cloesce compiler, and
 * is guaranteed to contain all model definitions.
 */
type ModelConstructorRegistry = Record<string, new () => any>;

/**
 * Meta information on the wrangler env and db bindings
 */
interface MetaWranglerEnv {
  envName: string;
  dbName: string; // TODO: support many db's
}

export type MiddlewareFn = (
  request: Request,
  env: any,
  di: DependencyInjector,
) => Promise<HttpResult | void>;

export type ResultMiddlewareFn = (
  request: Request,
  env: any,
  di: DependencyInjector,
  result: HttpResult,
) => Promise<HttpResult | void>;

export class CloesceApp {
  private globalMiddleware: MiddlewareFn[] = [];
  private modelMiddleware: Map<string, MiddlewareFn[]> = new Map();
  private methodMiddleware: Map<string, Map<string, MiddlewareFn[]>> =
    new Map();

  private resultMiddleware: ResultMiddlewareFn[] = [];

  public routePrefix: string = "api";

  /**
   * Registers global middleware which runs before any route matching.
   *
   * @param m - The middleware function to register.
   */
  public onRequest(m: MiddlewareFn) {
    this.globalMiddleware.push(m);
  }

  /**
   * Registers middleware which runs after the response is generated, but before
   * it is returned to the client.
   *
   * Optionally, return a new HttpResult to short-circuit the response.
   *
   * Errors thrown in response middleware are caught and returned as a 500 response.
   *
   * Errors thrown in earlier middleware or route processing are not caught here.
   *
   * @param m - The middleware function to register.
   */
  public onResult(m: ResultMiddlewareFn) {
    this.resultMiddleware.push(m);
  }

  /**
   * Registers middleware for a specific model type.
   *
   * Runs before request validation and method middleware.
   *
   * @typeParam T - The model type.
   * @param ctor - The model constructor (used to derive its name).
   * @param m - The middleware function to register.
   */
  public onModel<T>(ctor: new () => T, m: MiddlewareFn) {
    if (this.modelMiddleware.has(ctor.name)) {
      this.modelMiddleware.get(ctor.name)!.push(m);
    } else {
      this.modelMiddleware.set(ctor.name, [m]);
    }
  }

  /**
   * Registers middleware for a specific method on a model.
   *
   * Runs after model middleware and request validation.
   *
   * @typeParam T - The model type.
   * @param ctor - The model constructor (used to derive its name).
   * @param method - The method name on the model.
   * @param m - The middleware function to register.
   */
  public onMethod<T>(
    ctor: new () => T,
    method: KeysOfType<T, (...args: any) => any>,
    m: MiddlewareFn,
  ) {
    if (!this.methodMiddleware.has(ctor.name)) {
      this.methodMiddleware.set(ctor.name, new Map());
    }

    const methods = this.methodMiddleware.get(ctor.name)!;
    if (!methods.has(method)) {
      methods.set(method, []);
    }

    methods.get(method)!.push(m);
  }

  /**
   * Router entry point. Undergoes route matching, request validation, hydration, and method dispatch.
   */
  private async cloesce(
    request: Request,
    env: any,
    ast: CloesceAst,
    constructorRegistry: ModelConstructorRegistry,
    di: DependencyInjector,
    d1: D1Database,
  ): Promise<HttpResult> {
    // Global middleware
    for (const m of this.globalMiddleware) {
      const res = await m(request, env, di);
      if (res) {
        return res;
      }
    }

    // Route match
    const route = matchRoute(request, ast, this.routePrefix);
    if (route.isLeft()) {
      return route.value;
    }
    const { method, model, id } = route.unwrap();

    // Model middleware
    for (const m of this.modelMiddleware.get(model.name) ?? []) {
      const res = await m(request, env, di);
      if (res) {
        return res;
      }
    }

    // Request validation
    const validation = await validateRequest(request, ast, model, method, id);
    if (validation.isLeft()) {
      return validation.value;
    }
    const { params, dataSource } = validation.unwrap();

    // Method middleware
    for (const m of this.methodMiddleware.get(model.name)?.get(method.name) ??
      []) {
      const res = await m(request, env, di);
      if (res) {
        return res;
      }
    }

    // Hydration
    const crudCtx = await (async () => {
      if (method.is_static) {
        return Either.right(
          CrudContext.fromCtor(d1, constructorRegistry[model.name]),
        );
      }

      const hydratedModel = await hydrateModel(
        constructorRegistry,
        d1,
        model,
        id!, // id must exist after matchRoute
        dataSource!, // ds must exist after validateRequest
      );

      return hydratedModel.map((_) =>
        CrudContext.fromInstance(
          d1,
          hydratedModel.value,
          constructorRegistry[model.name],
        ),
      );
    })();
    if (crudCtx.isLeft()) {
      return crudCtx.value;
    }

    // Method dispatch
    return await methodDispatch(crudCtx.unwrap(), di, method, params);
  }

  /**
   * Runs the Cloesce app. Intended to be called from the generated workers code.
   */
  public async run(
    request: Request,
    env: any,
    ast: CloesceAst,
    constructorRegistry: ModelConstructorRegistry,
    envMeta: MetaWranglerEnv,
  ): Promise<Response> {
    const di: DependencyInjector = new Map();
    di.set(envMeta.envName, env);
    di.set("Request", request);

    await RuntimeContainer.init(ast, constructorRegistry);
    const d1: D1Database = env[envMeta.dbName]; // TODO: multiple dbs

    try {
      // Core cloesce processing
      const response = await this.cloesce(
        request,
        env,
        ast,
        constructorRegistry,
        di,
        d1,
      );

      // Response middleware
      for (const m of this.resultMiddleware) {
        const res = await m(request, env, di, response);
        if (res) {
          return res.toResponse();
        }
      }

      return response.toResponse();
    } catch (e: any) {
      console.error(JSON.stringify(e));
      return HttpResult.fail(500, e.toString()).toResponse();
    }
  }
}

/**
 * Given a request, this represents a map of each body / url  param name to
 * its actual value. Unknown, as the a request can be anything.
 */
export type RequestParamMap = Record<string, unknown>;

/**
 * Singleton instance containing the cidl, constructor registry, and wasm binary.
 * These values are guaranteed to never change throughout a workers lifetime.
 */
export class RuntimeContainer {
  private static instance: RuntimeContainer | undefined;
  private constructor(
    public readonly ast: CloesceAst,
    public readonly constructorRegistry: ModelConstructorRegistry,
    public readonly wasm: OrmWasmExports,
  ) {}

  static async init(
    ast: CloesceAst,
    constructorRegistry: ModelConstructorRegistry,
    wasm?: WebAssembly.Instance,
  ) {
    if (this.instance) return;
    const wasmAbi = await loadOrmWasm(ast, wasm);
    this.instance = new RuntimeContainer(ast, constructorRegistry, wasmAbi);
  }

  static get(): RuntimeContainer {
    return this.instance!;
  }
}

/**
 * Matches a request to a method on a model.
 * @param apiRoute The route from the domain to the actual API, ie https://foo.com/route/to/api => route/to/api/
 * @returns 404 or a `MatchedRoute`
 */
function matchRoute(
  request: Request,
  ast: CloesceAst,
  routePrefix: string,
): Either<
  HttpResult,
  {
    model: Model;
    method: ModelMethod;
    id: string | null;
  }
> {
  const url = new URL(request.url);
  const parts = url.pathname.split("/").filter(Boolean);
  const prefix = routePrefix.split("/").filter(Boolean);

  // Error state: We expect an exact request format, and expect that the model
  // and are apart of the CIDL
  const notFound = (e: string) =>
    Either.left(HttpResult.fail(404, `Path not found: ${e} ${url.pathname}`));

  for (const p of prefix) {
    if (parts.shift() !== p) return notFound(`Missing prefix segment "${p}"`);
  }

  if (parts.length < 2) {
    return notFound("Expected /model/method or /model/:id/method");
  }

  // Attempt to extract from routeParts
  const modelName = parts[0];
  const methodName = parts[parts.length - 1];
  const id = parts.length === 3 ? parts[1] : null;

  const model = ast.models[modelName];
  if (!model) {
    return notFound(`Unknown model ${modelName}`);
  }

  const method = model.methods[methodName];
  if (!method) {
    return notFound(`Unknown method ${modelName}.${methodName}`);
  }

  if (request.method !== method.http_verb) {
    return notFound("Unmatched HTTP method");
  }

  return Either.right({
    model,
    method,
    id,
  });
}

/**
 * Validates the request's body/search params against a ModelMethod
 * @returns 400 or a `RequestParamMap` consisting of each parameters name mapped to its value, and
 * a data source
 */
async function validateRequest(
  request: Request,
  ast: CloesceAst,
  model: Model,
  method: ModelMethod,
  id: string | null,
): Promise<
  Either<HttpResult, { params: RequestParamMap; dataSource: string | null }>
> {
  // Error state: any missing parameter, body, or malformed input will exit with 400.
  const invalidRequest = (e: string) =>
    Either.left(HttpResult.fail(400, `Invalid Request Body: ${e}`));

  if (!method.is_static && id == null) {
    return invalidRequest("Id's are required for instantiated methods.");
  }

  // Filter out any injected parameters that will not be passed
  // by the query.
  const requiredParams = method.parameters.filter(
    (p) => !(typeof p.cidl_type === "object" && "Inject" in p.cidl_type),
  );

  // Extract url or body parameters
  const url = new URL(request.url);
  let params: RequestParamMap = {};
  if (method.http_verb === "GET") {
    params = Object.fromEntries(url.searchParams.entries());
  } else {
    try {
      params = await request.json();
    } catch {
      return invalidRequest("Could not retrieve JSON body.");
    }
  }

  // Ensure all required params exist
  if (!requiredParams.every((p) => p.name in params)) {
    return invalidRequest(`Missing parameters.`);
  }

  // Validate all parameters type
  for (const p of requiredParams) {
    const value = params[p.name];
    const isPartial =
      typeof p.cidl_type !== "string" && "Partial" in p.cidl_type;

    if (!validateCidlType(ast, value, p.cidl_type, isPartial)) {
      return invalidRequest("Invalid parameters.");
    }
  }

  // Validate data source if exists
  const dataSourceParam = requiredParams.find(
    (p) => typeof p.cidl_type === "object" && "DataSource" in p.cidl_type,
  );
  const dataSource = dataSourceParam
    ? (params[dataSourceParam.name] as string)
    : null;
  if (
    dataSource &&
    dataSource !== NO_DATA_SOURCE &&
    !(dataSource in model.data_sources)
  ) {
    return invalidRequest(`Unknown data source ${dataSource}`);
  }

  return Either.right({ params, dataSource });
}

/**
 * Queries D1 for a particular model's ID, then transforms the SQL column output into
 * an instance of a model using the provided include tree and metadata as a guide.
 * @returns 404 if no record was found for the provided ID
 * @returns 500 if the D1 database is not synced with Cloesce and yields an error
 * @returns The instantiated model on success
 */
async function hydrateModel(
  constructorRegistry: ModelConstructorRegistry,
  d1: D1Database,
  model: Model,
  id: string,
  dataSource: string,
): Promise<Either<HttpResult, object>> {
  // Error state: If the D1 database has been tweaked outside of Cloesce
  // resulting in a malformed query, exit with a 500.
  const malformedQuery = (e: any) =>
    Either.left(
      HttpResult.fail(
        500,
        `Error in hydration query, is the database out of sync with the backend?: ${e instanceof Error ? e.message : String(e)}`,
      ),
    );

  // Error state: If no record is found for the id, return a 404
  const missingRecord = Either.left(HttpResult.fail(404, "Record not found"));

  // Query DB
  let records;
  try {
    let includeTree: IncludeTree<any> | null =
      dataSource === NO_DATA_SOURCE
        ? null
        : (constructorRegistry[model.name] as any)[dataSource];

    records = await d1
      .prepare(Orm.getQuery(constructorRegistry[model.name], includeTree))
      .bind(id)
      .run();

    if (!records?.results) {
      return missingRecord;
    }
    if (records.error) {
      return malformedQuery(records.error);
    }
  } catch (e) {
    return malformedQuery(e);
  }

  // Hydrate
  const models: object[] = mapSql(
    constructorRegistry[model.name],
    records.results,
    model.data_sources[dataSource]?.tree ?? {},
  ).value as object[];

  return Either.right(models[0]);
}

/**
 * Calls a method on a model given a list of parameters.
 * @returns 500 on an uncaught client error, 200 with a result body on success
 */
async function methodDispatch(
  crudCtx: CrudContext,
  instanceRegistry: DependencyInjector,
  method: ModelMethod,
  params: Record<string, unknown>,
): Promise<HttpResult<unknown>> {
  // Error state: Client code ran into an uncaught exception.
  const uncaughtException = (e: any) =>
    HttpResult.fail(
      500,
      `Uncaught exception in method dispatch: ${e instanceof Error ? e.message : String(e)}`,
    );

  const paramArray = [];
  for (const param of method.parameters) {
    if (params[param.name]) {
      paramArray.push(params[param.name]);
      continue;
    }

    // Injected type
    const injected = instanceRegistry.get((param.cidl_type as any)["Inject"]);
    if (!injected) {
      // Error state: Injected parameters cannot be found at compile time, only at runtime.
      // If a injected reference does not exist, throw a 500.
      return HttpResult.fail(
        500,
        `An injected parameter was missing from the instance registry: ${JSON.stringify(param.cidl_type)}`,
      );
    }

    paramArray.push(injected);
  }

  // Ensure the result is always some HttpResult
  const resultWrapper = (res: any): HttpResult<unknown> => {
    const rt = method.return_type;

    if (rt === null) {
      return HttpResult.ok(200);
    }

    if (typeof rt === "object" && rt !== null && "HttpResult" in rt) {
      return res as HttpResult<unknown>;
    }

    return HttpResult.ok(200, res);
  };

  try {
    const res = await crudCtx.interceptCrud(method.name)(...paramArray);
    return resultWrapper(res);
  } catch (e) {
    return uncaughtException(e);
  }
}

/**
 * Runtime type validation for CIDL types.
 *
 * Returns true if the value matches the CIDL type, false otherwise.
 */
function validateCidlType(
  ast: CloesceAst,
  value: unknown,
  cidlType: CidlType,
  isPartial: boolean,
): boolean {
  if (value === undefined) return isPartial;

  // TODO: consequences of null checking like this? 'null' is passed in
  // as a string for GET requests
  const nullable = isNullableType(cidlType);
  if (value == null || value === "null") return nullable;

  if (nullable) {
    cidlType = (cidlType as any).Nullable; // Unwrap the nullable type
  }

  // Handle primitive string types with switch
  if (typeof cidlType === "string") {
    switch (cidlType) {
      case "Integer":
        return Number.isInteger(Number(value));
      case "Real":
        return !Number.isNaN(Number(value));
      case "Text":
        return typeof value === "string";
      case "Boolean":
        return typeof value === "boolean";
      case "DateIso":
        const date = new Date(value as string);
        return !isNaN(date.getTime());
      default:
        return false;
    }
  }

  // Handle Data Sources
  if ("DataSource" in cidlType) {
    return typeof value === "string";
  }

  // Handle Models
  let cidlTypeAccessor =
    "Partial" in cidlType
      ? cidlType.Partial
      : "Object" in cidlType
        ? cidlType.Object
        : undefined;

  if (cidlTypeAccessor && ast.models[cidlTypeAccessor]) {
    const model = ast.models[cidlTypeAccessor];
    if (!model || typeof value !== "object") return false;
    const valueObj = value as Record<string, unknown>;

    // Validate attributes
    if (
      !model.attributes.every((attr) =>
        validateCidlType(
          ast,
          valueObj[attr.value.name],
          attr.value.cidl_type,
          isPartial,
        ),
      )
    ) {
      return false;
    }

    // Validate navigation properties
    return model.navigation_properties.every((nav) => {
      const navValue = valueObj[nav.var_name];

      return (
        navValue == null ||
        validateCidlType(
          ast,
          navValue,
          getNavigationPropertyCidlType(nav),
          isPartial,
        )
      );
    });
  }

  // Handle Plain Old Objects
  if (cidlTypeAccessor && ast.poos[cidlTypeAccessor]) {
    const poo = ast.poos[cidlTypeAccessor];
    if (!poo || typeof value !== "object") return false;
    const valueObj = value as Record<string, unknown>;

    // Validate attributes
    if (
      !poo.attributes.every((attr) =>
        validateCidlType(ast, valueObj[attr.name], attr.cidl_type, isPartial),
      )
    ) {
      return false;
    }

    return true;
  }

  if ("Array" in cidlType) {
    const arr = cidlType.Array;
    return (
      Array.isArray(value) &&
      value.every((v) => validateCidlType(ast, v, arr, isPartial))
    );
  }

  if ("HttpResult" in cidlType) {
    if (value === null) return cidlType.HttpResult === null;
    if (cidlType.HttpResult === null) return false;
    return validateCidlType(ast, value, cidlType.HttpResult, isPartial);
  }

  return false;
}

/**
 * For testing purposes
 */
export const _cloesceInternal = {
  matchRoute,
  validateRequest,
  methodDispatch,
  RuntimeContainer,
};
