// GENERATED BY CLOESCE. DO NOT MODIFY.
// @ts-nocheck
export class Validator {
  id: number;
  email: string;
  name: string;
  data: KValue<string>;
  async someMethod(
    id: number,
    name: string,
    fetchImpl: typeof fetch = fetch
  ): Promise<HttpResult<void>> {
    const __id = [
      encodeURIComponent(String(this.id)),
      encodeURIComponent(String(this.name)),
    ].join("/");
    const __baseUrl = new URL(
      `http://localhost:5038/api/Validator/${__id}/someMethod`
    );
    const __payload: any = {};
    __payload["id"] = id;
    __payload["name"] = name;

    const __res = await fetchImpl(__baseUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: requestBody(MediaType.Json, __payload),
    });

    return await HttpResult.fromResponse(
      __res,
      MediaType.Json,
      undefined,
      false
    );
  }
  static async $save(
    args: { Default: DeepPartial<Validator> } | { None: DeepPartial<Validator> },
    fetchImpl: typeof fetch = fetch
  ): Promise<HttpResult<Validator>> {
    const __resolvedKind: "Default" | "None" = dsKey(args) as any;
    const __baseUrl = new URL(
      `http://localhost:5038/api/Validator/$save`
    );
    const __payload: any = {};
    __payload["model"] = args[__resolvedKind];
    __baseUrl.searchParams.append("__datasource", __resolvedKind);

    const __res = await fetchImpl(__baseUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: requestBody(MediaType.Json, __payload),
    });

    return await HttpResult.fromResponse(
      __res,
      MediaType.Json,
      Validator,
      false
    );
  }
  static async $get(
    args: { Default: { name: string; id: number; }} | { None: { name: string; id: number; }},
    fetchImpl: typeof fetch = fetch
  ): Promise<HttpResult<Validator>> {
    const __resolvedKind: "Default" | "None" = dsKey(args) as any;
    const __resolvedArgs: any = args[__resolvedKind];
    const __baseUrl = new URL(
      `http://localhost:5038/api/Validator/$get`
    );
    __baseUrl.searchParams.append("name", String(__resolvedArgs?.name ?? null));
    __baseUrl.searchParams.append("Default_id", String(args?.Default?.id ?? null));
    __baseUrl.searchParams.append("None_id", String(args?.None?.id ?? null));
    __baseUrl.searchParams.append("__datasource", __resolvedKind);

    const __res = await fetchImpl(__baseUrl, {
      method: "GET",
    });

    return await HttpResult.fromResponse(
      __res,
      MediaType.Json,
      Validator,
      false
    );
  }
  static async $list(
    args: { Default: { lastSeen_id: number; limit: number; }} | { None: { lastSeen_id: number; limit: number; }},
    fetchImpl: typeof fetch = fetch
  ): Promise<HttpResult<Validator[]>> {
    const __resolvedKind: "Default" | "None" = dsKey(args) as any;
    const __baseUrl = new URL(
      `http://localhost:5038/api/Validator/$list`
    );
    __baseUrl.searchParams.append("Default_lastSeen_id", String(args?.Default?.lastSeen_id ?? null));
    __baseUrl.searchParams.append("Default_limit", String(args?.Default?.limit ?? null));
    __baseUrl.searchParams.append("None_lastSeen_id", String(args?.None?.lastSeen_id ?? null));
    __baseUrl.searchParams.append("None_limit", String(args?.None?.limit ?? null));
    __baseUrl.searchParams.append("__datasource", __resolvedKind);

    const __res = await fetchImpl(__baseUrl, {
      method: "GET",
    });

    return await HttpResult.fromResponse(
      __res,
      MediaType.Json,
      Validator,
      true
    );
  }

  static fromJson(data: any): Validator {
    const __res = Object.assign(new Validator(), data);
    if (__res.data) __res.data = Object.assign(new KValue(), __res.data);
    return __res;
  }
}

function dsKey(args: object): string {
  return Object.keys(args)[0];
}

type DeepPartialInner<T> = T extends (infer U)[]
  ? DeepPartialInner<U>[]
  : T extends object
  ? { [K in keyof T]?: DeepPartialInner<T[K]> }
  : T | (null extends T ? null : never);
export type DeepPartial<T> = DeepPartialInner<T> & { __brand?: "Partial" };

export class KValue<V> {
  key!: string;
  raw: unknown | null;
  metadata: unknown | null;
  get value(): V | null {
    return this.raw as V | null;
  }
}

export interface Paginated<T> {
  results: T[];
  cursor: string | null;
  complete: boolean;
}

export enum MediaType {
  Json = "Json",
  Octet = "Octet",
}

declare const Buffer: any;
export function b64ToU8(b64: string): Uint8Array {
  if (typeof Buffer !== "undefined") {
    const buffer = Buffer.from(b64, "base64");
    return new Uint8Array(buffer);
  }
  const s = atob(b64);
  const u8 = new Uint8Array(s.length);
  for (let i = 0; i < s.length; i++) {
    u8[i] = s.charCodeAt(i);
  }
  return u8;
}

export function u8ToB64(u8: Uint8Array): string {
  if (typeof Buffer !== "undefined") {
    return Buffer.from(u8).toString("base64");
  }
  let s = "";
  for (let i = 0; i < u8.length; i++) {
    s += String.fromCharCode(u8[i]);
  }
  return btoa(s);
}

export class R2Object {
  key!: string;
  version!: string;
  size!: number;
  etag!: string;
  httpEtag!: string;
  uploaded!: Date;
  customMetadata?: Record<string, string>;
}

function requestBody(
  mediaType: MediaType,
  data: any | string | undefined,
): BodyInit | undefined {
  switch (mediaType) {
    case MediaType.Json: {
      return JSON.stringify(data ?? {}, (_, v) => {
        if (v instanceof Uint8Array) {
          return u8ToB64(v);
        }
        return v;
      });
    }
    case MediaType.Octet: {
      return Object.values(data)[0] as BodyInit;
    }
  }
}

export class HttpResult<T = unknown> {
  public constructor(
    public ok: boolean,
    public status: number,
    public headers: Headers,
    public data?: T,
    public message?: string,
    public mediaType?: MediaType,
  ) { }

  static async fromResponse(
    response: Response,
    mediaType: MediaType,
    ctor?: any,
    array: boolean = false,
  ): Promise<HttpResult<any>> {
    if (response.status >= 400) {
      return new HttpResult(
        false,
        response.status,
        response.headers,
        undefined,
        await response.text(),
      );
    }

    function instantiate(json: any, ctor?: any) {
      switch (ctor) {
        case Date: {
          return new Date(json);
        }
        case Uint8Array: {
          return b64ToU8(json);
        }
        case undefined: {
          return json;
        }
        default: {
          return ctor.fromJson(json);
        }
      }
    }

    async function data() {
      switch (mediaType) {
        case MediaType.Json: {
          const data = await response.json();

          if (array && Array.isArray(data)) {
            for (let i = 0; i < data.length; i++) {
              data[i] = instantiate(data[i], ctor);
            }
            return data;
          }
          return instantiate(data, ctor);
        }
        case MediaType.Octet: {
          return response;
        }
      }
    }
    return new HttpResult(
      true,
      response.status,
      response.headers,
      await data(),
    );
  }
}