use idl::{CidlType, CloesceIdl, IncludeTree, Model, NavigationCardinality};
use serde_json::Value as JsonValue;

use frontend::fmt_cidl_type;

use crate::query::save::plan::{
    PathSegment, SaveArg, SavePlan, SaveQuery, SaveStep, SqlStatement, TMP_TABLE,
};
use crate::query::{Database, DatabaseKind, TemplateSegment};
use crate::validate::validate_cidl_type;
use crate::{OrmErrorKind, Result, fail};

/// Converts a payload into a [SavePlan].
///
/// Accepts a payload object describing the update/insert (or both) to take place,
/// adapting to the payload's shape to determine the sequence of writes and hydrations.
///
/// Every upsert sequence is followed by a select sequence that reads back the inserted/updated rows,
/// so the response is the database truth in payload order.
pub fn plan<'src>(
    model: &str,
    idl: &'src CloesceIdl<'src>,
    tree: &IncludeTree<'src>,
    payload: &'src JsonValue,
) -> Result<SavePlan<'src>> {
    let mut planner = Planner {
        idl,
        batches: Vec::new(),
        steps: Vec::new(),
    };

    let Some(root) = idl.models.get(model) else {
        // Fail silently if the model is not found
        return Ok(SavePlan::default());
    };

    planner.visit(root, payload, tree, vec![], ParentCtx::default())?;
    Ok(planner.emit())
}

#[derive(Default, Clone)]
struct ParentCtx<'src> {
    /// child column name -> the value the parent supplies for it.
    bindings: Vec<(&'src str, PkSource<'src>)>,

    /// Shard args for a nested DO child, if the parent routes it to a specific stub.
    shard: Vec<(&'src str, SaveArg<'src>)>,
}

#[derive(Clone)]
enum PkSource<'src> {
    /// A concrete value present in the payload.
    Payload(&'src JsonValue),

    /// An auto-incremented key generated by the batch at `batch`, captured into
    /// [TMP_TABLE] under the owning instance's `path`. `column` is the PK column
    /// name under which the value was stored in the tmp JSON object.
    Generated {
        batch: usize,
        path: Vec<PathSegment<'src>>,
        column: &'src str,
    },
}

impl<'src> PkSource<'src> {
    /// The [SaveArg] binding this source outside its own batch. A generated source reads
    /// the hydrated PK back from the body.
    fn save_arg(&self) -> SaveArg<'src> {
        match self {
            PkSource::Payload(v) => SaveArg::Payload(v),
            PkSource::Generated { path, column, .. } => {
                let mut path = path.clone();
                path.push(PathSegment::Field(column));
                SaveArg::Result(path)
            }
        }
    }
}

/// Some sub object of the original payload passed to [plan].
/// (a vertex in the payload graph, if you prefer)
/// ((or a node in the payload tree, if you preferer)))
type PayloadSubObject<'src> = Option<&'src serde_json::Map<String, JsonValue>>;

struct Instance<'src> {
    pks: Vec<(&'src str, PkSource<'src>)>,
    stage: usize,
    path: Vec<PathSegment<'src>>,
    shard: Vec<(&'src str, SaveArg<'src>)>,
}

impl<'src> Instance<'src> {
    fn pk_source(&self, column: &str) -> Option<PkSource<'src>> {
        self.pks
            .iter()
            .find(|(name, _)| *name == column)
            .map(|(_, src)| src.clone())
    }

    fn save_arg(&self, obj: PayloadSubObject<'src>, field: &'src str) -> SaveArg<'src> {
        let value = self.shard.iter().find(|(name, _)| *name == field);
        if let Some((_, arg)) = value {
            return arg.clone();
        }

        if let Some(value) = obj.and_then(|o| o.get(field)) {
            return SaveArg::Payload(value);
        }

        let mut path = self.path.clone();
        path.push(PathSegment::Field(field));
        SaveArg::Result(path)
    }
}

/// A pending SQL transaction against one database / stub in one stage.
struct Batch<'src> {
    stage: usize,
    database: Database<'src>,
    shard: Vec<(&'src str, SaveArg<'src>)>,
    writes: Vec<SqlStatement<'src>>,
    hydrates: Vec<SqlStatement<'src>>,
    uses_tmp: bool,
}

struct Planner<'src> {
    idl: &'src CloesceIdl<'src>,
    batches: Vec<Batch<'src>>,
    steps: Vec<(usize, SaveStep<'src>)>,
}

impl<'src> Planner<'src> {
    /// Post-order DFS over the payload graph.
    ///
    /// Returns the visited instance's [PkSource]
    fn visit(
        &mut self,
        model: &'src Model<'src>,
        payload: &'src JsonValue,
        tree: &IncludeTree<'src>,
        path: Vec<PathSegment<'src>>,
        parent: ParentCtx<'src>,
    ) -> Result<Instance<'src>> {
        let obj = payload.as_object();

        if !model.uses_sqlite() {
            // Directly synthesize route fields
            {
                let fields = model
                    .route_fields
                    .iter()
                    .filter_map(|f| {
                        let name = f.name.as_ref();
                        Some((name, SaveArg::Payload(obj.and_then(|o| o.get(name))?)))
                    })
                    .collect::<Vec<_>>();

                self.push_step(
                    0,
                    path.clone(),
                    SaveQuery::Synthesize {
                        fields,
                        create: true,
                    },
                );
            }

            let instance = Instance {
                pks: Vec::new(),
                stage: 0,
                path,
                shard: Vec::new(),
            };
            self.write_keys(model, obj, tree, &instance)?;
            self.visit_children(model, obj, tree, &instance, true)?;

            return Ok(instance);
        }

        // 1:1 navs first: this row may hold their FK, so the child is written before the row
        // resolves its local key.
        //
        // The child's ctx carries every nav key local already known without this row's write
        // (payload values, route params), so a child keyed by them resolves immediately.
        let mut nav_fks = parent.bindings;
        let one_navs = model
            .navigation_fields
            .iter()
            .filter(|n| matches!(n.cardinality, NavigationCardinality::One));
        for nav in one_navs {
            let Some((subtree, child_payload, target)) = self.nav_parts(nav, obj, tree) else {
                continue;
            };

            let ctx = self.child_ctx(nav, obj, &[]);
            let mut child_path = path.clone();
            child_path.push(PathSegment::Field(nav.field.name.as_ref()));
            let child = self.visit(target, child_payload, subtree, child_path, ctx)?;

            // Map this rows local key(s) to the child's PK source.
            for key in &nav.keys {
                if let Some(src) = child.pk_source(key.target) {
                    nav_fks.push((key.local, src));
                }
            }
        }

        self.visit_row(model, obj, tree, path, parent.shard, nav_fks)
    }

    /// Resolve every column of a sqlite-backed row, emit its write + readback,
    /// then recurse many navs.
    fn visit_row(
        &mut self,
        model: &'src Model<'src>,
        obj: PayloadSubObject<'src>,
        tree: &IncludeTree<'src>,
        path: Vec<PathSegment<'src>>,
        parent_shard: Vec<(&'src str, SaveArg<'src>)>,
        nav_fks: Vec<(&'src str, PkSource<'src>)>,
    ) -> Result<Instance<'src>> {
        let backing = model.backing.as_ref().expect("sqlite model has a backing");

        let pk_missing = model
            .primary_columns
            .iter()
            .all(|pk| !obj.is_some_and(|o| o.contains_key(pk.field.name.as_ref())));

        let mut cols = Vec::new();
        let mut has_missing_non_nullable = false;
        for (col, is_pk) in model.all_columns() {
            let name = col.field.name.as_ref();
            let provided = obj.and_then(|o| o.get(name));

            // A FK resolved through a 1:1 nav or a parent binding
            let fk_source = nav_fks
                .iter()
                .find(|(local, _)| *local == name)
                .map(|(_, src)| src.clone());

            let spec = match (provided, fk_source, is_pk) {
                (Some(value), _, _) => {
                    // The value exists in the payload and must be validated.
                    validate_cidl_type(&col.field, Some(value.clone()), self.idl, false)?;
                    ColSpec::Arg(SaveArg::Payload(value))
                }
                (None, Some(PkSource::Payload(v)), _) => {
                    // A parent/nav supplied the value (validation defers to the parent).
                    ColSpec::Arg(SaveArg::Payload(v))
                }
                (None, Some(src @ PkSource::Generated { .. }), _) => {
                    // A parent/nav supplied a generated value (we trust sql)
                    ColSpec::Generated(src)
                }
                (None, None, true) if matches!(col.field.cidl_type, CidlType::Int) => {
                    if model.has_composite_pk() {
                        fail!(OrmErrorKind::ModelKeyCannotAutoIncrement {
                            model: model.name.to_string(),
                            field: name.to_string(),
                        });
                    }

                    // The value is missing but we can auto-increment it.
                    ColSpec::AutoIncrement
                }
                (None, None, _) if pk_missing && col.field.cidl_type.is_nullable() => {
                    // Coerce to NULL for a missing nullable PK
                    ColSpec::Arg(SaveArg::Payload(&JsonValue::Null))
                }
                (None, None, false) if !pk_missing => {
                    // PK is present so this is an update OR insert (upsert).
                    if !col.field.cidl_type.is_nullable() {
                        // Narrow to an explicit update, cannot insert with a missing
                        // field.
                        has_missing_non_nullable = true;
                    }
                    continue;
                }
                _ => {
                    // The field is required to be present for a valid upsert,
                    // but is not. Abort.
                    fail!(OrmErrorKind::MissingField {
                        expected: fmt_cidl_type(&col.field.cidl_type),
                        missing: name.to_string(),
                    })
                }
            };

            cols.push(Column { name, is_pk, spec });
        }

        // A save carries every value in the payload, so a shard field resolves from a parent
        // binding, the payload, or a nav-key FK.
        let shard = backing
            .fields
            .iter()
            .map(|f| {
                let arg = parent_shard
                    .iter()
                    .find(|(n, _)| n == f)
                    .map(|(_, a)| a.clone())
                    .or_else(|| obj.and_then(|o| o.get(*f)).map(SaveArg::Payload))
                    .or_else(|| {
                        nav_fks
                            .iter()
                            .find(|(local, _)| local == f)
                            .map(|(_, src)| src.save_arg())
                    })
                    .ok_or_else(|| OrmErrorKind::MissingField {
                        expected: "all shard keys present".to_string(),
                        missing: f.to_string(),
                    })?;
                Ok((*f, arg))
            })
            .collect::<Result<Vec<_>>>()?;

        // Pick (or create) the batch this row belongs to, based on its generated deps.
        let deps = Column::generated_deps(&cols);
        let batch_idx = self.find_or_create_batch(backing.into(), shard.clone(), &deps);
        let stage = self.batches[batch_idx].stage;

        // Finalize generated FKs against the chosen batch.
        // - same-batch -> inline tmp subquery
        // - cross-batch -> read the hydrated PK back from the body.
        let finalized = cols
            .iter()
            .map(|c| c.finalize(batch_idx))
            .collect::<Vec<_>>();
        let row = RowSql {
            model,
            cols: &finalized,
        };

        // Emit the row write, then (if auto-increment) the tmp capture.
        let mut pks = Vec::new();
        self.batches[batch_idx]
            .writes
            .push(row.write(has_missing_non_nullable));

        if let Some(pk_name) = cols
            .iter()
            .find(|c| matches!(c.spec, ColSpec::AutoIncrement))
            .map(|c| c.name)
        {
            // Emit a tmp-capture for the auto-incremented PK, so this row's
            // children can reference it.
            self.batches[batch_idx].writes.push(SqlStatement::Write {
                sql: tmp_capture_sql(&dotted(&path), pk_name),
                arguments: vec![],
            });
            self.batches[batch_idx].uses_tmp = true;
            pks.push((
                pk_name,
                PkSource::Generated {
                    batch: batch_idx,
                    path: path.clone(),
                    column: pk_name,
                },
            ));
        }

        // Record provided PK source so descendants (and this row's parent, for a 1:1)
        // can resolve foreign keys pointing here.
        for col in &cols {
            if col.is_pk {
                match &col.spec {
                    ColSpec::Arg(SaveArg::Payload(v)) if !v.is_null() => {
                        pks.push((col.name, PkSource::Payload(v)))
                    }
                    ColSpec::Generated(src) => pks.push((col.name, src.clone())),
                    _ => {
                        // The PK is either auto-incremented (already recorded) or missing (insert query)
                    }
                }
            }
        }

        // Queue the read-back hydrate for this instance, keyed on its finalized PK columns.
        self.batches[batch_idx].hydrates.push(row.hydrate(&path));

        let instance = Instance {
            pks,
            stage,
            path,
            shard,
        };

        // Non-shard route fields are not columns, so the read-back hydrate omits them; merge
        // them onto the instance.
        let ns_route_fields = model
            .route_fields
            .iter()
            .map(|f| f.name.as_ref())
            .filter(|f| !backing.fields.contains(f))
            .filter_map(|f| {
                let arg = match nav_fks.iter().find(|(local, _)| *local == f) {
                    Some((_, src)) => src.save_arg(),
                    None => SaveArg::Payload(obj.and_then(|o| o.get(f))?),
                };
                Some((f, arg))
            })
            .collect::<Vec<_>>();
        if !ns_route_fields.is_empty() {
            self.push_step(
                stage,
                instance.path.clone(),
                SaveQuery::Synthesize {
                    fields: ns_route_fields,
                    create: false,
                },
            );
        }

        // KV / R2 writes
        self.write_keys(model, obj, tree, &instance)?;

        // Many navs; don't include 1:1 navs because Self::visit already handled them.
        self.visit_children(model, obj, tree, &instance, false)?;

        Ok(instance)
    }

    /// Recurse the navs that are written after `instance`
    /// - `Many` navs per array element
    /// - when `include_ones`, 1:1 navs too
    fn visit_children(
        &mut self,
        model: &'src Model<'src>,
        obj: PayloadSubObject<'src>,
        tree: &IncludeTree<'src>,
        instance: &Instance<'src>,
        include_ones: bool,
    ) -> Result<()> {
        for nav in &model.navigation_fields {
            let one = matches!(nav.cardinality, NavigationCardinality::One);
            if one && !include_ones {
                continue;
            }

            let Some((subtree, payload, target)) = self.nav_parts(nav, obj, tree) else {
                continue;
            };
            let ctx = self.child_ctx(nav, obj, &instance.pks);

            let mut nav_path = instance.path.clone();
            nav_path.push(PathSegment::Field(nav.field.name.as_ref()));

            if one {
                self.visit(target, payload, subtree, nav_path, ctx)?;
            } else {
                let JsonValue::Array(items) = payload else {
                    // A non-array payload for a Many nav is silently ignored.
                    continue;
                };
                for (i, item) in items.iter().enumerate() {
                    let mut child_path = nav_path.clone();
                    child_path.push(PathSegment::Index(i));
                    self.visit(target, item, subtree, child_path, ctx.clone())?;
                }
            }
        }
        Ok(())
    }

    /// KV / R2 writes for `model`, gated by the include `tree`.
    ///
    /// - A key covered entirely by route params or payload values can be written in
    ///   the same stage as the parent row (executed in parallel)
    /// - A key that references a generated PK is delayed to the next stage.
    /// - R2/KV fields are optional, so a missing field is silently ignored.
    fn write_keys(
        &mut self,
        model: &'src Model<'src>,
        obj: PayloadSubObject<'src>,
        tree: &IncludeTree<'src>,
        instance: &Instance<'src>,
    ) -> Result<()> {
        let mut push = |stage, field: &'src str, query| {
            let mut result = instance.path.clone();
            result.push(PathSegment::Field(field));
            self.steps.push((stage, SaveStep { query, result }));
        };
        let stage_for = |delayed: bool| {
            if delayed {
                instance.stage + 1
            } else {
                instance.stage
            }
        };

        for r2 in &model.r2_fields {
            let name = r2.field.name.as_ref();
            if !tree.0.contains_key(name) {
                continue;
            }
            let Some(value) = obj.and_then(|o| o.get(name)) else {
                // The R2 field is missing from the payload, safely ignore it.
                continue;
            };

            let (segments, delayed) = template_segments(&r2.key_format, obj, instance);
            push(
                stage_for(delayed),
                name,
                SaveQuery::KeyWrite {
                    database: Database {
                        name: r2.binding,
                        kind: DatabaseKind::R2,
                    },
                    key: segments,
                    value,
                    metadata: None,
                    shard: vec![],
                },
            );
        }

        for kv in &model.kv_fields {
            let name = kv.field.name.as_ref();
            if !tree.0.contains_key(name) {
                continue;
            }

            let (value, metadata) = if kv.field.cidl_type.is_kv_object() {
                // Worker KV fields are wrapped as `KvObject<T>` (`{ raw, metadata }`).
                let Some(JsonValue::Object(kv_object)) = obj.and_then(|o| o.get(name)) else {
                    continue;
                };
                let Some(raw) = kv_object.get("raw") else {
                    continue;
                };
                (raw, kv_object.get("metadata"))
            } else {
                let Some(value) = obj.and_then(|o| o.get(name)) else {
                    continue;
                };
                (value, None)
            };

            let is_do_kv = self
                .idl
                .wrangler_env
                .durable_bindings
                .iter()
                .any(|b| b.name == kv.binding);
            let (kind, shard_fields) = if is_do_kv {
                (DatabaseKind::DurableObject, kv.shard_fields.as_slice())
            } else {
                (DatabaseKind::Kv, [].as_slice())
            };

            let (segments, seg_delayed) = template_segments(&kv.key_format, obj, instance);
            let shard = shard_fields
                .iter()
                .map(|f| (*f, instance.save_arg(obj, f)))
                .collect::<Vec<_>>();
            let shard_delayed = shard.iter().any(|(_, a)| matches!(a, SaveArg::Result(_)));

            push(
                stage_for(seg_delayed || shard_delayed),
                name,
                SaveQuery::KeyWrite {
                    database: Database {
                        name: kv.binding,
                        kind,
                    },
                    key: segments,
                    value,
                    metadata,
                    shard,
                },
            );
        }
        Ok(())
    }

    /// Pick the batch a row lands in.
    ///
    /// `deps` are the batches that generated a PK this row depends on.
    /// - If a dep shares this rows binding + identical shard, the row may join it.
    /// - Otherwise, or when joining would strand another dep, the row lands in at
    ///   `stage = max(dep.stage + 1)`, resolving each cross-batch generated FK from
    ///   the dependency's read-back hydrate.
    fn find_or_create_batch(
        &mut self,
        database: Database<'src>,
        shard: Vec<(&'src str, SaveArg<'src>)>,
        deps: &[usize],
    ) -> usize {
        for &batch in deps {
            let b = &self.batches[batch];
            if b.database != database || b.shard != shard {
                // The batch is for a different binding or shard, so this row cannot join it.
                continue;
            }
            let clears_other_deps = deps.iter().all(|&other| {
                other == batch || self.batches[batch].stage > self.batches[other].stage
            });
            if clears_other_deps {
                // This batch is for the same binding/shard and is the last dep to be
                // resolved, so this row can join it.
                return batch;
            }
        }

        let stage = deps
            .iter()
            .map(|&batch| self.batches[batch].stage + 1)
            .max()
            .unwrap_or(0);

        // Join an existing batch at this exact stage / binding / shard, else create one.
        if let Some(idx) = self
            .batches
            .iter()
            .position(|b| b.stage == stage && b.database == database && b.shard == shard)
        {
            return idx;
        }

        self.batches.push(Batch {
            stage,
            database,
            shard,
            writes: Vec::new(),
            hydrates: Vec::new(),
            uses_tmp: false,
        });
        self.batches.len() - 1
    }

    fn push_step(&mut self, stage: usize, result: Vec<PathSegment<'src>>, query: SaveQuery<'src>) {
        self.steps.push((stage, SaveStep { query, result }));
    }

    /// (subtree, payload, target model) triple for a nav, if the include tree
    /// requests it and the payload carries it.
    fn nav_parts<'t>(
        &self,
        nav: &'src idl::NavigationField<'src>,
        obj: PayloadSubObject<'src>,
        tree: &'t IncludeTree<'src>,
    ) -> Option<(&'t IncludeTree<'src>, &'src JsonValue, &'src Model<'src>)> {
        let subtree = tree.0.get(nav.field.name.as_ref())?;
        let payload = obj.and_then(|o| o.get(nav.field.name.as_ref()))?;
        let target = self.idl.models.get(nav.model_reference)?;
        Some((subtree, payload, target))
    }

    /// Build the [ParentCtx] for a child nav
    /// - Resolve each nav key's `local` against what this instance knows
    ///   (a known primary key in `pks`, or a payload value)
    /// - If the child is DO-backed, any binding covering a shard field is lifted
    ///   into `shard` so the child routes to the right stub.
    fn child_ctx(
        &self,
        nav: &'src idl::NavigationField<'src>,
        obj: PayloadSubObject<'src>,
        pks: &[(&'src str, PkSource<'src>)],
    ) -> ParentCtx<'src> {
        let bindings: Vec<(&'src str, PkSource<'src>)> = nav
            .keys
            .iter()
            .filter_map(|k| {
                let source = if let Some((_, src)) = pks.iter().find(|(name, _)| *name == k.local) {
                    src.clone()
                } else if let Some(v) = obj.and_then(|o| o.get(k.local)) {
                    PkSource::Payload(v)
                } else {
                    return None;
                };
                Some((k.target, source))
            })
            .collect();

        let shard = self
            .idl
            .models
            .get(nav.model_reference)
            .and_then(|t| t.backing.as_ref())
            .filter(|b| matches!(b.kind, idl::BackingKind::DurableObject))
            .map(|b| {
                b.fields
                    .iter()
                    .filter_map(|f| {
                        bindings
                            .iter()
                            .find(|(target, _)| target == f)
                            .map(|(_, src)| (*f, src.save_arg()))
                    })
                    .collect::<Vec<_>>()
            })
            .unwrap_or_default();

        ParentCtx { bindings, shard }
    }

    /// Collapse the accumulated batches and steps into a [SavePlan].
    fn emit(self) -> SavePlan<'src> {
        let Planner { batches, steps, .. } = self;
        let mut plan = SavePlan::default();

        for batch in batches {
            let mut statements = batch.writes;
            statements.extend(batch.hydrates);
            if batch.uses_tmp {
                // Every single batch must clear the tmp table s.t. it is
                // empty for the next batch.
                statements.push(SqlStatement::Write {
                    sql: format!("DELETE FROM \"{TMP_TABLE}\""),
                    arguments: vec![],
                });
            }
            plan.stage_at(batch.stage).steps.push(SaveStep {
                query: SaveQuery::SqlBatch {
                    database: batch.database,
                    statements,
                    shard: batch.shard,
                },
                result: vec![],
            });
        }

        for (stage, step) in steps {
            plan.stage_at(stage).steps.push(step);
        }

        plan
    }
}

struct Column<'src> {
    name: &'src str,
    is_pk: bool,
    spec: ColSpec<'src>,
}

enum ColSpec<'src> {
    /// A bound `?N` argument.
    /// - The planner *does not* directly inline payload values to avoid
    ///   SQL injection, using bound arguments instead.
    Arg(SaveArg<'src>),

    /// A FK pointing at a generated PK (finalized once the batch is chosen).
    Generated(PkSource<'src>),

    /// A single-column integer PK generated on insert.
    AutoIncrement,
}

impl<'src> Column<'src> {
    /// Finalize this column against the chosen `batch`: a generated FK produced in the same
    /// batch inlines a [TMP_TABLE] subquery; one from another batch reads the hydrated PK
    /// back from the body.
    fn finalize(&self, batch: usize) -> FinalCol<'src> {
        let value = match &self.spec {
            ColSpec::Arg(arg) => FinalValue::Arg(arg.clone()),
            ColSpec::AutoIncrement => FinalValue::Skip,
            ColSpec::Generated(
                src @ PkSource::Generated {
                    batch: gen_batch,
                    path,
                    column,
                    ..
                },
            ) => {
                if *gen_batch == batch {
                    FinalValue::Inline(tmp_subquery(&dotted(path), column))
                } else {
                    FinalValue::Arg(src.save_arg())
                }
            }
            ColSpec::Generated(_) => {
                unreachable!("consequence of @ pattern matching lol")
            }
        };

        FinalCol {
            name: self.name,
            is_pk: self.is_pk,
            value,
        }
    }

    /// The batches that generated a PK any of `cols` depends on.
    fn generated_deps(cols: &[Column]) -> Vec<usize> {
        cols.iter()
            .filter_map(|col| match &col.spec {
                ColSpec::Generated(PkSource::Generated { batch, .. }) => Some(*batch),
                _ => None,
            })
            .fold(Vec::new(), |mut deps, batch| {
                if !deps.contains(&batch) {
                    deps.push(batch);
                }
                deps
            })
    }
}

struct FinalCol<'src> {
    name: &'src str,
    is_pk: bool,
    value: FinalValue<'src>,
}

enum FinalValue<'src> {
    /// A bound `?N` argument.
    Arg(SaveArg<'src>),

    /// An inline SQL expression (a tmp subquery), consuming no placeholder.
    Inline(String),

    /// Omitted from the INSERT column list (an auto-incremented PK).
    Skip,
}

struct RowSql<'a, 'src> {
    model: &'src Model<'src>,
    cols: &'a [FinalCol<'src>],
}

impl<'src> RowSql<'_, 'src> {
    /// The row `Write` statement. A present PK with a missing non-nullable column
    /// (`partial`) forces a keyed UPDATE.
    fn write(&self, partial: bool) -> SqlStatement<'src> {
        let any_pk = self.cols.iter().any(|c| c.is_pk);
        if any_pk && partial {
            self.update()
        } else {
            self.insert()
        }
    }

    fn insert(&self) -> SqlStatement<'src> {
        let mut names = Vec::new();
        let mut placeholders = Vec::new();
        let mut arguments = Vec::new();
        for col in self.cols {
            match &col.value {
                FinalValue::Skip => continue,
                FinalValue::Inline(expr) => {
                    names.push(quote(col.name));
                    placeholders.push(expr.clone());
                }
                FinalValue::Arg(arg) => {
                    names.push(quote(col.name));
                    placeholders.push(format!("?{}", arguments.len() + 1));
                    arguments.push(arg.clone());
                }
            }
        }

        let sql = if names.is_empty() {
            format!("INSERT INTO {} DEFAULT VALUES", quote(self.model.name))
        } else {
            let mut sql = format!(
                "INSERT INTO {} ({}) VALUES ({})",
                quote(self.model.name),
                names.join(", "),
                placeholders.join(", ")
            );

            // Upsert when every PK is resolved (present, not auto-increment) and non-PK columns
            // exist to update.
            let all_pks_resolved = !self
                .cols
                .iter()
                .any(|c| c.is_pk && matches!(c.value, FinalValue::Skip));

            let pk_names = self
                .cols
                .iter()
                .filter(|c| c.is_pk)
                .map(|c| quote(c.name))
                .collect::<Vec<_>>();

            let updates = self
                .cols
                .iter()
                .filter(|c| !c.is_pk && !matches!(c.value, FinalValue::Skip))
                .map(|c| format!("{0} = \"excluded\".{0}", quote(c.name)))
                .collect::<Vec<_>>();

            if all_pks_resolved && !pk_names.is_empty() && !updates.is_empty() {
                sql.push_str(&format!(
                    " ON CONFLICT ({}) DO UPDATE SET {}",
                    pk_names.join(", "),
                    updates.join(", ")
                ));
            }
            sql
        };

        SqlStatement::Write { sql, arguments }
    }

    fn update(&self) -> SqlStatement<'src> {
        let mut arguments = Vec::new();
        let mut clause = |pk: bool| {
            self.cols
                .iter()
                .filter(|c| c.is_pk == pk)
                .filter_map(|c| match &c.value {
                    FinalValue::Skip => None,
                    FinalValue::Inline(expr) => Some(format!("{} = {}", quote(c.name), expr)),
                    FinalValue::Arg(arg) => {
                        arguments.push(arg.clone());
                        Some(format!("{} = ?{}", quote(c.name), arguments.len()))
                    }
                })
                .collect::<Vec<_>>()
        };

        let sets = clause(false);
        let wheres = clause(true);
        let sql = format!(
            "UPDATE {} SET {} WHERE {}",
            quote(self.model.name),
            sets.join(", "),
            wheres.join(" AND ")
        );
        SqlStatement::Write { sql, arguments }
    }

    /// The read-back `SELECT` for this instance
    fn hydrate(&self, path: &[PathSegment<'src>]) -> SqlStatement<'src> {
        let columns = self
            .model
            .primary_columns
            .iter()
            .chain(&self.model.columns)
            .map(|c| quote(c.field.name.as_ref()))
            .collect::<Vec<_>>()
            .join(", ");

        let mut arguments = Vec::new();
        let predicates = self
            .cols
            .iter()
            .filter(|c| c.is_pk)
            .map(|c| {
                let rhs = match &c.value {
                    FinalValue::Arg(arg) => {
                        arguments.push(arg.clone());
                        format!("?{}", arguments.len())
                    }
                    FinalValue::Inline(expr) => expr.clone(),
                    FinalValue::Skip => tmp_subquery(&dotted(path), c.name),
                };
                format!("{} = {}", quote(c.name), rhs)
            })
            .collect::<Vec<_>>();

        let sql = format!(
            "SELECT {columns} FROM {} WHERE {}",
            quote(self.model.name),
            predicates.join(" AND ")
        );

        SqlStatement::Hydrate {
            sql,
            arguments,
            result: path.to_vec(),
        }
    }
}

fn template_segments<'src>(
    key: &'src str,
    obj: PayloadSubObject<'src>,
    instance: &Instance<'src>,
) -> (Vec<TemplateSegment<'src, SaveArg<'src>>>, bool) {
    let mut delayed = false;
    let segments = TemplateSegment::parse(key, |placeholder| {
        let arg = instance.save_arg(obj, placeholder);
        if matches!(arg, SaveArg::Result(_)) {
            delayed = true;
        }
        arg
    });
    (segments, delayed)
}

/// `INSERT OR REPLACE INTO "$cloesce_tmp" ...`
/// capturing a generated single PK by path.
fn tmp_capture_sql(tmp_path: &str, pk_column: &str) -> String {
    format!(
        "INSERT OR REPLACE INTO {} (\"path\", \"primary_key\") VALUES ('{}', json_object('{}', last_insert_rowid()))",
        quote(TMP_TABLE),
        tmp_path,
        pk_column,
    )
}

/// `(SELECT json_extract("primary_key", '$.<col>')
///     FROM "$cloesce_tmp" WHERE "path" = '<tmp_path>')`
fn tmp_subquery(tmp_path: &str, column: &str) -> String {
    format!(
        "(SELECT json_extract(\"primary_key\", '$.{}') FROM {} WHERE \"path\" = '{}')",
        column,
        quote(TMP_TABLE),
        tmp_path,
    )
}

/// Dotted body path (planner-internal [TMP_TABLE] key).
/// fields by name, array elements by index, root = "".
///
///  e.g. `["dogs", 1]` -> `"dogs.1"`.
fn dotted(path: &[PathSegment]) -> String {
    path.iter()
        .map(|seg| match seg {
            PathSegment::Field(f) => f.to_string(),
            PathSegment::Index(i) => i.to_string(),
        })
        .collect::<Vec<_>>()
        .join(".")
}

fn quote(ident: &str) -> String {
    format!("\"{ident}\"")
}
