//! A mock runtime executor for [SelectPlan].

use std::collections::{HashMap, HashSet};

use orm::query::select::plan::{
    JoinKeys, MapCardinality, Select, SelectArg, SelectPlan, SelectStep,
};
use orm::query::{Database, DatabaseKind, TemplateSegment};
use serde_json::{Map, Value as JsonValue, json};

use crate::common::setup::MockStorage;
use crate::common::{bind_value, row_to_json};

/// Executes the query plan exactly as written, with no access to the IDL, against
/// a set of in-memory SQLite pools. Intended to test the [SelectPlan] generated by the planner,
/// not necessarily the runtimes actual execution semantics.
///
/// - KV metadata is not supported
/// - Does not chunk large spreads
/// - Does not support partial failures. If any step fails, the whole plan fails. In the
///   real runtime a failed step still lets later steps in its stage attach their results
///   (with a blank body where needed)
/// - Any missing value is a hard failure
pub async fn execute<'p>(
    plan: &'p SelectPlan<'p>,
    params: Map<String, JsonValue>,
    storage: &'p MockStorage,
) -> JsonValue {
    let mut ctx = Context {
        params,
        storage,
        tables: HashMap::new(),
    };

    for stage in &plan.stages {
        // The real runtime executes a stages steps concurrently. This mock fetches them
        // sequentially in reverse, and only hydrates the stage's tables once every fetch
        // has run, so a step that secretly depends on another step in its own stage
        // fails loudly instead of silently working by luck of iteration order.
        let mut fetched = Vec::new();
        for step in stage.steps.iter().rev() {
            fetched.push((step, ctx.fetch(step).await));
        }

        // Hydrate parents before children.
        fetched.sort_by_key(|(step, _)| step.result.len());
        for (step, data) in fetched {
            let table = ctx.attach(step, data);
            ctx.tables.insert(step.result.as_slice(), table);
        }
    }

    ctx.assemble()
}

/// A step's location in the hydrated result ([SelectStep::result]).
type Path<'p> = &'p [&'p str];

struct Context<'p> {
    params: Map<String, JsonValue>,
    storage: &'p MockStorage,

    /// The hydrated tables of every completed stage, by result path.
    tables: HashMap<Path<'p>, Table>,
}

enum StepResult {
    /// SQL rows in query order, stamped at with their shard fields and
    /// param-sourced route fields.
    Rows(Vec<JsonValue>),

    /// Key store reads: resolved argument tuple (shard values, template values)
    /// -> fetched value.
    Keys(HashMap<Vec<JsonValue>, JsonValue>),

    /// Synthesize steps fetch nothing.
    Empty,
}

struct Attachment {
    /// Back-ref to the parent row of the table who composes this value.
    parent: usize,
    value: JsonValue,
}

struct Table {
    attachments: Vec<Attachment>,
    many: bool,
}

impl<'p> Context<'p> {
    /// Execute a single step's fetch. Sees only the tables of earlier stages.
    async fn fetch(&self, step: &'p SelectStep<'p>) -> StepResult {
        match &step.query {
            Select::Sql {
                database,
                sql,
                arguments,
                shard,
                route_fields,
                ..
            } => StepResult::Rows(
                self.fetch_sql(database, sql, arguments, shard, route_fields)
                    .await,
            ),
            Select::Key {
                database,
                segments,
                shard,
            } => StepResult::Keys(self.fetch_key(database, segments, shard)),
            Select::Synthesize { .. } => StepResult::Empty,
        }
    }

    async fn fetch_sql(
        &self,
        database: &Database<'_>,
        sql: &str,
        arguments: &[SelectArg<'p>],
        shard: &[(&'p str, SelectArg<'p>)],
        route_fields: &[(&'p str, SelectArg<'p>)],
    ) -> Vec<JsonValue> {
        let spreads = arguments.iter().map(|a| self.spread(a)).collect::<Vec<_>>();
        if spreads.iter().any(Vec::is_empty) {
            // A spread over zero parent values selects nothing.
            return Vec::new();
        }

        let mut slots = 1..;
        let expansions = spreads
            .iter()
            .map(|s| {
                let slots = slots.by_ref().take(s.len()).map(|i| format!("?{i}"));
                slots.collect::<Vec<_>>().join(", ")
            })
            .collect::<Vec<_>>();
        let sql = expand_placeholders(sql, &expansions);
        let binds = spreads.into_iter().flatten().collect::<Vec<_>>();

        // Param route fields are constant across shards; `Result` route fields
        // are deferred to hydration.
        let constants = route_fields
            .iter()
            .filter_map(|(field, arg)| match arg {
                SelectArg::Param(name) => Some((*field, self.param(name))),
                SelectArg::Result(_) => None,
            })
            .collect::<Vec<_>>();

        let mut out = Vec::new();
        let shard_args = shard.iter().map(|(_, arg)| arg).collect::<Vec<_>>();
        for tuple in self.tuples(&shard_args) {
            let pool = match database.kind {
                DatabaseKind::D1 => self.storage.d1.get(database.name),
                DatabaseKind::DurableObject => self
                    .storage
                    .durable
                    .get(database.name)
                    .and_then(|i| i.get(&tuple)),
                _ => unreachable!("sql select routed at a non-sql database"),
            }
            .expect("sql pool to exist in tests");
            let query = binds.iter().fold(sqlx::query(&sql), bind_value);
            let rows = query
                .fetch_all(pool)
                .await
                .expect("select to succeed in tests");

            // Stamp shard fields and constant route fields
            let stamps = shard
                .iter()
                .map(|(field, _)| *field)
                .zip(tuple)
                .chain(constants.iter().cloned())
                .collect::<Vec<_>>();

            out.extend(rows.iter().map(|r| {
                let mut row = row_to_json(r);
                let map = row.as_object_mut().expect("sql row to be an object");
                map.extend(stamps.iter().map(|(f, v)| (f.to_string(), v.clone())));
                row
            }));
        }

        out
    }

    /// Read from key-value stores (KV, DO KV, R2). One storage fetch per
    /// distinct argument tuple.
    fn fetch_key(
        &self,
        database: &Database<'_>,
        segments: &[TemplateSegment<'p, SelectArg<'p>>],
        shard: &[(&'p str, SelectArg<'p>)],
    ) -> HashMap<Vec<JsonValue>, JsonValue> {
        self.tuples(&key_args(shard, segments))
            .into_iter()
            .map(|tuple| {
                let key = render_key(segments, &tuple[shard.len()..]);
                let entries = match database.kind {
                    DatabaseKind::Kv => self.storage.kv.get(database.name),
                    DatabaseKind::R2 => self.storage.r2.get(database.name),
                    DatabaseKind::DurableObject => {
                        let shards = self.storage.durable_kv.get(database.name);
                        shards.and_then(|s| s.get(&tuple[..shard.len()]))
                    }
                    DatabaseKind::D1 => unreachable!("key select routed at a sql database"),
                };
                let raw = entries
                    .and_then(|m| m.get(&key))
                    .cloned()
                    .unwrap_or_else(|| panic!("key `{key}` to exist in tests"));

                // A Workers KV read wraps its value; R2 and DO-KV reads are the raw value.
                let value = match database.kind {
                    DatabaseKind::Kv => json!({ "value": raw }),
                    _ => raw,
                };
                (tuple, value)
            })
            .collect()
    }

    /// The distinct values a single argument spreads to at fetch time.
    fn spread(&self, arg: &SelectArg<'p>) -> Vec<JsonValue> {
        self.tuples(&[arg])
            .into_iter()
            .map(|mut t| t.pop().unwrap())
            .collect()
    }

    /// Resolve `args` to the distinct value tuples, one per hydrated object of the deepest
    /// table any arg references. An arg owned by a strict ancestor of that table is
    /// resolved by climbing the parent back-refs (never a cross product).
    fn tuples(&self, args: &[&SelectArg<'p>]) -> Vec<Vec<JsonValue>> {
        let tables = args
            .iter()
            .filter_map(|arg| match arg {
                SelectArg::Result(q) => Some(&q[..q.len() - 1]),
                SelectArg::Param(_) => None,
            })
            .collect::<HashSet<_>>();

        // Param-only tuples resolve without a source table.
        let Some(deepest) = tables.iter().copied().max_by_key(|t| t.len()) else {
            let tuple = args.iter().map(|arg| self.resolve_at(&[], 0, arg));
            return vec![tuple.collect()];
        };
        assert!(
            tables.iter().all(|t| deepest.starts_with(t)),
            "key/shard arguments spanning unrelated source tables are unsupported"
        );

        let table = self
            .tables
            .get(deepest)
            .expect("result arg to reference an earlier stage's table");
        distinct((0..table.attachments.len()).map(|idx| {
            args.iter()
                .map(|arg| self.resolve_at(deepest, idx, arg))
                .collect::<Vec<_>>()
        }))
    }

    fn param(&self, name: &str) -> JsonValue {
        let value = self.params.get(name).cloned();
        value.unwrap_or_else(|| panic!("runtime param `{name}` to exist in tests"))
    }

    /// Fold every hydrated table into its parent, deepest first, producing the final
    /// result.
    fn assemble(&mut self) -> JsonValue {
        let mut paths = self.tables.keys().copied().collect::<Vec<_>>();
        paths.sort_by_key(|path| std::cmp::Reverse(path.len()));
        for path in paths {
            let Some((field, parent_path)) = path.split_last() else {
                break;
            };
            let child = self.tables.remove(path).unwrap();
            let parents = &mut self
                .tables
                .get_mut(parent_path)
                .expect("parent table")
                .attachments;
            if child.many {
                for parent in parents.iter_mut() {
                    parent.value[*field] = json!([]);
                }
            }
            for attachment in child.attachments {
                match &mut parents[attachment.parent].value[*field] {
                    JsonValue::Array(values) if child.many => values.push(attachment.value),
                    slot => *slot = attachment.value,
                }
            }
        }

        let root = self
            .tables
            .remove(&[] as &[&str])
            .expect("root table to exist");
        let mut values = root.attachments.into_iter().map(|a| a.value);
        match root.many {
            true => JsonValue::Array(values.collect()),
            false => values.next().expect("root result to exist in tests"),
        }
    }

    /// Compute one table's attachments: which parent each value belongs to, with any
    /// per-parent fields (route fields, synthesized fields, key lookups) resolved by
    /// climbing the ancestor back-refs.
    fn attach(&self, step: &'p SelectStep<'p>, fetched: StepResult) -> Table {
        let path = step.result.as_slice();
        match (&step.query, fetched) {
            (
                Select::Sql {
                    mapping,
                    route_fields,
                    ..
                },
                StepResult::Rows(rows),
            ) => {
                let many = mapping.cardinality == MapCardinality::Many;
                let Some((_, parent_path)) = path.split_last() else {
                    let attachments = rows
                        .into_iter()
                        .map(|value| Attachment { parent: 0, value });
                    return Table {
                        attachments: attachments.collect(),
                        many,
                    };
                };

                // Bucket parents by join key, then hand each row to its matching parents;
                // a One mapping serves each parent at most once.
                let mut index = HashMap::<Vec<JsonValue>, Vec<usize>>::new();
                for (i, parent) in self.tables[parent_path].attachments.iter().enumerate() {
                    let key = join_key(&parent.value, &mapping.join, |j| j.parent_key);
                    index.entry(key).or_default().push(i);
                }

                let mut served = HashSet::new();
                let mut attachments = Vec::new();
                for row in &rows {
                    let key = join_key(row, &mapping.join, |j| j.child_key);
                    for &parent in index.get(&key).map(Vec::as_slice).unwrap_or_default() {
                        if !many && !served.insert(parent) {
                            continue;
                        }
                        let mut value = row.clone();
                        for (field, arg) in route_fields {
                            if matches!(arg, SelectArg::Result(_)) {
                                value[*field] = self.resolve_at(parent_path, parent, arg);
                            }
                        }
                        attachments.push(Attachment { parent, value });
                    }
                }
                Table { attachments, many }
            }
            (
                Select::Key {
                    segments, shard, ..
                },
                StepResult::Keys(fetched),
            ) => {
                let args = key_args(shard, segments);
                self.singletons(path, |parent_path, parent| {
                    let tuple = args
                        .iter()
                        .map(|arg| self.resolve_at(parent_path, parent, arg))
                        .collect::<Vec<_>>();
                    fetched[&tuple].clone()
                })
            }
            (
                Select::Synthesize {
                    fields,
                    cardinality,
                },
                StepResult::Empty,
            ) => {
                // A Many synthesize is a singleton array, folded as a single value.
                // At the root every field is param-sourced by construction.
                self.singletons(path, |parent_path, parent| {
                    let object = fields
                        .iter()
                        .map(|(field, arg)| {
                            (field.to_string(), self.resolve_at(parent_path, parent, arg))
                        })
                        .collect();
                    match cardinality {
                        MapCardinality::One => JsonValue::Object(object),
                        MapCardinality::Many => json!([JsonValue::Object(object)]),
                    }
                })
            }
            _ => unreachable!("fetched data to match its step kind"),
        }
    }

    /// A `Table` with exactly one attachment per parent object (a single root-level
    /// attachment when `path` is the root), each built from its parent's location.
    fn singletons(&self, path: Path<'p>, build: impl Fn(Path<'p>, usize) -> JsonValue) -> Table {
        let attachments = match path.split_last() {
            None => vec![Attachment {
                parent: 0,
                value: build(path, 0),
            }],
            Some((_, parent_path)) => (0..self.tables[parent_path].attachments.len())
                .map(|parent| Attachment {
                    parent,
                    value: build(parent_path, parent),
                })
                .collect(),
        };
        Table {
            attachments,
            many: false,
        }
    }

    /// Resolve an argument for the object at (`path`, `idx`)
    fn resolve_at(&self, path: &[&'p str], idx: usize, arg: &SelectArg<'p>) -> JsonValue {
        match arg {
            SelectArg::Param(name) => self.param(name),
            SelectArg::Result(q) => {
                let (field, owner) = q.split_last().expect("non-empty result arg");
                let (mut path, mut idx) = (path, idx);
                while path.len() > owner.len() {
                    idx = self.tables[path].attachments[idx].parent;
                    path = &path[..path.len() - 1];
                }
                field_of(&self.tables[path].attachments[idx].value, field)
            }
        }
    }
}

/// A row's join key along one side of a mapping.
fn join_key<'j>(
    row: &JsonValue,
    join: &[JoinKeys<'j>],
    side: fn(&JoinKeys<'j>) -> &'j str,
) -> Vec<JsonValue> {
    join.iter().map(|j| field_of(row, side(j))).collect()
}

/// A key step's arguments in tuple order: shard values, then template values.
fn key_args<'s, 'p>(
    shard: &'s [(&'p str, SelectArg<'p>)],
    segments: &'s [TemplateSegment<'p, SelectArg<'p>>],
) -> Vec<&'s SelectArg<'p>> {
    let template = segments.iter().filter_map(|segment| match segment {
        TemplateSegment::Value(arg) => Some(arg),
        TemplateSegment::Literal(_) => None,
    });
    shard.iter().map(|(_, arg)| arg).chain(template).collect()
}

fn render_key(segments: &[TemplateSegment<'_, SelectArg<'_>>], values: &[JsonValue]) -> String {
    let mut values = values.iter();
    segments
        .iter()
        .map(|segment| match segment {
            TemplateSegment::Literal(text) => (*text).to_string(),
            TemplateSegment::Value(_) => match values.next().expect("template value") {
                JsonValue::String(s) => s.clone(),
                other => other.to_string(),
            },
        })
        .collect()
}

/// Rewrite `?N` placeholders, replacing the N-th argument's placeholder with its
/// (possibly spread) expansion.
fn expand_placeholders(sql: &str, expansions: &[String]) -> String {
    let mut parts = sql.split('?');
    let mut out = parts.next().unwrap_or_default().to_string();
    for part in parts {
        let digits = part.chars().take_while(char::is_ascii_digit).count();
        let n: usize = part[..digits].parse().expect("numbered placeholder");
        out.push_str(&expansions[n - 1]);
        out.push_str(&part[digits..]);
    }
    out
}

fn field_of(row: &JsonValue, field: &str) -> JsonValue {
    let value = row.get(field).cloned();
    value.unwrap_or_else(|| panic!("field `{field}` to exist on a fetched row"))
}

/// Order-preserving distinct.
fn distinct<T: std::hash::Hash + Eq + Clone>(values: impl IntoIterator<Item = T>) -> Vec<T> {
    let mut seen = HashSet::new();
    values
        .into_iter()
        .filter(|v| seen.insert(v.clone()))
        .collect()
}
