// GENERATED BY CLOESCE. DO NOT MODIFY.
/**
 * Typed client for the `A` model.
 *
 * Each method performs an HTTP request and returns an {@link HttpResult}.
 * Pass an optional `fetchImpl` as the last argument to customize requests (e.g. auth headers).
 *
 * @example
 * ```ts
 * const authed: typeof fetch = (url, init) =>
 *   fetch(url, { ...init, headers: { ...init?.headers, Authorization: token } });
 *
 * const res = await A.someApi(arg, authed);
 * if (!res.ok) throw new Error(res.message);
 * console.log(res.data);
 * ```
 *
 * @example Streaming methods resolve to `HttpResult<Response>` — read the body off `res.data`
 * ```ts
 * const res = await A.download(id);
 * if (!res.ok) throw new Error(res.message);
 * const blob = await res.data!.blob();        // or .body / .arrayBuffer()
 * ```
 */
export class A {
  id: number;
  bId: number | null;
  b: B | undefined;
  /** Call `A.create` over HTTP. Static method. */
  static async create(
    a: A,
    fetchImpl: typeof fetch = fetch
  ): Promise<HttpResult<A>> {
    const __$baseUrl = new URL(
      `http://localhost:5716/api/A/create`
    );
    const __$payload: any = {};
    __$payload["a"] = a;

    const __$res = await fetchImpl(__$baseUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: requestBody(MediaType.Json, __$payload),
    });

    return await HttpResult.fromResponse(
      __$res,
      MediaType.Json,
      A,
      false
    );
  }
  /** Call `A.withoutB` over HTTP. Instance method. */
  async withoutB(
    fetchImpl: typeof fetch = fetch
  ): Promise<HttpResult<A>> {
    const __$id = [
      encodeURIComponent(String(this.id)),
    ].join("/");
    const __$baseUrl = new URL(
      `http://localhost:5716/api/A/${__$id}/withoutB`
    );

    const __$res = await fetchImpl(__$baseUrl, {
      method: "GET",
    });

    return await HttpResult.fromResponse(
      __$res,
      MediaType.Json,
      A,
      false
    );
  }
  /** Call `A.$save` over HTTP. Static method. */
  static async $save(
    model: DeepPartial<A>,
    fetchImpl: typeof fetch = fetch
  ): Promise<HttpResult<A>> {
    const __$baseUrl = new URL(
      `http://localhost:5716/api/A/$save`
    );
    const __$payload: any = {};
    __$payload["model"] = model;

    const __$res = await fetchImpl(__$baseUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: requestBody(MediaType.Json, __$payload),
    });

    return await HttpResult.fromResponse(
      __$res,
      MediaType.Json,
      A,
      false
    );
  }
  /** Call `A.$save_WithB` over HTTP. Static method. */
  static async $save_WithB(
    model: DeepPartial<A>,
    fetchImpl: typeof fetch = fetch
  ): Promise<HttpResult<A>> {
    const __$baseUrl = new URL(
      `http://localhost:5716/api/A/$save_WithB`
    );
    const __$payload: any = {};
    __$payload["model"] = model;

    const __$res = await fetchImpl(__$baseUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: requestBody(MediaType.Json, __$payload),
    });

    return await HttpResult.fromResponse(
      __$res,
      MediaType.Json,
      A,
      false
    );
  }
  /** Call `A.$save_WithoutB` over HTTP. Static method. */
  static async $save_WithoutB(
    model: DeepPartial<A>,
    fetchImpl: typeof fetch = fetch
  ): Promise<HttpResult<A>> {
    const __$baseUrl = new URL(
      `http://localhost:5716/api/A/$save_WithoutB`
    );
    const __$payload: any = {};
    __$payload["model"] = model;

    const __$res = await fetchImpl(__$baseUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: requestBody(MediaType.Json, __$payload),
    });

    return await HttpResult.fromResponse(
      __$res,
      MediaType.Json,
      A,
      false
    );
  }
  /** Call `A.$get` over HTTP. Static method. */
  static async $get(
    id: number,
    fetchImpl: typeof fetch = fetch
  ): Promise<HttpResult<A>> {
    const __$baseUrl = new URL(
      `http://localhost:5716/api/A/$get`
    );
    __$baseUrl.searchParams.append("id", String(id));

    const __$res = await fetchImpl(__$baseUrl, {
      method: "GET",
    });

    return await HttpResult.fromResponse(
      __$res,
      MediaType.Json,
      A,
      false
    );
  }
  /** Call `A.$get_WithB` over HTTP. Static method. */
  static async $get_WithB(
    id: number,
    fetchImpl: typeof fetch = fetch
  ): Promise<HttpResult<A>> {
    const __$baseUrl = new URL(
      `http://localhost:5716/api/A/$get_WithB`
    );
    __$baseUrl.searchParams.append("id", String(id));

    const __$res = await fetchImpl(__$baseUrl, {
      method: "GET",
    });

    return await HttpResult.fromResponse(
      __$res,
      MediaType.Json,
      A,
      false
    );
  }
  /** Call `A.$get_WithoutB` over HTTP. Static method. */
  static async $get_WithoutB(
    id: number,
    fetchImpl: typeof fetch = fetch
  ): Promise<HttpResult<A>> {
    const __$baseUrl = new URL(
      `http://localhost:5716/api/A/$get_WithoutB`
    );
    __$baseUrl.searchParams.append("id", String(id));

    const __$res = await fetchImpl(__$baseUrl, {
      method: "GET",
    });

    return await HttpResult.fromResponse(
      __$res,
      MediaType.Json,
      A,
      false
    );
  }

  /** @internal Reconstruct from a plain JSON object. */
  static fromJson(data: any): A {
    const __$res = Object.assign(new A(), data);
    __$res["b"] &&= B.fromJson(__$res.b);
    return __$res;
  }
}
/**
 * Typed client for the `B` model.
 *
 * Each method performs an HTTP request and returns an {@link HttpResult}.
 * Pass an optional `fetchImpl` as the last argument to customize requests (e.g. auth headers).
 *
 * @example
 * ```ts
 * const authed: typeof fetch = (url, init) =>
 *   fetch(url, { ...init, headers: { ...init?.headers, Authorization: token } });
 *
 * const res = await B.someApi(arg, authed);
 * if (!res.ok) throw new Error(res.message);
 * console.log(res.data);
 * ```
 *
 * @example Streaming methods resolve to `HttpResult<Response>` — read the body off `res.data`
 * ```ts
 * const res = await B.download(id);
 * if (!res.ok) throw new Error(res.message);
 * const blob = await res.data!.blob();        // or .body / .arrayBuffer()
 * ```
 */
export class B {
  id: number;
  a: A[];
  /** Call `B.testMethod` over HTTP. Instance method. */
  async testMethod(
    fetchImpl: typeof fetch = fetch
  ): Promise<HttpResult<void>> {
    const __$id = [
      encodeURIComponent(String(this.id)),
    ].join("/");
    const __$baseUrl = new URL(
      `http://localhost:5716/api/B/${__$id}/testMethod`
    );
    const __$payload: any = {};

    const __$res = await fetchImpl(__$baseUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: requestBody(MediaType.Json, __$payload),
    });

    return await HttpResult.fromResponse(
      __$res,
      MediaType.Json,
      undefined,
      false
    );
  }
  /** Call `B.$save` over HTTP. Static method. */
  static async $save(
    model: DeepPartial<B>,
    fetchImpl: typeof fetch = fetch
  ): Promise<HttpResult<B>> {
    const __$baseUrl = new URL(
      `http://localhost:5716/api/B/$save`
    );
    const __$payload: any = {};
    __$payload["model"] = model;

    const __$res = await fetchImpl(__$baseUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: requestBody(MediaType.Json, __$payload),
    });

    return await HttpResult.fromResponse(
      __$res,
      MediaType.Json,
      B,
      false
    );
  }
  /** Call `B.$get` over HTTP. Static method. */
  static async $get(
    id: number,
    fetchImpl: typeof fetch = fetch
  ): Promise<HttpResult<B>> {
    const __$baseUrl = new URL(
      `http://localhost:5716/api/B/$get`
    );
    __$baseUrl.searchParams.append("id", String(id));

    const __$res = await fetchImpl(__$baseUrl, {
      method: "GET",
    });

    return await HttpResult.fromResponse(
      __$res,
      MediaType.Json,
      B,
      false
    );
  }

  /** @internal Reconstruct from a plain JSON object. */
  static fromJson(data: any): B {
    const __$res = Object.assign(new B(), data);
    for (let i = 0; i < __$res.a?.length; i++) {
      __$res.a[i] = A.fromJson(__$res.a[i]);
    }
    return __$res;
  }
}
/**
 * Typed client for the `Course` model.
 *
 * Each method performs an HTTP request and returns an {@link HttpResult}.
 * Pass an optional `fetchImpl` as the last argument to customize requests (e.g. auth headers).
 *
 * @example
 * ```ts
 * const authed: typeof fetch = (url, init) =>
 *   fetch(url, { ...init, headers: { ...init?.headers, Authorization: token } });
 *
 * const res = await Course.someApi(arg, authed);
 * if (!res.ok) throw new Error(res.message);
 * console.log(res.data);
 * ```
 *
 * @example Streaming methods resolve to `HttpResult<Response>` — read the body off `res.data`
 * ```ts
 * const res = await Course.download(id);
 * if (!res.ok) throw new Error(res.message);
 * const blob = await res.data!.blob();        // or .body / .arrayBuffer()
 * ```
 */
export class Course {
  id: number;
  students: CourseStudent[];
  /** Call `Course.$save` over HTTP. Static method. */
  static async $save(
    model: DeepPartial<Course>,
    fetchImpl: typeof fetch = fetch
  ): Promise<HttpResult<Course>> {
    const __$baseUrl = new URL(
      `http://localhost:5716/api/Course/$save`
    );
    const __$payload: any = {};
    __$payload["model"] = model;

    const __$res = await fetchImpl(__$baseUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: requestBody(MediaType.Json, __$payload),
    });

    return await HttpResult.fromResponse(
      __$res,
      MediaType.Json,
      Course,
      false
    );
  }

  /** @internal Reconstruct from a plain JSON object. */
  static fromJson(data: any): Course {
    const __$res = Object.assign(new Course(), data);
    for (let i = 0; i < __$res.students?.length; i++) {
      __$res.students[i] = CourseStudent.fromJson(__$res.students[i]);
    }
    return __$res;
  }
}
/**
 * Typed client for the `Person` model.
 *
 * Each method performs an HTTP request and returns an {@link HttpResult}.
 * Pass an optional `fetchImpl` as the last argument to customize requests (e.g. auth headers).
 *
 * @example
 * ```ts
 * const authed: typeof fetch = (url, init) =>
 *   fetch(url, { ...init, headers: { ...init?.headers, Authorization: token } });
 *
 * const res = await Person.someApi(arg, authed);
 * if (!res.ok) throw new Error(res.message);
 * console.log(res.data);
 * ```
 *
 * @example Streaming methods resolve to `HttpResult<Response>` — read the body off `res.data`
 * ```ts
 * const res = await Person.download(id);
 * if (!res.ok) throw new Error(res.message);
 * const blob = await res.data!.blob();        // or .body / .arrayBuffer()
 * ```
 */
export class Person {
  id: number;
  dogs: Dog[];
  /** Call `Person.create` over HTTP. Static method. */
  static async create(
    person: DeepPartial<Person>,
    fetchImpl: typeof fetch = fetch
  ): Promise<HttpResult<Person>> {
    const __$baseUrl = new URL(
      `http://localhost:5716/api/Person/create`
    );
    const __$payload: any = {};
    __$payload["person"] = person;

    const __$res = await fetchImpl(__$baseUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: requestBody(MediaType.Json, __$payload),
    });

    return await HttpResult.fromResponse(
      __$res,
      MediaType.Json,
      Person,
      false
    );
  }
  /** Call `Person.withoutDogs` over HTTP. Instance method. */
  async withoutDogs(
    fetchImpl: typeof fetch = fetch
  ): Promise<HttpResult<Person>> {
    const __$id = [
      encodeURIComponent(String(this.id)),
    ].join("/");
    const __$baseUrl = new URL(
      `http://localhost:5716/api/Person/${__$id}/withoutDogs`
    );

    const __$res = await fetchImpl(__$baseUrl, {
      method: "GET",
    });

    return await HttpResult.fromResponse(
      __$res,
      MediaType.Json,
      Person,
      false
    );
  }
  /** Call `Person.$save` over HTTP. Static method. */
  static async $save(
    model: DeepPartial<Person>,
    fetchImpl: typeof fetch = fetch
  ): Promise<HttpResult<Person>> {
    const __$baseUrl = new URL(
      `http://localhost:5716/api/Person/$save`
    );
    const __$payload: any = {};
    __$payload["model"] = model;

    const __$res = await fetchImpl(__$baseUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: requestBody(MediaType.Json, __$payload),
    });

    return await HttpResult.fromResponse(
      __$res,
      MediaType.Json,
      Person,
      false
    );
  }
  /** Call `Person.$save_WithDogs` over HTTP. Static method. */
  static async $save_WithDogs(
    model: DeepPartial<Person>,
    fetchImpl: typeof fetch = fetch
  ): Promise<HttpResult<Person>> {
    const __$baseUrl = new URL(
      `http://localhost:5716/api/Person/$save_WithDogs`
    );
    const __$payload: any = {};
    __$payload["model"] = model;

    const __$res = await fetchImpl(__$baseUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: requestBody(MediaType.Json, __$payload),
    });

    return await HttpResult.fromResponse(
      __$res,
      MediaType.Json,
      Person,
      false
    );
  }
  /** Call `Person.$save_WithoutDogs` over HTTP. Static method. */
  static async $save_WithoutDogs(
    model: DeepPartial<Person>,
    fetchImpl: typeof fetch = fetch
  ): Promise<HttpResult<Person>> {
    const __$baseUrl = new URL(
      `http://localhost:5716/api/Person/$save_WithoutDogs`
    );
    const __$payload: any = {};
    __$payload["model"] = model;

    const __$res = await fetchImpl(__$baseUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: requestBody(MediaType.Json, __$payload),
    });

    return await HttpResult.fromResponse(
      __$res,
      MediaType.Json,
      Person,
      false
    );
  }
  /** Call `Person.$get` over HTTP. Static method. */
  static async $get(
    id: number,
    fetchImpl: typeof fetch = fetch
  ): Promise<HttpResult<Person>> {
    const __$baseUrl = new URL(
      `http://localhost:5716/api/Person/$get`
    );
    __$baseUrl.searchParams.append("id", String(id));

    const __$res = await fetchImpl(__$baseUrl, {
      method: "GET",
    });

    return await HttpResult.fromResponse(
      __$res,
      MediaType.Json,
      Person,
      false
    );
  }
  /** Call `Person.$get_WithDogs` over HTTP. Static method. */
  static async $get_WithDogs(
    id: number,
    fetchImpl: typeof fetch = fetch
  ): Promise<HttpResult<Person>> {
    const __$baseUrl = new URL(
      `http://localhost:5716/api/Person/$get_WithDogs`
    );
    __$baseUrl.searchParams.append("id", String(id));

    const __$res = await fetchImpl(__$baseUrl, {
      method: "GET",
    });

    return await HttpResult.fromResponse(
      __$res,
      MediaType.Json,
      Person,
      false
    );
  }
  /** Call `Person.$get_WithoutDogs` over HTTP. Static method. */
  static async $get_WithoutDogs(
    id: number,
    fetchImpl: typeof fetch = fetch
  ): Promise<HttpResult<Person>> {
    const __$baseUrl = new URL(
      `http://localhost:5716/api/Person/$get_WithoutDogs`
    );
    __$baseUrl.searchParams.append("id", String(id));

    const __$res = await fetchImpl(__$baseUrl, {
      method: "GET",
    });

    return await HttpResult.fromResponse(
      __$res,
      MediaType.Json,
      Person,
      false
    );
  }

  /** @internal Reconstruct from a plain JSON object. */
  static fromJson(data: any): Person {
    const __$res = Object.assign(new Person(), data);
    for (let i = 0; i < __$res.dogs?.length; i++) {
      __$res.dogs[i] = Dog.fromJson(__$res.dogs[i]);
    }
    return __$res;
  }
}
/**
 * Typed client for the `Student` model.
 *
 * Each method performs an HTTP request and returns an {@link HttpResult}.
 * Pass an optional `fetchImpl` as the last argument to customize requests (e.g. auth headers).
 *
 * @example
 * ```ts
 * const authed: typeof fetch = (url, init) =>
 *   fetch(url, { ...init, headers: { ...init?.headers, Authorization: token } });
 *
 * const res = await Student.someApi(arg, authed);
 * if (!res.ok) throw new Error(res.message);
 * console.log(res.data);
 * ```
 *
 * @example Streaming methods resolve to `HttpResult<Response>` — read the body off `res.data`
 * ```ts
 * const res = await Student.download(id);
 * if (!res.ok) throw new Error(res.message);
 * const blob = await res.data!.blob();        // or .body / .arrayBuffer()
 * ```
 */
export class Student {
  id: number;
  courses: CourseStudent[];
  /** Call `Student.create` over HTTP. Static method. */
  static async create(
    student: DeepPartial<Student>,
    fetchImpl: typeof fetch = fetch
  ): Promise<HttpResult<Student>> {
    const __$baseUrl = new URL(
      `http://localhost:5716/api/Student/create`
    );
    const __$payload: any = {};
    __$payload["student"] = student;

    const __$res = await fetchImpl(__$baseUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: requestBody(MediaType.Json, __$payload),
    });

    return await HttpResult.fromResponse(
      __$res,
      MediaType.Json,
      Student,
      false
    );
  }
  /** Call `Student.none` over HTTP. Instance method. */
  async none(
    fetchImpl: typeof fetch = fetch
  ): Promise<HttpResult<Student>> {
    const __$id = [
      encodeURIComponent(String(this.id)),
    ].join("/");
    const __$baseUrl = new URL(
      `http://localhost:5716/api/Student/${__$id}/none`
    );

    const __$res = await fetchImpl(__$baseUrl, {
      method: "GET",
    });

    return await HttpResult.fromResponse(
      __$res,
      MediaType.Json,
      Student,
      false
    );
  }
  /** Call `Student.$save` over HTTP. Static method. */
  static async $save(
    model: DeepPartial<Student>,
    fetchImpl: typeof fetch = fetch
  ): Promise<HttpResult<Student>> {
    const __$baseUrl = new URL(
      `http://localhost:5716/api/Student/$save`
    );
    const __$payload: any = {};
    __$payload["model"] = model;

    const __$res = await fetchImpl(__$baseUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: requestBody(MediaType.Json, __$payload),
    });

    return await HttpResult.fromResponse(
      __$res,
      MediaType.Json,
      Student,
      false
    );
  }
  /** Call `Student.$save_None` over HTTP. Static method. */
  static async $save_None(
    model: DeepPartial<Student>,
    fetchImpl: typeof fetch = fetch
  ): Promise<HttpResult<Student>> {
    const __$baseUrl = new URL(
      `http://localhost:5716/api/Student/$save_None`
    );
    const __$payload: any = {};
    __$payload["model"] = model;

    const __$res = await fetchImpl(__$baseUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: requestBody(MediaType.Json, __$payload),
    });

    return await HttpResult.fromResponse(
      __$res,
      MediaType.Json,
      Student,
      false
    );
  }
  /** Call `Student.$save_WithCoursesStudentsCourses` over HTTP. Static method. */
  static async $save_WithCoursesStudentsCourses(
    model: DeepPartial<Student>,
    fetchImpl: typeof fetch = fetch
  ): Promise<HttpResult<Student>> {
    const __$baseUrl = new URL(
      `http://localhost:5716/api/Student/$save_WithCoursesStudentsCourses`
    );
    const __$payload: any = {};
    __$payload["model"] = model;

    const __$res = await fetchImpl(__$baseUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: requestBody(MediaType.Json, __$payload),
    });

    return await HttpResult.fromResponse(
      __$res,
      MediaType.Json,
      Student,
      false
    );
  }
  /** Call `Student.$get` over HTTP. Static method. */
  static async $get(
    id: number,
    fetchImpl: typeof fetch = fetch
  ): Promise<HttpResult<Student>> {
    const __$baseUrl = new URL(
      `http://localhost:5716/api/Student/$get`
    );
    __$baseUrl.searchParams.append("id", String(id));

    const __$res = await fetchImpl(__$baseUrl, {
      method: "GET",
    });

    return await HttpResult.fromResponse(
      __$res,
      MediaType.Json,
      Student,
      false
    );
  }
  /** Call `Student.$get_None` over HTTP. Static method. */
  static async $get_None(
    id: number,
    fetchImpl: typeof fetch = fetch
  ): Promise<HttpResult<Student>> {
    const __$baseUrl = new URL(
      `http://localhost:5716/api/Student/$get_None`
    );
    __$baseUrl.searchParams.append("id", String(id));

    const __$res = await fetchImpl(__$baseUrl, {
      method: "GET",
    });

    return await HttpResult.fromResponse(
      __$res,
      MediaType.Json,
      Student,
      false
    );
  }
  /** Call `Student.$get_WithCoursesStudentsCourses` over HTTP. Static method. */
  static async $get_WithCoursesStudentsCourses(
    id: number,
    fetchImpl: typeof fetch = fetch
  ): Promise<HttpResult<Student>> {
    const __$baseUrl = new URL(
      `http://localhost:5716/api/Student/$get_WithCoursesStudentsCourses`
    );
    __$baseUrl.searchParams.append("id", String(id));

    const __$res = await fetchImpl(__$baseUrl, {
      method: "GET",
    });

    return await HttpResult.fromResponse(
      __$res,
      MediaType.Json,
      Student,
      false
    );
  }

  /** @internal Reconstruct from a plain JSON object. */
  static fromJson(data: any): Student {
    const __$res = Object.assign(new Student(), data);
    for (let i = 0; i < __$res.courses?.length; i++) {
      __$res.courses[i] = CourseStudent.fromJson(__$res.courses[i]);
    }
    return __$res;
  }
}
/**
 * Typed client for the `Dog` model.
 *
 * Each method performs an HTTP request and returns an {@link HttpResult}.
 * Pass an optional `fetchImpl` as the last argument to customize requests (e.g. auth headers).
 *
 * @example
 * ```ts
 * const authed: typeof fetch = (url, init) =>
 *   fetch(url, { ...init, headers: { ...init?.headers, Authorization: token } });
 *
 * const res = await Dog.someApi(arg, authed);
 * if (!res.ok) throw new Error(res.message);
 * console.log(res.data);
 * ```
 *
 * @example Streaming methods resolve to `HttpResult<Response>` — read the body off `res.data`
 * ```ts
 * const res = await Dog.download(id);
 * if (!res.ok) throw new Error(res.message);
 * const blob = await res.data!.blob();        // or .body / .arrayBuffer()
 * ```
 */
export class Dog {
  id: number;
  personId: number;
  person: Person | undefined;
  /** Call `Dog.testMethod` over HTTP. Instance method. */
  async testMethod(
    fetchImpl: typeof fetch = fetch
  ): Promise<HttpResult<void>> {
    const __$id = [
      encodeURIComponent(String(this.id)),
    ].join("/");
    const __$baseUrl = new URL(
      `http://localhost:5716/api/Dog/${__$id}/testMethod`
    );
    const __$payload: any = {};

    const __$res = await fetchImpl(__$baseUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: requestBody(MediaType.Json, __$payload),
    });

    return await HttpResult.fromResponse(
      __$res,
      MediaType.Json,
      undefined,
      false
    );
  }
  /** Call `Dog.$save` over HTTP. Static method. */
  static async $save(
    model: DeepPartial<Dog>,
    fetchImpl: typeof fetch = fetch
  ): Promise<HttpResult<Dog>> {
    const __$baseUrl = new URL(
      `http://localhost:5716/api/Dog/$save`
    );
    const __$payload: any = {};
    __$payload["model"] = model;

    const __$res = await fetchImpl(__$baseUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: requestBody(MediaType.Json, __$payload),
    });

    return await HttpResult.fromResponse(
      __$res,
      MediaType.Json,
      Dog,
      false
    );
  }

  /** @internal Reconstruct from a plain JSON object. */
  static fromJson(data: any): Dog {
    const __$res = Object.assign(new Dog(), data);
    __$res["person"] &&= Person.fromJson(__$res.person);
    return __$res;
  }
}
/**
 * Typed client for the `CourseStudent` model.
 *
 * Each method performs an HTTP request and returns an {@link HttpResult}.
 * Pass an optional `fetchImpl` as the last argument to customize requests (e.g. auth headers).
 *
 * @example
 * ```ts
 * const authed: typeof fetch = (url, init) =>
 *   fetch(url, { ...init, headers: { ...init?.headers, Authorization: token } });
 *
 * const res = await CourseStudent.someApi(arg, authed);
 * if (!res.ok) throw new Error(res.message);
 * console.log(res.data);
 * ```
 *
 * @example Streaming methods resolve to `HttpResult<Response>` — read the body off `res.data`
 * ```ts
 * const res = await CourseStudent.download(id);
 * if (!res.ok) throw new Error(res.message);
 * const blob = await res.data!.blob();        // or .body / .arrayBuffer()
 * ```
 */
export class CourseStudent {
  courseId: number;
  studentId: number;
  course: Course | undefined;
  student: Student | undefined;

  /** @internal Reconstruct from a plain JSON object. */
  static fromJson(data: any): CourseStudent {
    const __$res = Object.assign(new CourseStudent(), data);
    __$res["course"] &&= Course.fromJson(__$res.course);
    __$res["student"] &&= Student.fromJson(__$res.student);
    return __$res;
  }
}
/** @internal */
function dsKey(args: object): string {
  return Object.keys(args)[0];
}

/** @internal */
type DeepPartialInner<T> = T extends (infer U)[]
  ? DeepPartialInner<U>[]
  : T extends object
  ? { [K in keyof T]?: DeepPartialInner<T[K]> }
  : T | (null extends T ? null : never);
/** Recursively-optional version of `T`. Used for partial update payloads. */
export type DeepPartial<T> = DeepPartialInner<T> & { __$brand?: "Partial" };

/**
 * Key/value entry from a KV-backed field. Access the typed value via {@link value}.
 *
 * A model's KV fields hydrate to a `KValue<V>` on the client. Read the stored value through
 * `.value` (typed `V | null`); `.raw` and `.metadata` hold the untyped underlying entry.
 *
 * @example
 * ```ts
 * const res = await User.by_id(id);
 * const profile = res.data!.profile.value; // V | null
 * ```
 */
export class KValue<V> {
  raw: unknown | null;
  metadata: unknown | null;
  /** The stored value cast to its declared type, or `null` if absent. */
  get value(): V | null {
    return this.raw as V | null;
  }
}

/** The wire encoding of a request/response body: structured JSON or raw bytes. */
export enum MediaType {
  Json = "Json",
  Octet = "Octet",
}

/** @internal */
declare const Buffer: any;
/** Decode a base64 string into a `Uint8Array`. Works in both Node and the browser. */
export function b64ToU8(b64: string): Uint8Array {
  if (typeof Buffer !== "undefined") {
    const buffer = Buffer.from(b64, "base64");
    return new Uint8Array(buffer);
  }
  const s = atob(b64);
  const u8 = new Uint8Array(s.length);
  for (let i = 0; i < s.length; i++) {
    u8[i] = s.charCodeAt(i);
  }
  return u8;
}

/** Encode a `Uint8Array` as a base64 string. Works in both Node and the browser. */
export function u8ToB64(u8: Uint8Array): string {
  if (typeof Buffer !== "undefined") {
    return Buffer.from(u8).toString("base64");
  }
  let s = "";
  for (let i = 0; i < u8.length; i++) {
    s += String.fromCharCode(u8[i]);
  }
  return btoa(s);
}

/** Client-side metadata for an object stored in an R2 bucket. */
export class R2Object {
  key!: string;
  version!: string;
  size!: number;
  etag!: string;
  httpEtag!: string;
  uploaded!: Date;
  customMetadata?: Record<string, string>;
}

/** @internal */
function requestBody(
  mediaType: MediaType,
  data: any | string | undefined,
): BodyInit | undefined {
  switch (mediaType) {
    case MediaType.Json: {
      return JSON.stringify(data ?? {}, (_, v) => {
        if (v instanceof Uint8Array) {
          return u8ToB64(v);
        }
        return v;
      });
    }
    case MediaType.Octet: {
      return Object.values(data)[0] as BodyInit;
    }
  }
}

/**
 * Result of every client API call. Wraps the HTTP outcome for non-throwing control flow.
 *
 * @example
 * ```ts
 * const res = await User.login(username);
 * if (!res.ok) {
 *   console.error(res.status, res.message);
 *   return;
 * }
 * useSession(res.data!.token);
 * ```
 */
export class HttpResult<T = unknown> {
  public constructor(
    public ok: boolean,
    public status: number,
    public headers: Headers,
    public data?: T,
    public message?: string,
    public mediaType?: MediaType,
  ) { }

  /** @internal Build from a raw `fetch` `Response`. */
  static async fromResponse(
    response: Response,
    mediaType: MediaType,
    ctor?: any,
    array: boolean = false,
  ): Promise<HttpResult<any>> {
    if (response.status >= 400) {
      return new HttpResult(
        false,
        response.status,
        response.headers,
        undefined,
        await response.text(),
      );
    }

    function instantiate(json: any, ctor?: any) {
      switch (ctor) {
        case Date: {
          return new Date(json);
        }
        case Uint8Array: {
          return b64ToU8(json);
        }
        case undefined: {
          return json;
        }
        default: {
          return ctor.fromJson(json);
        }
      }
    }

    async function data() {
      switch (mediaType) {
        case MediaType.Json: {
          const data = await response.json();

          if (array && Array.isArray(data)) {
            for (let i = 0; i < data.length; i++) {
              data[i] = instantiate(data[i], ctor);
            }
            return data;
          }
          return instantiate(data, ctor);
        }
        case MediaType.Octet: {
          return response;
        }
      }
    }
    return new HttpResult(
      true,
      response.status,
      response.headers,
      await data(),
    );
  }
}