// GENERATED BY CLOESCE. DO NOT MODIFY.
import { HttpResult, KValue, CloesceApp, Orm, IncludeTree, DeepPartial, Paginated } from "cloesce";
import { R2Bucket, KVNamespace, D1Database, R2Object, D1PreparedStatement, R2ObjectBody } from "@cloudflare/workers-types";

type MaybePromise<T> = T | Promise<T>;
type MaybeHttpResult<T> = T | HttpResult<T>;
export interface Env {
    db: D1Database;
}
export namespace Dog {
    export const Tag = "Dog";
    export const Meta = cidl.models.Dog as any;

    export interface Self {
        id: number;
        name: string;
        age: number;
    }

    export abstract class Api {
        readonly tag = Tag;
        abstract create(dog: DeepPartial<Dog.Self>): MaybePromise<MaybeHttpResult<Dog.Self>>;
        abstract getPartialSelf(self: Dog.Self): MaybePromise<MaybeHttpResult<DeepPartial<Dog.Self>>>;
    }

    export namespace DataSources {
        export const Default = {
            include: {},
            getQuery: (env: Env, id: number) => env.db.prepare(`SELECT "Dog"."id" AS "id", "Dog"."name" AS "name", "Dog"."age" AS "age" FROM "Dog" WHERE "Dog"."id" = ?1`).bind(id),
            async get(env: Env, id: number): Promise<Dog.Self | null> {
                return await Orm.fromEnv(env).get<Dog.Self>(Dog.Meta, Dog.DataSources.Default.getQuery(env, id), Dog.DataSources.Default.include, {  });
            },
            listQuery: (env: Env, lastSeen_id: number, limit: number) => env.db.prepare(`SELECT "Dog"."id" AS "id", "Dog"."name" AS "name", "Dog"."age" AS "age" FROM "Dog" WHERE "Dog"."id" > ?1 ORDER BY "Dog"."id" ASC LIMIT ?2`).bind(lastSeen_id, limit),
            async list(env: Env, lastSeen_id: number, limit: number): Promise<Dog.Self[]> {
                return await Orm.fromEnv(env).list<Dog.Self>(Dog.Meta, Dog.DataSources.Default.listQuery(env, lastSeen_id, limit), Dog.DataSources.Default.include);
            },
        }
    }

    export async function save(env: Env, newModel: DeepPartial<Self>, include: IncludeTree<Self> = DataSources.Default.include): Promise<Self | null> {
        return await Orm.fromEnv(env).upsert<Self>(Meta, newModel, include);
    }

    export async function get(env: Env, args: { query?: D1PreparedStatement, include?: IncludeTree<Self> }): Promise<Self | null> {
        args.include ??= DataSources.Default.include;
        return await Orm.fromEnv(env).get<Self>(Meta, args.query, args.include, {});
    }

    export async function list(env: Env, args: { query?: D1PreparedStatement, include?: IncludeTree<Self> }): Promise<Self[]> {
        args.include ??= DataSources.Default.include;
        return await Orm.fromEnv(env).list<Self>(Meta, args.query, args.include);
    }
}
import cidl from "./cidl.json" with { type: "json" };
(cidl.models.Dog.data_sources["Default"] as any).gen = Dog.DataSources.Default;

export async function cloesce(): Promise<CloesceApp> {
    return await CloesceApp.init(cidl as any, "http://localhost:5646/api")
}

// Default entrypoint for a Cloesce app. 
// Replace with a custom fetch handler to register API implementations, add middleware, etc.
export default {
    async fetch(request: Request, env: Env): Promise<Response> {
        const app = await cloesce();
        return await app.run(request, env);
    }
}