// GENERATED BY CLOESCE. DO NOT MODIFY.
import { HttpResult, KValue, CloesceApp, Orm as CloesceOrm, IncludeTree, DeepPartial, Paginated, CloesceResult, CloesceError, SqlStatement, applyDurableMigrations, DurableMigration } from "cloesce";
import { R2Bucket, KVNamespace, D1Database, R2Object, D1PreparedStatement, D1Result, R2ObjectBody, ReadableStream } from "@cloudflare/workers-types";
import { DurableObject } from "cloudflare:workers";

export type CfReadableStream = ReadableStream;
export type MaybePromise<T> = T | Promise<T>;
export type MaybeHttpResult<T> = T | HttpResult<T>;
export type ApiResult<T> = MaybePromise<MaybeHttpResult<T>>;

export interface CfEnv {
    db: D1Database;
}

export namespace Env {
}

export type Env = CfEnv & {
};

export function upgradeEnv(env: CfEnv): Env {
    return env as Env;
}
export namespace FailModel {
    export const Tag = "FailModel" as const;
    export const Meta = cidl.models.FailModel as any;

    export interface Self {
        id: number;
        name: string;
    }

    export interface Api {
        throwingMethod(
            self: FailModel.Self,
        ): ApiResult<void>;
        numericValidators(
            self: FailModel.Self,
            gtField: number,
            gteField: number,
            ltField: number,
            lteField: number,
            stepField: number,
        ): ApiResult<void>;
        stringValidators(
            self: FailModel.Self,
            lenField: string,
            minLenField: string,
            maxLenField: string,
            regexField: string,
        ): ApiResult<void>;
    }
    export const _api = undefined as unknown as Api;

    export interface Sources {
    }

    export namespace GeneratedSource {
        export const Default = {
            tree: {},
            selectQuery: `SELECT "FailModel"."id" AS "id", "FailModel"."name" AS "name" FROM "FailModel"`,

            getQuery(env: { db: CfEnv["db"] }, id: number): D1PreparedStatement {
                return env.db.prepare(`SELECT "FailModel"."id" AS "id", "FailModel"."name" AS "name" FROM "FailModel" WHERE "FailModel"."id" = ?1`).bind(id);
            },
            listQuery(env: { db: CfEnv["db"] }, lastSeen_id: number, limit: number): D1PreparedStatement {
                return env.db.prepare(`SELECT "FailModel"."id" AS "id", "FailModel"."name" AS "name" FROM "FailModel" WHERE "FailModel"."id" > ?1 ORDER BY "FailModel"."id" ASC LIMIT ?2`).bind(lastSeen_id, limit);
            },
            async get(env: { db: Env["db"] }, id: number): Promise<HttpResult<Self | null>> {
                const stmt = this.getQuery(env, id);
                const res = await CloesceOrm.fromEnv(env).get<Self>(Meta, stmt, this.tree);
                if (res.errors.length > 0) {
                    return HttpResult.fail(400, CloesceError.displayErrors(res));
                }
                if (res.value === null) {
                    return HttpResult.fail(404);
                }
                return HttpResult.ok(200, res.value);
            },
            async list(env: { db: Env["db"] }, lastSeen_id: number, limit: number): Promise<HttpResult<Self[]>> {
                const stmt = this.listQuery(env, lastSeen_id, limit);
                const res = await CloesceOrm.fromEnv(env).list<Self>(Meta, stmt, this.tree);
                if (res.errors.length > 0) {
                    return HttpResult.fail(400, CloesceError.displayErrors(res));
                }
                return HttpResult.ok(200, res.value!);
            },
            async save(env: { db: Env["db"] }, model: DeepPartial<Self>): Promise<HttpResult<Self | null>> {
                let res = await CloesceOrm.fromEnv(env).upsert<Self>(Meta, model, this.tree);
                if (res.errors.length > 0) {
                    return HttpResult.fail(400, CloesceError.displayErrors(res));
                }
                if (res.value === null) {
                    return HttpResult.fail(404);
                }
                return HttpResult.ok(200, res.value);
            },
        };
    }

    export function impl<Impl extends Api & Sources>(implObj: Impl & ThisType<{ tag: string; Orm: typeof Orm; Default: typeof GeneratedSource.Default } & Impl>): { tag: string; Orm: typeof Orm; Default: typeof GeneratedSource.Default } & Impl {
        return _impl("FailModel", { Orm, Default: GeneratedSource.Default }, implObj) as any;
    }

    export namespace Orm {
        export async function save(env: { db: CfEnv["db"] }, newModel: DeepPartial<Self>, include: IncludeTree<Self> = GeneratedSource.Default.tree): Promise<CloesceResult<Self | null>> {
            return await CloesceOrm.fromEnv(env).upsert<Self>(Meta, newModel, include);
        }

        export async function get(env: { db: CfEnv["db"] }, args: { query?: D1PreparedStatement, include?: IncludeTree<Self> }): Promise<CloesceResult<Self | null>> {
            args.include ??= GeneratedSource.Default.tree
            return await CloesceOrm.fromEnv(env).get<Self>(Meta, args.query, args.include);
        }

        export async function list(env: { db: CfEnv["db"] }, args: { query?: D1PreparedStatement, include?: IncludeTree<Self> }): Promise<CloesceResult<FailModel.Self[]>> {
            args.include ??= GeneratedSource.Default.tree;
            return await CloesceOrm.fromEnv(env).list<Self>(Meta, args.query, args.include);
        }

        export function map(result: D1Result, include: IncludeTree<Self> = GeneratedSource.Default.tree): Self[] {
            return CloesceOrm.map<Self>(Meta, result, include);
        }

        export async function hydrate(env: { db: CfEnv["db"] }, base: DeepPartial<Self>, include: IncludeTree<Self> = GeneratedSource.Default.tree): Promise<CloesceResult<Self>> {
            return await CloesceOrm.fromEnv(env).hydrate<Self>(Meta, base, include);
        }
    }
}
export namespace UnregisteredService {
    export const Tag = "UnregisteredService" as const;

    export interface Api {
        unregistered(
        ): ApiResult<string>;
    }
    export const _api = undefined as unknown as Api;

    export function impl<Impl extends Api>(implObj: Impl): Impl & { tag: typeof Tag } {
        return _impl("UnregisteredService", {}, implObj);
    }
}

function _impl(modelName: string, extras: Record<string, any>, implObj: any) {
    const base: any = { ...implObj, ...extras, tag: modelName };
    for (const key of Object.keys(base)) {
        const v = base[key];
        if (typeof v === "function") base[key] = v.bind(base);
    }
    return base;
}

function _implDs(generated: Record<string, any>, user: Record<string, any>) {
    const merged: any = { ...generated, ...user };
    for (const key of Object.keys(merged)) {
        const v = merged[key];
        if (typeof v === "function") merged[key] = v.bind(merged);
    }
    return merged;
}

import cidl from "./cidl.json" with { type: "json" };

export function cloesce(env: CfEnv): CloesceApp {
    // @ts-expect-error
    return new CloesceApp(cidl as any, "http://localhost:5409/api", upgradeEnv(env));
}

// Default entrypoint for a Cloesce app.
// Replace with a custom fetch handler to register API implementations, add middleware, etc.
export default {
    async fetch(request: Request, env: CfEnv): Promise<Response> {
        const app = cloesce(env);
        return await app.run(request);
    }
}