// GENERATED BY CLOESCE. DO NOT MODIFY.
import { HttpResult, KValue, CloesceApp, Orm as CloesceOrm, IncludeTree, DeepPartial, Paginated } from "cloesce";
import { R2Bucket, KVNamespace, D1Database, R2Object, D1PreparedStatement, D1Result, R2ObjectBody, ReadableStream } from "@cloudflare/workers-types";

export type CfReadableStream = ReadableStream;
export type MaybePromise<T> = T | Promise<T>;
export type MaybeHttpResult<T> = T | HttpResult<T>;
export type ApiResult<T> = MaybePromise<MaybeHttpResult<T>>;
export interface Env {
    db: D1Database;
}
export namespace CrudHaver {
    export const Kind = "model" as const;
    export const Tag = "CrudHaver" as const;
    export const Meta = cidl.models.CrudHaver as any;

    export interface Self {
        id: number;
        name: string;
    }

    export namespace Key {
    }

    export interface Api {
        notCrud(self: CrudHaver.Self): ApiResult<void>;
    }
    export const _api = undefined as unknown as Api;

    export function impl<Impl extends Api>(implObj: Impl & ThisType<Impl & typeof Source & { tag: string; Key: any; Orm: typeof Orm }>): Impl & typeof Source & { tag: string; Key: any; Orm: typeof Orm } {
        return _impl(CrudHaver, implObj);
    }

    export namespace Source {
        export const Default = {
            include: {},
            getQuery: (env: Env, id: number) => env.db.prepare(`SELECT "CrudHaver"."id" AS "id", "CrudHaver"."name" AS "name" FROM "CrudHaver" WHERE "CrudHaver"."id" = ?1`).bind(id),
            async get(env: Env, id: number): Promise<CrudHaver.Self | null> {
                return await CloesceOrm.fromEnv(env).get<CrudHaver.Self>(CrudHaver.Meta, CrudHaver.Source.Default.getQuery(env, id), CrudHaver.Source.Default.include, {  });
            },
            listQuery: (env: Env, lastSeen_id: number, limit: number) => env.db.prepare(`SELECT "CrudHaver"."id" AS "id", "CrudHaver"."name" AS "name" FROM "CrudHaver" WHERE "CrudHaver"."id" > ?1 ORDER BY "CrudHaver"."id" ASC LIMIT ?2`).bind(lastSeen_id, limit),
            async list(env: Env, lastSeen_id: number, limit: number): Promise<CrudHaver.Self[]> {
                return await CloesceOrm.fromEnv(env).list<CrudHaver.Self>(CrudHaver.Meta, CrudHaver.Source.Default.listQuery(env, lastSeen_id, limit), CrudHaver.Source.Default.include);
            },
        }
    }

    export namespace Orm {
        export async function save(env: Env, newModel: DeepPartial<Self>, include: IncludeTree<Self> = Source.Default.include): Promise<Self | null> {
            return await CloesceOrm.fromEnv(env).upsert<Self>(Meta, newModel, include);
        }

        export async function get(env: Env, args: { query?: D1PreparedStatement, include?: IncludeTree<Self> }): Promise<Self | null> {
            args.include ??= Source.Default.include;
            return await CloesceOrm.fromEnv(env).get<Self>(Meta, args.query, args.include, {});
        }

        export async function list(env: Env, args: { query?: D1PreparedStatement, include?: IncludeTree<Self> }): Promise<Self[]> {
            args.include ??= Source.Default.include;
            return await CloesceOrm.fromEnv(env).list<Self>(Meta, args.query, args.include);
        }

        export function select(include: IncludeTree<Self> = Source.Default.include, from?: string): string {
            return CloesceOrm.select(Meta, from ?? null, include);
        }

        export function map(result: D1Result): Self[] {
            return CloesceOrm.map<Self>(Meta, result, Source.Default.include);
        }

        export async function hydrate(env: Env, base: DeepPartial<Self>, include: IncludeTree<Self> = Source.Default.include): Promise<Self> {
            return await CloesceOrm.fromEnv(env).hydrate<Self>(Meta, base, {  }, include);
        }
    }
}
export namespace Parent {
    export const Kind = "model" as const;
    export const Tag = "Parent" as const;
    export const Meta = cidl.models.Parent as any;

    export interface Self {
        id: number;
        favoriteChildId: number | null;
        favoriteChild: Child.Self;
        children: Child.Self[];
    }

    export namespace Key {
    }

    export interface Api {
    }
    export const _api = undefined as unknown as Api;

    export function impl<Impl extends Api>(implObj: Impl & ThisType<Impl & typeof Source & { tag: string; Key: any; Orm: typeof Orm }>): Impl & typeof Source & { tag: string; Key: any; Orm: typeof Orm } {
        return _impl(Parent, implObj);
    }

    export namespace Source {
        export const Default = {
            include: {"children":{},"favoriteChild":{}},
            getQuery: (env: Env, id: number) => env.db.prepare(`SELECT "Parent"."id" AS "id", "Parent"."favoriteChildId" AS "favoriteChildId", "Child_1"."id" AS "favoriteChild.id", "Child_1"."parentId" AS "favoriteChild.parentId", "Child_2"."id" AS "children.id", "Child_2"."parentId" AS "children.parentId" FROM "Parent" LEFT JOIN "Child" AS "Child_1" ON "Parent"."favoriteChildId" = "Child_1"."id" LEFT JOIN "Child" AS "Child_2" ON "Parent"."id" = "Child_2"."parentId" WHERE "Parent"."id" = ?1`).bind(id),
            async get(env: Env, id: number): Promise<Parent.Self | null> {
                return await CloesceOrm.fromEnv(env).get<Parent.Self>(Parent.Meta, Parent.Source.Default.getQuery(env, id), Parent.Source.Default.include, {  });
            },
            listQuery: (env: Env, lastSeen_id: number, limit: number) => env.db.prepare(`SELECT "Parent"."id" AS "id", "Parent"."favoriteChildId" AS "favoriteChildId", "Child_1"."id" AS "favoriteChild.id", "Child_1"."parentId" AS "favoriteChild.parentId", "Child_2"."id" AS "children.id", "Child_2"."parentId" AS "children.parentId" FROM "Parent" LEFT JOIN "Child" AS "Child_1" ON "Parent"."favoriteChildId" = "Child_1"."id" LEFT JOIN "Child" AS "Child_2" ON "Parent"."id" = "Child_2"."parentId" WHERE "Parent"."id" > ?1 ORDER BY "Parent"."id" ASC LIMIT ?2`).bind(lastSeen_id, limit),
            async list(env: Env, lastSeen_id: number, limit: number): Promise<Parent.Self[]> {
                return await CloesceOrm.fromEnv(env).list<Parent.Self>(Parent.Meta, Parent.Source.Default.listQuery(env, lastSeen_id, limit), Parent.Source.Default.include);
            },
        }
        export const WithChildren = {
            include: {"children":{},"favoriteChild":{}},
            getQuery: (env: Env, id: number) => env.db.prepare(`SELECT "Parent"."id" AS "id", "Parent"."favoriteChildId" AS "favoriteChildId", "Child_1"."id" AS "favoriteChild.id", "Child_1"."parentId" AS "favoriteChild.parentId", "Child_2"."id" AS "children.id", "Child_2"."parentId" AS "children.parentId" FROM "Parent" LEFT JOIN "Child" AS "Child_1" ON "Parent"."favoriteChildId" = "Child_1"."id" LEFT JOIN "Child" AS "Child_2" ON "Parent"."id" = "Child_2"."parentId" WHERE "Parent"."id" = ?1`).bind(id),
            async get(env: Env, id: number): Promise<Parent.Self | null> {
                return await CloesceOrm.fromEnv(env).get<Parent.Self>(Parent.Meta, Parent.Source.WithChildren.getQuery(env, id), Parent.Source.WithChildren.include, {  });
            },
            listQuery: (env: Env, lastSeen_id: number, limit: number) => env.db.prepare(`SELECT "Parent"."id" AS "id", "Parent"."favoriteChildId" AS "favoriteChildId", "Child_1"."id" AS "favoriteChild.id", "Child_1"."parentId" AS "favoriteChild.parentId", "Child_2"."id" AS "children.id", "Child_2"."parentId" AS "children.parentId" FROM "Parent" LEFT JOIN "Child" AS "Child_1" ON "Parent"."favoriteChildId" = "Child_1"."id" LEFT JOIN "Child" AS "Child_2" ON "Parent"."id" = "Child_2"."parentId" WHERE "Parent"."id" > ?1 ORDER BY "Parent"."id" ASC LIMIT ?2`).bind(lastSeen_id, limit),
            async list(env: Env, lastSeen_id: number, limit: number): Promise<Parent.Self[]> {
                return await CloesceOrm.fromEnv(env).list<Parent.Self>(Parent.Meta, Parent.Source.WithChildren.listQuery(env, lastSeen_id, limit), Parent.Source.WithChildren.include);
            },
        }
    }

    export namespace Orm {
        export async function save(env: Env, newModel: DeepPartial<Self>, include: IncludeTree<Self> = Source.Default.include): Promise<Self | null> {
            return await CloesceOrm.fromEnv(env).upsert<Self>(Meta, newModel, include);
        }

        export async function get(env: Env, args: { query?: D1PreparedStatement, include?: IncludeTree<Self> }): Promise<Self | null> {
            args.include ??= Source.Default.include;
            return await CloesceOrm.fromEnv(env).get<Self>(Meta, args.query, args.include, {});
        }

        export async function list(env: Env, args: { query?: D1PreparedStatement, include?: IncludeTree<Self> }): Promise<Self[]> {
            args.include ??= Source.Default.include;
            return await CloesceOrm.fromEnv(env).list<Self>(Meta, args.query, args.include);
        }

        export function select(include: IncludeTree<Self> = Source.Default.include, from?: string): string {
            return CloesceOrm.select(Meta, from ?? null, include);
        }

        export function map(result: D1Result): Self[] {
            return CloesceOrm.map<Self>(Meta, result, Source.Default.include);
        }

        export async function hydrate(env: Env, base: DeepPartial<Self>, include: IncludeTree<Self> = Source.Default.include): Promise<Self> {
            return await CloesceOrm.fromEnv(env).hydrate<Self>(Meta, base, {  }, include);
        }
    }
}
export namespace Child {
    export const Kind = "model" as const;
    export const Tag = "Child" as const;
    export const Meta = cidl.models.Child as any;

    export interface Self {
        id: number;
        parentId: number;
        parent: Parent.Self;
    }

    export namespace Key {
    }

    export interface Api {
    }
    export const _api = undefined as unknown as Api;

    export function impl<Impl extends Api>(implObj: Impl & ThisType<Impl & typeof Source & { tag: string; Key: any; Orm: typeof Orm }>): Impl & typeof Source & { tag: string; Key: any; Orm: typeof Orm } {
        return _impl(Child, implObj);
    }

    export namespace Source {
        export const Default = {
            include: {"parent":{"children":{}}},
            getQuery: (env: Env, id: number) => env.db.prepare(`SELECT "Child"."id" AS "id", "Child"."parentId" AS "parentId", "Parent_1"."id" AS "parent.id", "Parent_1"."favoriteChildId" AS "parent.favoriteChildId", "Child_2"."id" AS "parent.children.id", "Child_2"."parentId" AS "parent.children.parentId" FROM "Child" LEFT JOIN "Parent" AS "Parent_1" ON "Child"."parentId" = "Parent_1"."id" LEFT JOIN "Child" AS "Child_2" ON "Parent_1"."id" = "Child_2"."parentId" WHERE "Child"."id" = ?1`).bind(id),
            async get(env: Env, id: number): Promise<Child.Self | null> {
                return await CloesceOrm.fromEnv(env).get<Child.Self>(Child.Meta, Child.Source.Default.getQuery(env, id), Child.Source.Default.include, {  });
            },
            listQuery: (env: Env, lastSeen_id: number, limit: number) => env.db.prepare(`SELECT "Child"."id" AS "id", "Child"."parentId" AS "parentId", "Parent_1"."id" AS "parent.id", "Parent_1"."favoriteChildId" AS "parent.favoriteChildId", "Child_2"."id" AS "parent.children.id", "Child_2"."parentId" AS "parent.children.parentId" FROM "Child" LEFT JOIN "Parent" AS "Parent_1" ON "Child"."parentId" = "Parent_1"."id" LEFT JOIN "Child" AS "Child_2" ON "Parent_1"."id" = "Child_2"."parentId" WHERE "Child"."id" > ?1 ORDER BY "Child"."id" ASC LIMIT ?2`).bind(lastSeen_id, limit),
            async list(env: Env, lastSeen_id: number, limit: number): Promise<Child.Self[]> {
                return await CloesceOrm.fromEnv(env).list<Child.Self>(Child.Meta, Child.Source.Default.listQuery(env, lastSeen_id, limit), Child.Source.Default.include);
            },
        }
    }

    export namespace Orm {
        export async function save(env: Env, newModel: DeepPartial<Self>, include: IncludeTree<Self> = Source.Default.include): Promise<Self | null> {
            return await CloesceOrm.fromEnv(env).upsert<Self>(Meta, newModel, include);
        }

        export async function get(env: Env, args: { query?: D1PreparedStatement, include?: IncludeTree<Self> }): Promise<Self | null> {
            args.include ??= Source.Default.include;
            return await CloesceOrm.fromEnv(env).get<Self>(Meta, args.query, args.include, {});
        }

        export async function list(env: Env, args: { query?: D1PreparedStatement, include?: IncludeTree<Self> }): Promise<Self[]> {
            args.include ??= Source.Default.include;
            return await CloesceOrm.fromEnv(env).list<Self>(Meta, args.query, args.include);
        }

        export function select(include: IncludeTree<Self> = Source.Default.include, from?: string): string {
            return CloesceOrm.select(Meta, from ?? null, include);
        }

        export function map(result: D1Result): Self[] {
            return CloesceOrm.map<Self>(Meta, result, Source.Default.include);
        }

        export async function hydrate(env: Env, base: DeepPartial<Self>, include: IncludeTree<Self> = Source.Default.include): Promise<Self> {
            return await CloesceOrm.fromEnv(env).hydrate<Self>(Meta, base, {  }, include);
        }
    }
}

function _impl<NS extends { Kind: "model"; Meta: { name: string }; Source: any; _api: any; Orm: any; Key?: any }, Impl extends NS["_api"]>(namespace: NS, implObj: Impl & ThisType<Impl & NS["Source"] & { tag: string; Key: NS["Key"]; Orm: NS["Orm"] }>): Impl & NS["Source"] & { tag: string; Key: NS["Key"]; Orm: NS["Orm"] };
function _impl<NS extends { Kind: "service"; Tag: string; _api: any }, Impl extends NS["_api"]>(namespace: NS, implObj: Impl): Impl & { tag: NS["Tag"] };
function _impl(namespace: any, implObj: any) {
    if (namespace.Kind === "model") {
        const model = { ...implObj, ...namespace.Source, tag: namespace.Meta.name, Key: namespace.Key, Orm: namespace.Orm };
        for (const key of Object.keys(implObj as object)) {
            const fn = (model as any)[key];
            if (typeof fn === "function") (model as any)[key] = fn.bind(model);
        }
        return model;
    }

    const service = { ...implObj, tag: namespace.Tag };
    for (const key of Object.keys(implObj as object)) {
        const fn = (service as any)[key];
        if (typeof fn === "function") (service as any)[key] = fn.bind(service);
    }
    return service;
}

import cidl from "./cidl.json" with { type: "json" };
(cidl.models.CrudHaver.data_sources["Default"] as any).gen = CrudHaver.Source.Default;
(cidl.models.Parent.data_sources["Default"] as any).gen = Parent.Source.Default;
(cidl.models.Parent.data_sources["WithChildren"] as any).gen = Parent.Source.WithChildren;
(cidl.models.Child.data_sources["Default"] as any).gen = Child.Source.Default;

export async function cloesce(): Promise<CloesceApp> {
    return await CloesceApp.init(cidl as any, "http://localhost:5391/api")
}

// Default entrypoint for a Cloesce app.
// Replace with a custom fetch handler to register API implementations, add middleware, etc.
export default {
    async fetch(request: Request, env: Env): Promise<Response> {
        const app = await cloesce();
        return await app.run(request, env);
    }
}