compatibility_date = "2025-10-02"
main = "./src/api/main.ts"
name = "realworld"

[[d1_databases]]
binding = "Db"
database_id = "replace_with_Db_id"
database_name = "replace_with_Db_name"
migrations_dir = "./migrations/Db"

[[durable_objects.bindings]]
class_name = "FavoriteDo"
name = "FavoriteDo"

[[kv_namespaces]]
binding = "Session"
id = "replace_with_Session_id"

[[migrations]]
new_sqlite_classes = ["FavoriteDo"]
tag = "v1"

[[r2_buckets]]
binding = "Avatars"
bucket_name = "replace-with-avatars-name"
