// GENERATED BY CLOESCE. DO NOT MODIFY.
import { HttpResult, KValue, CloesceApp, Orm, IncludeTree, DeepPartial } from "cloesce";
import { R2Bucket, KVNamespace, D1Database, R2Object, D1PreparedStatement, ReadableStream, R2ObjectBody } from "@cloudflare/workers-types";

type MaybePromise<T> = T | Promise<T>;
type MaybeHttpResult<T> = T | HttpResult<T>;
export interface Env {
    db: D1Database;
}
export interface Poo {
    ds: "Baz" | "Default";
}
export namespace Foo {
    export const Tag = "Foo";
    export const Meta = cidl.models.Foo as any;

    export interface Self {
        id: number;
    }

    export abstract class Api {
        readonly tag = Tag;
        abstract bar(self: Foo.Self, customDs: "Baz" | "Default", oneDs: "Default" | "ShitAss", noDs: "Default", poop: Poo): MaybePromise<MaybeHttpResult<void>>;
    }

    export namespace DataSources {
        export const Baz = {
            include: {},
            getQuery: (env: Env, id: number) => env.db.prepare(`SELECT "Foo"."id" AS "id" FROM "Foo" WHERE "Foo"."id" = ?1`).bind(id),
            async get(env: Env, id: number): Promise<Foo.Self | null> {
                return await Orm.fromEnv(env).getQuery<Foo.Self>(Foo.Meta, Foo.DataSources.Baz.getQuery(env, id), Foo.DataSources.Baz.include, {  });
            },
            listQuery: (env: Env, lastSeen_id: number, limit: number) => env.db.prepare(`SELECT "Foo"."id" AS "id" FROM "Foo" WHERE "Foo"."id" > ?1 ORDER BY "Foo"."id" ASC LIMIT ?2`).bind(lastSeen_id, limit),
            async list(env: Env, lastSeen_id: number, limit: number): Promise<Foo.Self[]> {
                return await Orm.fromEnv(env).listQuery<Foo.Self>(Foo.Meta, Foo.DataSources.Baz.listQuery(env, lastSeen_id, limit), Foo.DataSources.Baz.include);
            },
        }
        export const Default = {
            include: {},
            getQuery: (env: Env, id: number) => env.db.prepare(`SELECT "Foo"."id" AS "id" FROM "Foo" WHERE "Foo"."id" = ?1`).bind(id),
            async get(env: Env, id: number): Promise<Foo.Self | null> {
                return await Orm.fromEnv(env).getQuery<Foo.Self>(Foo.Meta, Foo.DataSources.Default.getQuery(env, id), Foo.DataSources.Default.include, {  });
            },
            listQuery: (env: Env, lastSeen_id: number, limit: number) => env.db.prepare(`SELECT "Foo"."id" AS "id" FROM "Foo" WHERE "Foo"."id" > ?1 ORDER BY "Foo"."id" ASC LIMIT ?2`).bind(lastSeen_id, limit),
            async list(env: Env, lastSeen_id: number, limit: number): Promise<Foo.Self[]> {
                return await Orm.fromEnv(env).listQuery<Foo.Self>(Foo.Meta, Foo.DataSources.Default.listQuery(env, lastSeen_id, limit), Foo.DataSources.Default.include);
            },
        }
    }

    export async function save(env: Env, newModel: DeepPartial<Self>, include: IncludeTree<Self> = DataSources.Default.include): Promise<Self | null> {
        return await Orm.fromEnv(env).upsert<Self>(Meta, newModel, include);
    }

    export async function get(env: Env, args: { query?: D1PreparedStatement, include?: IncludeTree<Self> }): Promise<Self | null> {
        args.include ??= DataSources.Default.include;
        return await Orm.fromEnv(env).getQuery<Self>(Meta, args.query, args.include, {});
    }

    export async function list(env: Env, args: { query?: D1PreparedStatement, include?: IncludeTree<Self> }): Promise<Self[]> {
        args.include ??= DataSources.Default.include;
        return await Orm.fromEnv(env).listQuery<Self>(Meta, args.query, args.include);
    }
}
export namespace NoDs {
    export const Tag = "NoDs";
    export const Meta = cidl.models.NoDs as any;

    export interface Self {
        id: number;
    }

    export abstract class Api {
        readonly tag = Tag;
    }

    export namespace DataSources {
        export const Default = {
            include: {},
            getQuery: (env: Env, id: number) => env.db.prepare(`SELECT "NoDs"."id" AS "id" FROM "NoDs" WHERE "NoDs"."id" = ?1`).bind(id),
            async get(env: Env, id: number): Promise<NoDs.Self | null> {
                return await Orm.fromEnv(env).getQuery<NoDs.Self>(NoDs.Meta, NoDs.DataSources.Default.getQuery(env, id), NoDs.DataSources.Default.include, {  });
            },
            listQuery: (env: Env, lastSeen_id: number, limit: number) => env.db.prepare(`SELECT "NoDs"."id" AS "id" FROM "NoDs" WHERE "NoDs"."id" > ?1 ORDER BY "NoDs"."id" ASC LIMIT ?2`).bind(lastSeen_id, limit),
            async list(env: Env, lastSeen_id: number, limit: number): Promise<NoDs.Self[]> {
                return await Orm.fromEnv(env).listQuery<NoDs.Self>(NoDs.Meta, NoDs.DataSources.Default.listQuery(env, lastSeen_id, limit), NoDs.DataSources.Default.include);
            },
        }
    }

    export async function save(env: Env, newModel: DeepPartial<Self>, include: IncludeTree<Self> = DataSources.Default.include): Promise<Self | null> {
        return await Orm.fromEnv(env).upsert<Self>(Meta, newModel, include);
    }

    export async function get(env: Env, args: { query?: D1PreparedStatement, include?: IncludeTree<Self> }): Promise<Self | null> {
        args.include ??= DataSources.Default.include;
        return await Orm.fromEnv(env).getQuery<Self>(Meta, args.query, args.include, {});
    }

    export async function list(env: Env, args: { query?: D1PreparedStatement, include?: IncludeTree<Self> }): Promise<Self[]> {
        args.include ??= DataSources.Default.include;
        return await Orm.fromEnv(env).listQuery<Self>(Meta, args.query, args.include);
    }
}
export namespace OneDs {
    export const Tag = "OneDs";
    export const Meta = cidl.models.OneDs as any;

    export interface Self {
        id: number;
    }

    export abstract class Api {
        readonly tag = Tag;
    }

    export namespace DataSources {
        export const Default = {
            include: {},
            getQuery: (env: Env, id: number) => env.db.prepare(`SELECT "OneDs"."id" AS "id" FROM "OneDs" WHERE "OneDs"."id" = ?1`).bind(id),
            async get(env: Env, id: number): Promise<OneDs.Self | null> {
                return await Orm.fromEnv(env).getQuery<OneDs.Self>(OneDs.Meta, OneDs.DataSources.Default.getQuery(env, id), OneDs.DataSources.Default.include, {  });
            },
            listQuery: (env: Env, lastSeen_id: number, limit: number) => env.db.prepare(`SELECT "OneDs"."id" AS "id" FROM "OneDs" WHERE "OneDs"."id" > ?1 ORDER BY "OneDs"."id" ASC LIMIT ?2`).bind(lastSeen_id, limit),
            async list(env: Env, lastSeen_id: number, limit: number): Promise<OneDs.Self[]> {
                return await Orm.fromEnv(env).listQuery<OneDs.Self>(OneDs.Meta, OneDs.DataSources.Default.listQuery(env, lastSeen_id, limit), OneDs.DataSources.Default.include);
            },
        }
        export const ShitAss = {
            include: {},
            getQuery: (env: Env, id: number) => env.db.prepare(`SELECT "OneDs"."id" AS "id" FROM "OneDs" WHERE "OneDs"."id" = ?1`).bind(id),
            async get(env: Env, id: number): Promise<OneDs.Self | null> {
                return await Orm.fromEnv(env).getQuery<OneDs.Self>(OneDs.Meta, OneDs.DataSources.ShitAss.getQuery(env, id), OneDs.DataSources.ShitAss.include, {  });
            },
            listQuery: (env: Env, lastSeen_id: number, limit: number) => env.db.prepare(`SELECT "OneDs"."id" AS "id" FROM "OneDs" WHERE "OneDs"."id" > ?1 ORDER BY "OneDs"."id" ASC LIMIT ?2`).bind(lastSeen_id, limit),
            async list(env: Env, lastSeen_id: number, limit: number): Promise<OneDs.Self[]> {
                return await Orm.fromEnv(env).listQuery<OneDs.Self>(OneDs.Meta, OneDs.DataSources.ShitAss.listQuery(env, lastSeen_id, limit), OneDs.DataSources.ShitAss.include);
            },
        }
    }

    export async function save(env: Env, newModel: DeepPartial<Self>, include: IncludeTree<Self> = DataSources.Default.include): Promise<Self | null> {
        return await Orm.fromEnv(env).upsert<Self>(Meta, newModel, include);
    }

    export async function get(env: Env, args: { query?: D1PreparedStatement, include?: IncludeTree<Self> }): Promise<Self | null> {
        args.include ??= DataSources.Default.include;
        return await Orm.fromEnv(env).getQuery<Self>(Meta, args.query, args.include, {});
    }

    export async function list(env: Env, args: { query?: D1PreparedStatement, include?: IncludeTree<Self> }): Promise<Self[]> {
        args.include ??= DataSources.Default.include;
        return await Orm.fromEnv(env).listQuery<Self>(Meta, args.query, args.include);
    }
}
import cidl from "./cidl.json" with { type: "json" };
(cidl.models.Foo.data_sources["Baz"] as any).gen = Foo.DataSources.Baz;
(cidl.models.Foo.data_sources["Default"] as any).gen = Foo.DataSources.Default;
(cidl.models.NoDs.data_sources["Default"] as any).gen = NoDs.DataSources.Default;
(cidl.models.OneDs.data_sources["Default"] as any).gen = OneDs.DataSources.Default;
(cidl.models.OneDs.data_sources["ShitAss"] as any).gen = OneDs.DataSources.ShitAss;

export async function cloesce(): Promise<CloesceApp> {
    return await CloesceApp.init(cidl as any, "http://localhost:5646/api")
}

// Default entrypoint for a Cloesce app. 
// Replace with a custom fetch handler to register API implementations, add middleware, etc.
export default {
    async fetch(request: Request, env: Env): Promise<Response> {
        const app = await cloesce();
        return await app.run(request, env);
    }
}