// GENERATED BY CLOESCE. DO NOT MODIFY.
import { HttpResult, KValue, CloesceApp, Orm as CloesceOrm, IncludeTree, DeepPartial, Paginated } from "cloesce";
import { R2Bucket, KVNamespace, D1Database, R2Object, D1PreparedStatement, D1Result, R2ObjectBody, ReadableStream } from "@cloudflare/workers-types";

export type CfReadableStream = ReadableStream;
export type MaybePromise<T> = T | Promise<T>;
export type MaybeHttpResult<T> = T | HttpResult<T>;
export type ApiResult<T> = MaybePromise<MaybeHttpResult<T>>;
export interface Env {
    db: D1Database;
}
export interface Poo {
    ds: "Baz" | "Default";
}
export namespace Foo {
    export const Kind = "model" as const;
    export const Tag = "Foo" as const;
    export const Meta = cidl.models.Foo as any;

    export interface Self {
        id: number;
    }

    export namespace Key {
    }

    export interface Api {
        bar(self: Foo.Self, customDs: "Baz" | "Default", oneDs: "Default" | "ShitAss", noDs: "Default", poop: Poo): ApiResult<void>;
    }
    export const _api = undefined as unknown as Api;

    export function impl<Impl extends Api>(implObj: Impl & ThisType<typeof Source & { tag: string; Key: any; Orm: typeof Orm }>): typeof Source & { tag: string; Key: any; Orm: typeof Orm } & Impl {
        return _impl(Foo, implObj);
    }

    export namespace Source {
        export const Baz = {
            include: {},
            getQuery: (env: Env, id: number) => env.db.prepare(`SELECT "Foo"."id" AS "id" FROM "Foo" WHERE "Foo"."id" = ?1`).bind(id),
            async get(env: Env, id: number): Promise<Foo.Self | null> {
                return await CloesceOrm.fromEnv(env).get<Foo.Self>(Foo.Meta, Foo.Source.Baz.getQuery(env, id), Foo.Source.Baz.include, {  });
            },
            listQuery: (env: Env, lastSeen_id: number, limit: number) => env.db.prepare(`SELECT "Foo"."id" AS "id" FROM "Foo" WHERE "Foo"."id" > ?1 ORDER BY "Foo"."id" ASC LIMIT ?2`).bind(lastSeen_id, limit),
            async list(env: Env, lastSeen_id: number, limit: number): Promise<Foo.Self[]> {
                return await CloesceOrm.fromEnv(env).list<Foo.Self>(Foo.Meta, Foo.Source.Baz.listQuery(env, lastSeen_id, limit), Foo.Source.Baz.include);
            },
        }
        export const Default = {
            include: {},
            getQuery: (env: Env, id: number) => env.db.prepare(`SELECT "Foo"."id" AS "id" FROM "Foo" WHERE "Foo"."id" = ?1`).bind(id),
            async get(env: Env, id: number): Promise<Foo.Self | null> {
                return await CloesceOrm.fromEnv(env).get<Foo.Self>(Foo.Meta, Foo.Source.Default.getQuery(env, id), Foo.Source.Default.include, {  });
            },
            listQuery: (env: Env, lastSeen_id: number, limit: number) => env.db.prepare(`SELECT "Foo"."id" AS "id" FROM "Foo" WHERE "Foo"."id" > ?1 ORDER BY "Foo"."id" ASC LIMIT ?2`).bind(lastSeen_id, limit),
            async list(env: Env, lastSeen_id: number, limit: number): Promise<Foo.Self[]> {
                return await CloesceOrm.fromEnv(env).list<Foo.Self>(Foo.Meta, Foo.Source.Default.listQuery(env, lastSeen_id, limit), Foo.Source.Default.include);
            },
        }
    }

    export namespace Orm {
        export async function save(env: Env, newModel: DeepPartial<Self>, include: IncludeTree<Self> = Source.Default.include): Promise<Self | null> {
            return await CloesceOrm.fromEnv(env).upsert<Self>(Meta, newModel, include);
        }

        export async function get(env: Env, args: { query?: D1PreparedStatement, include?: IncludeTree<Self> }): Promise<Self | null> {
            args.include ??= Source.Default.include;
            return await CloesceOrm.fromEnv(env).get<Self>(Meta, args.query, args.include, {});
        }

        export async function list(env: Env, args: { query?: D1PreparedStatement, include?: IncludeTree<Self> }): Promise<Self[]> {
            args.include ??= Source.Default.include;
            return await CloesceOrm.fromEnv(env).list<Self>(Meta, args.query, args.include);
        }

        export function select(include: IncludeTree<Self> = Source.Default.include, from?: string): string {
            return CloesceOrm.select(Meta, from ?? null, include);
        }

        export function map(result: D1Result): Self[] {
            return CloesceOrm.map<Self>(Meta, result, Source.Default.include);
        }

        export async function hydrate(env: Env, base: DeepPartial<Self>, include: IncludeTree<Self> = Source.Default.include): Promise<Self> {
            return await CloesceOrm.fromEnv(env).hydrate<Self>(Meta, base, {  }, include);
        }
    }
}
export namespace NoDs {
    export const Kind = "model" as const;
    export const Tag = "NoDs" as const;
    export const Meta = cidl.models.NoDs as any;

    export interface Self {
        id: number;
    }

    export namespace Key {
    }

    export interface Api {
    }
    export const _api = undefined as unknown as Api;

    export function impl<Impl extends Api>(implObj: Impl & ThisType<typeof Source & { tag: string; Key: any; Orm: typeof Orm }>): typeof Source & { tag: string; Key: any; Orm: typeof Orm } & Impl {
        return _impl(NoDs, implObj);
    }

    export namespace Source {
        export const Default = {
            include: {},
            getQuery: (env: Env, id: number) => env.db.prepare(`SELECT "NoDs"."id" AS "id" FROM "NoDs" WHERE "NoDs"."id" = ?1`).bind(id),
            async get(env: Env, id: number): Promise<NoDs.Self | null> {
                return await CloesceOrm.fromEnv(env).get<NoDs.Self>(NoDs.Meta, NoDs.Source.Default.getQuery(env, id), NoDs.Source.Default.include, {  });
            },
            listQuery: (env: Env, lastSeen_id: number, limit: number) => env.db.prepare(`SELECT "NoDs"."id" AS "id" FROM "NoDs" WHERE "NoDs"."id" > ?1 ORDER BY "NoDs"."id" ASC LIMIT ?2`).bind(lastSeen_id, limit),
            async list(env: Env, lastSeen_id: number, limit: number): Promise<NoDs.Self[]> {
                return await CloesceOrm.fromEnv(env).list<NoDs.Self>(NoDs.Meta, NoDs.Source.Default.listQuery(env, lastSeen_id, limit), NoDs.Source.Default.include);
            },
        }
    }

    export namespace Orm {
        export async function save(env: Env, newModel: DeepPartial<Self>, include: IncludeTree<Self> = Source.Default.include): Promise<Self | null> {
            return await CloesceOrm.fromEnv(env).upsert<Self>(Meta, newModel, include);
        }

        export async function get(env: Env, args: { query?: D1PreparedStatement, include?: IncludeTree<Self> }): Promise<Self | null> {
            args.include ??= Source.Default.include;
            return await CloesceOrm.fromEnv(env).get<Self>(Meta, args.query, args.include, {});
        }

        export async function list(env: Env, args: { query?: D1PreparedStatement, include?: IncludeTree<Self> }): Promise<Self[]> {
            args.include ??= Source.Default.include;
            return await CloesceOrm.fromEnv(env).list<Self>(Meta, args.query, args.include);
        }

        export function select(include: IncludeTree<Self> = Source.Default.include, from?: string): string {
            return CloesceOrm.select(Meta, from ?? null, include);
        }

        export function map(result: D1Result): Self[] {
            return CloesceOrm.map<Self>(Meta, result, Source.Default.include);
        }

        export async function hydrate(env: Env, base: DeepPartial<Self>, include: IncludeTree<Self> = Source.Default.include): Promise<Self> {
            return await CloesceOrm.fromEnv(env).hydrate<Self>(Meta, base, {  }, include);
        }
    }
}
export namespace OneDs {
    export const Kind = "model" as const;
    export const Tag = "OneDs" as const;
    export const Meta = cidl.models.OneDs as any;

    export interface Self {
        id: number;
    }

    export namespace Key {
    }

    export interface Api {
    }
    export const _api = undefined as unknown as Api;

    export function impl<Impl extends Api>(implObj: Impl & ThisType<typeof Source & { tag: string; Key: any; Orm: typeof Orm }>): typeof Source & { tag: string; Key: any; Orm: typeof Orm } & Impl {
        return _impl(OneDs, implObj);
    }

    export namespace Source {
        export const Default = {
            include: {},
            getQuery: (env: Env, id: number) => env.db.prepare(`SELECT "OneDs"."id" AS "id" FROM "OneDs" WHERE "OneDs"."id" = ?1`).bind(id),
            async get(env: Env, id: number): Promise<OneDs.Self | null> {
                return await CloesceOrm.fromEnv(env).get<OneDs.Self>(OneDs.Meta, OneDs.Source.Default.getQuery(env, id), OneDs.Source.Default.include, {  });
            },
            listQuery: (env: Env, lastSeen_id: number, limit: number) => env.db.prepare(`SELECT "OneDs"."id" AS "id" FROM "OneDs" WHERE "OneDs"."id" > ?1 ORDER BY "OneDs"."id" ASC LIMIT ?2`).bind(lastSeen_id, limit),
            async list(env: Env, lastSeen_id: number, limit: number): Promise<OneDs.Self[]> {
                return await CloesceOrm.fromEnv(env).list<OneDs.Self>(OneDs.Meta, OneDs.Source.Default.listQuery(env, lastSeen_id, limit), OneDs.Source.Default.include);
            },
        }
        export const ShitAss = {
            include: {},
            getQuery: (env: Env, id: number) => env.db.prepare(`SELECT "OneDs"."id" AS "id" FROM "OneDs" WHERE "OneDs"."id" = ?1`).bind(id),
            async get(env: Env, id: number): Promise<OneDs.Self | null> {
                return await CloesceOrm.fromEnv(env).get<OneDs.Self>(OneDs.Meta, OneDs.Source.ShitAss.getQuery(env, id), OneDs.Source.ShitAss.include, {  });
            },
            listQuery: (env: Env, lastSeen_id: number, limit: number) => env.db.prepare(`SELECT "OneDs"."id" AS "id" FROM "OneDs" WHERE "OneDs"."id" > ?1 ORDER BY "OneDs"."id" ASC LIMIT ?2`).bind(lastSeen_id, limit),
            async list(env: Env, lastSeen_id: number, limit: number): Promise<OneDs.Self[]> {
                return await CloesceOrm.fromEnv(env).list<OneDs.Self>(OneDs.Meta, OneDs.Source.ShitAss.listQuery(env, lastSeen_id, limit), OneDs.Source.ShitAss.include);
            },
        }
    }

    export namespace Orm {
        export async function save(env: Env, newModel: DeepPartial<Self>, include: IncludeTree<Self> = Source.Default.include): Promise<Self | null> {
            return await CloesceOrm.fromEnv(env).upsert<Self>(Meta, newModel, include);
        }

        export async function get(env: Env, args: { query?: D1PreparedStatement, include?: IncludeTree<Self> }): Promise<Self | null> {
            args.include ??= Source.Default.include;
            return await CloesceOrm.fromEnv(env).get<Self>(Meta, args.query, args.include, {});
        }

        export async function list(env: Env, args: { query?: D1PreparedStatement, include?: IncludeTree<Self> }): Promise<Self[]> {
            args.include ??= Source.Default.include;
            return await CloesceOrm.fromEnv(env).list<Self>(Meta, args.query, args.include);
        }

        export function select(include: IncludeTree<Self> = Source.Default.include, from?: string): string {
            return CloesceOrm.select(Meta, from ?? null, include);
        }

        export function map(result: D1Result): Self[] {
            return CloesceOrm.map<Self>(Meta, result, Source.Default.include);
        }

        export async function hydrate(env: Env, base: DeepPartial<Self>, include: IncludeTree<Self> = Source.Default.include): Promise<Self> {
            return await CloesceOrm.fromEnv(env).hydrate<Self>(Meta, base, {  }, include);
        }
    }
}

function _impl<NS extends { Kind: "model"; Meta: { name: string }; Source: any; _api: any; Orm: any; Key?: any }, Impl extends NS["_api"]>(namespace: NS, implObj: Impl & ThisType<NS["Source"] & { tag: string; Key: NS["Key"]; Orm: NS["Orm"] }>): NS["Source"] & { tag: string; Key: NS["Key"]; Orm: NS["Orm"] } & Impl;
function _impl<NS extends { Kind: "service"; Tag: string; _api: any }, Impl extends NS["_api"]>(namespace: NS, implObj: Impl): Impl & { tag: NS["Tag"] };
function _impl(namespace: any, implObj: any) {
    if (namespace.Kind === "model") {
        const model = { ...implObj, ...namespace.Source, tag: namespace.Meta.name, Key: namespace.Key, Orm: namespace.Orm };
        for (const key of Object.keys(implObj as object)) {
            const fn = (model as any)[key];
            if (typeof fn === "function") (model as any)[key] = fn.bind(model);
        }
        return model;
    }

    const service = { ...implObj, tag: namespace.Tag };
    for (const key of Object.keys(implObj as object)) {
        const fn = (service as any)[key];
        if (typeof fn === "function") (service as any)[key] = fn.bind(service);
    }
    return service;
}

import cidl from "./cidl.json" with { type: "json" };
(cidl.models.Foo.data_sources["Baz"] as any).gen = Foo.Source.Baz;
(cidl.models.Foo.data_sources["Default"] as any).gen = Foo.Source.Default;
(cidl.models.NoDs.data_sources["Default"] as any).gen = NoDs.Source.Default;
(cidl.models.OneDs.data_sources["Default"] as any).gen = OneDs.Source.Default;
(cidl.models.OneDs.data_sources["ShitAss"] as any).gen = OneDs.Source.ShitAss;

export async function cloesce(): Promise<CloesceApp> {
    return await CloesceApp.init(cidl as any, "http://localhost:5719/api")
}

// Default entrypoint for a Cloesce app.
// Replace with a custom fetch handler to register API implementations, add middleware, etc.
export default {
    async fetch(request: Request, env: Env): Promise<Response> {
        const app = await cloesce();
        return await app.run(request, env);
    }
}