// GENERATED BY CLOESCE. DO NOT MODIFY.
import { HttpResult, KValue, CloesceApp, Orm as CloesceOrm, IncludeTree, DeepPartial, Paginated } from "cloesce";
import { R2Bucket, KVNamespace, D1Database, R2Object, D1PreparedStatement, D1Result, R2ObjectBody, ReadableStream } from "@cloudflare/workers-types";

export type CfReadableStream = ReadableStream;
export type MaybePromise<T> = T | Promise<T>;
export type MaybeHttpResult<T> = T | HttpResult<T>;
export type ApiResult<T> = MaybePromise<MaybeHttpResult<T>>;
export interface Env {
    db: D1Database;
}
export namespace BlobService {
    export const Kind = "service" as const;
    export const Tag = "BlobService" as const;

    export interface Self {
    }

    export interface Api {
        init?(self: BlobService.Self): ApiResult<void>;
        incrementBlob(b: Uint8Array): ApiResult<Uint8Array>;
    }
    export const _api = undefined as unknown as Api;

    export function impl<Impl extends Api>(implObj: Impl): Impl & { tag: typeof Tag } {
        return _impl(BlobService, implObj);
    }
}
export namespace BlobHaver {
    export const Kind = "model" as const;
    export const Tag = "BlobHaver" as const;
    export const Meta = cidl.models.BlobHaver as any;

    export interface Self {
        id: number;
        blob1: Uint8Array;
        blob2: Uint8Array;
    }

    export namespace Key {
    }

    export interface Api {
        getBlob1(self: BlobHaver.Self): ApiResult<Uint8Array>;
        inputStream(s: CfReadableStream): ApiResult<void>;
        yieldStream(self: BlobHaver.Self): ApiResult<CfReadableStream>;
    }
    export const _api = undefined as unknown as Api;

    export function impl<Impl extends Api>(implObj: Impl & ThisType<typeof Source & { tag: string; Key: any; Orm: typeof Orm }>): typeof Source & { tag: string; Key: any; Orm: typeof Orm } & Impl {
        return _impl(BlobHaver, implObj);
    }

    export namespace Source {
        export const Default = {
            include: {},
            getQuery: (env: Env, id: number) => env.db.prepare(`SELECT "BlobHaver"."id" AS "id", "BlobHaver"."blob1" AS "blob1", "BlobHaver"."blob2" AS "blob2" FROM "BlobHaver" WHERE "BlobHaver"."id" = ?1`).bind(id),
            async get(env: Env, id: number): Promise<BlobHaver.Self | null> {
                return await CloesceOrm.fromEnv(env).get<BlobHaver.Self>(BlobHaver.Meta, BlobHaver.Source.Default.getQuery(env, id), BlobHaver.Source.Default.include, {  });
            },
            listQuery: (env: Env, lastSeen_id: number, limit: number) => env.db.prepare(`SELECT "BlobHaver"."id" AS "id", "BlobHaver"."blob1" AS "blob1", "BlobHaver"."blob2" AS "blob2" FROM "BlobHaver" WHERE "BlobHaver"."id" > ?1 ORDER BY "BlobHaver"."id" ASC LIMIT ?2`).bind(lastSeen_id, limit),
            async list(env: Env, lastSeen_id: number, limit: number): Promise<BlobHaver.Self[]> {
                return await CloesceOrm.fromEnv(env).list<BlobHaver.Self>(BlobHaver.Meta, BlobHaver.Source.Default.listQuery(env, lastSeen_id, limit), BlobHaver.Source.Default.include);
            },
        }
    }

    export namespace Orm {
        export async function save(env: Env, newModel: DeepPartial<Self>, include: IncludeTree<Self> = Source.Default.include): Promise<Self | null> {
            return await CloesceOrm.fromEnv(env).upsert<Self>(Meta, newModel, include);
        }

        export async function get(env: Env, args: { query?: D1PreparedStatement, include?: IncludeTree<Self> }): Promise<Self | null> {
            args.include ??= Source.Default.include;
            return await CloesceOrm.fromEnv(env).get<Self>(Meta, args.query, args.include, {});
        }

        export async function list(env: Env, args: { query?: D1PreparedStatement, include?: IncludeTree<Self> }): Promise<Self[]> {
            args.include ??= Source.Default.include;
            return await CloesceOrm.fromEnv(env).list<Self>(Meta, args.query, args.include);
        }

        export function select(include: IncludeTree<Self> = Source.Default.include, from?: string): string {
            return CloesceOrm.select(Meta, from ?? null, include);
        }

        export function map(result: D1Result): Self[] {
            return CloesceOrm.map<Self>(Meta, result, Source.Default.include);
        }

        export async function hydrate(env: Env, base: DeepPartial<Self>, include: IncludeTree<Self> = Source.Default.include): Promise<Self> {
            return await CloesceOrm.fromEnv(env).hydrate<Self>(Meta, base, {  }, include);
        }
    }
}

function _impl<NS extends { Kind: "model"; Meta: { name: string }; Source: any; _api: any; Orm: any; Key?: any }, Impl extends NS["_api"]>(namespace: NS, implObj: Impl & ThisType<NS["Source"] & { tag: string; Key: NS["Key"]; Orm: NS["Orm"] }>): NS["Source"] & { tag: string; Key: NS["Key"]; Orm: NS["Orm"] } & Impl;
function _impl<NS extends { Kind: "service"; Tag: string; _api: any }, Impl extends NS["_api"]>(namespace: NS, implObj: Impl): Impl & { tag: NS["Tag"] };
function _impl(namespace: any, implObj: any) {
    if (namespace.Kind === "model") {
        const model = { ...implObj, ...namespace.Source, tag: namespace.Meta.name, Key: namespace.Key, Orm: namespace.Orm };
        for (const key of Object.keys(implObj as object)) {
            const fn = (model as any)[key];
            if (typeof fn === "function") (model as any)[key] = fn.bind(model);
        }
        return model;
    }

    const service = { ...implObj, tag: namespace.Tag };
    for (const key of Object.keys(implObj as object)) {
        const fn = (service as any)[key];
        if (typeof fn === "function") (service as any)[key] = fn.bind(service);
    }
    return service;
}

import cidl from "./cidl.json" with { type: "json" };
(cidl.models.BlobHaver.data_sources["Default"] as any).gen = BlobHaver.Source.Default;

export async function cloesce(): Promise<CloesceApp> {
    return await CloesceApp.init(cidl as any, "http://localhost:5270/api")
}

// Default entrypoint for a Cloesce app.
// Replace with a custom fetch handler to register API implementations, add middleware, etc.
export default {
    async fetch(request: Request, env: Env): Promise<Response> {
        const app = await cloesce();
        return await app.run(request, env);
    }
}