// GENERATED BY CLOESCE. DO NOT MODIFY.
import { HttpResult, KValue, CloesceApp, Orm, IncludeTree, DeepPartial } from "cloesce";
import { R2Bucket, KVNamespace, D1Database, R2Object, D1PreparedStatement, ReadableStream, R2ObjectBody } from "@cloudflare/workers-types";

type MaybePromise<T> = T | Promise<T>;
export interface Env {
    db: D1Database;
}
export namespace BlobService {
    export interface Self {
    }

    export abstract class Api {
        readonly tag = "BlobService";
        abstract init(self: BlobService.Self): MaybePromise<HttpResult<void> | void>;
        abstract incrementBlob(b: Uint8Array): MaybePromise<HttpResult<Uint8Array>>;
    }
}
export namespace BlobHaver {
    export const Meta = cidl.models.BlobHaver as any;

    export interface Self {
        id: number;
        blob1: Uint8Array;
        blob2: Uint8Array;
    }

    export abstract class Api {
        readonly tag = "BlobHaver";
        abstract getBlob1(self: BlobHaver.Self): MaybePromise<HttpResult<Uint8Array>>;
        abstract inputStream(s: ReadableStream): MaybePromise<HttpResult<void>>;
        abstract yieldStream(self: BlobHaver.Self): MaybePromise<HttpResult<ReadableStream>>;
    }

    export namespace DataSources {
        export const Default = {
            include: {},
            getQuery: (env: Env, id: number) => env.db.prepare(`SELECT "BlobHaver"."id" AS "id", "BlobHaver"."blob1" AS "blob1", "BlobHaver"."blob2" AS "blob2" FROM "BlobHaver" WHERE "BlobHaver"."id" = ?1`).bind(id),
            async get(env: Env, id: number): Promise<BlobHaver.Self | null> {
                return await Orm.fromEnv(env).getQuery<BlobHaver.Self>(BlobHaver.Meta, BlobHaver.DataSources.Default.getQuery(env, id), BlobHaver.DataSources.Default.include, {  });
            },
            listQuery: (env: Env, lastSeen_id: number, limit: number) => env.db.prepare(`SELECT "BlobHaver"."id" AS "id", "BlobHaver"."blob1" AS "blob1", "BlobHaver"."blob2" AS "blob2" FROM "BlobHaver" WHERE "BlobHaver"."id" > ?1 ORDER BY "BlobHaver"."id" ASC LIMIT ?2`).bind(lastSeen_id, limit),
            async list(env: Env, lastSeen_id: number, limit: number): Promise<BlobHaver.Self[]> {
                return await Orm.fromEnv(env).listQuery<BlobHaver.Self>(BlobHaver.Meta, BlobHaver.DataSources.Default.listQuery(env, lastSeen_id, limit), BlobHaver.DataSources.Default.include);
            },
        }
    }

    export async function save(env: Env, newModel: DeepPartial<Self>, include: IncludeTree<Self> = DataSources.Default.include): Promise<Self | null> {
        return await Orm.fromEnv(env).upsert<Self>(Meta, newModel, include);
    }

    export async function get(env: Env, args: { query?: D1PreparedStatement, include?: IncludeTree<Self> }): Promise<Self | null> {
        args.include ??= DataSources.Default.include;
        return await Orm.fromEnv(env).getQuery<Self>(Meta, args.query, args.include, {});
    }

    export async function list(env: Env, args: { query?: D1PreparedStatement, include?: IncludeTree<Self> }): Promise<Self[]> {
        args.include ??= DataSources.Default.include;
        return await Orm.fromEnv(env).listQuery<Self>(Meta, args.query, args.include);
    }
}
import cidl from "./cidl.json" with { type: "json" };
(cidl.models.BlobHaver.data_sources["Default"] as any).gen = BlobHaver.DataSources.Default;

export async function cloesce(): Promise<CloesceApp> {
    return await CloesceApp.init(cidl as any, "http://localhost:5646/api")
}

// Default entrypoint for a Cloesce app. 
// Replace with a custom fetch handler to register API implementations, add middleware, etc.
export default async function fetch(request: Request, env: Env): Promise<Response> {
    const app = await cloesce();
    return await app.run(request, env);
}