// GENERATED BY CLOESCE. DO NOT MODIFY.
import { HttpResult, KValue, CloesceApp, Orm as CloesceOrm, IncludeTree, DeepPartial, Paginated, CloesceResult, CloesceError, SqlStatement, applyDurableMigrations, DurableMigration } from "cloesce";
import { R2Bucket, KVNamespace, D1Database, R2Object, D1PreparedStatement, D1Result, R2ObjectBody, ReadableStream } from "@cloudflare/workers-types";
import { DurableObject } from "cloudflare:workers";

export type CfReadableStream = ReadableStream;
export type MaybePromise<T> = T | Promise<T>;
export type MaybeHttpResult<T> = T | HttpResult<T>;
export type ApiResult<T> = MaybePromise<MaybeHttpResult<T>>;

export interface CfEnv {
    db1: D1Database;
    db2: D1Database;
}

export namespace Env {
}

export type Env = CfEnv & {
};

export function upgradeEnv(env: CfEnv): Env {
    return env as Env;
}
export namespace DB1Model {
    export const Tag = "DB1Model" as const;
    export const Meta = cidl.models.DB1Model as any;

    export interface Self {
        id: number;
        someColumn: string;
    }

    export interface Api {
    }
    export const _api = undefined as unknown as Api;

    export interface Sources {
    }

    export namespace GeneratedSource {
        export const Default = {
            tree: {},
            selectQuery: `SELECT "DB1Model"."id" AS "id", "DB1Model"."someColumn" AS "someColumn" FROM "DB1Model"`,

            getQuery(env: { db1: CfEnv["db1"] }, id: number): D1PreparedStatement {
                return env.db1.prepare(`SELECT "DB1Model"."id" AS "id", "DB1Model"."someColumn" AS "someColumn" FROM "DB1Model" WHERE "DB1Model"."id" = ?1`).bind(id);
            },
            listQuery(env: { db1: CfEnv["db1"] }, lastSeen_id: number, limit: number): D1PreparedStatement {
                return env.db1.prepare(`SELECT "DB1Model"."id" AS "id", "DB1Model"."someColumn" AS "someColumn" FROM "DB1Model" WHERE "DB1Model"."id" > ?1 ORDER BY "DB1Model"."id" ASC LIMIT ?2`).bind(lastSeen_id, limit);
            },
            async get(env: { db1: Env["db1"] }, id: number): Promise<HttpResult<Self | null>> {
                const stmt = this.getQuery(env, id);
                const res = await CloesceOrm.fromEnv(env).get<Self>(Meta, stmt, this.tree);
                if (res.errors.length > 0) {
                    return HttpResult.fail(400, CloesceError.displayErrors(res));
                }
                if (res.value === null) {
                    return HttpResult.fail(404);
                }
                return HttpResult.ok(200, res.value);
            },
            async list(env: { db1: Env["db1"] }, lastSeen_id: number, limit: number): Promise<HttpResult<Self[]>> {
                const stmt = this.listQuery(env, lastSeen_id, limit);
                const res = await CloesceOrm.fromEnv(env).list<Self>(Meta, stmt, this.tree);
                if (res.errors.length > 0) {
                    return HttpResult.fail(400, CloesceError.displayErrors(res));
                }
                return HttpResult.ok(200, res.value!);
            },
            async save(env: { db1: Env["db1"] }, model: DeepPartial<Self>): Promise<HttpResult<Self | null>> {
                let res = await CloesceOrm.fromEnv(env).upsert<Self>(Meta, model, this.tree);
                if (res.errors.length > 0) {
                    return HttpResult.fail(400, CloesceError.displayErrors(res));
                }
                if (res.value === null) {
                    return HttpResult.fail(404);
                }
                return HttpResult.ok(200, res.value);
            },
        };
    }

    export function impl<Impl extends Api & Sources>(implObj: Impl & ThisType<{ tag: string; Orm: typeof Orm; Default: typeof GeneratedSource.Default } & Impl>): { tag: string; Orm: typeof Orm; Default: typeof GeneratedSource.Default } & Impl {
        return _impl("DB1Model", { Orm, Default: GeneratedSource.Default }, implObj) as any;
    }

    export namespace Orm {
        export async function save(env: { db1: CfEnv["db1"] }, newModel: DeepPartial<Self>, include: IncludeTree<Self> = GeneratedSource.Default.tree): Promise<CloesceResult<Self | null>> {
            return await CloesceOrm.fromEnv(env).upsert<Self>(Meta, newModel, include);
        }

        export async function get(env: { db1: CfEnv["db1"] }, args: { query?: D1PreparedStatement, include?: IncludeTree<Self> }): Promise<CloesceResult<Self | null>> {
            args.include ??= GeneratedSource.Default.tree
            return await CloesceOrm.fromEnv(env).get<Self>(Meta, args.query, args.include);
        }

        export async function list(env: { db1: CfEnv["db1"] }, args: { query?: D1PreparedStatement, include?: IncludeTree<Self> }): Promise<CloesceResult<DB1Model.Self[]>> {
            args.include ??= GeneratedSource.Default.tree;
            return await CloesceOrm.fromEnv(env).list<Self>(Meta, args.query, args.include);
        }

        export function map(result: D1Result, include: IncludeTree<Self> = GeneratedSource.Default.tree): Self[] {
            return CloesceOrm.map<Self>(Meta, result, include);
        }

        export async function hydrate(env: { db1: CfEnv["db1"] }, base: DeepPartial<Self>, include: IncludeTree<Self> = GeneratedSource.Default.tree): Promise<CloesceResult<Self>> {
            return await CloesceOrm.fromEnv(env).hydrate<Self>(Meta, base, include);
        }
    }
}
export namespace DB2Model {
    export const Tag = "DB2Model" as const;
    export const Meta = cidl.models.DB2Model as any;

    export interface Self {
        id: number;
        someColumn: string;
    }

    export interface Api {
    }
    export const _api = undefined as unknown as Api;

    export interface Sources {
    }

    export namespace GeneratedSource {
        export const Default = {
            tree: {},
            selectQuery: `SELECT "DB2Model"."id" AS "id", "DB2Model"."someColumn" AS "someColumn" FROM "DB2Model"`,

            getQuery(env: { db2: CfEnv["db2"] }, id: number): D1PreparedStatement {
                return env.db2.prepare(`SELECT "DB2Model"."id" AS "id", "DB2Model"."someColumn" AS "someColumn" FROM "DB2Model" WHERE "DB2Model"."id" = ?1`).bind(id);
            },
            listQuery(env: { db2: CfEnv["db2"] }, lastSeen_id: number, limit: number): D1PreparedStatement {
                return env.db2.prepare(`SELECT "DB2Model"."id" AS "id", "DB2Model"."someColumn" AS "someColumn" FROM "DB2Model" WHERE "DB2Model"."id" > ?1 ORDER BY "DB2Model"."id" ASC LIMIT ?2`).bind(lastSeen_id, limit);
            },
            async get(env: { db2: Env["db2"] }, id: number): Promise<HttpResult<Self | null>> {
                const stmt = this.getQuery(env, id);
                const res = await CloesceOrm.fromEnv(env).get<Self>(Meta, stmt, this.tree);
                if (res.errors.length > 0) {
                    return HttpResult.fail(400, CloesceError.displayErrors(res));
                }
                if (res.value === null) {
                    return HttpResult.fail(404);
                }
                return HttpResult.ok(200, res.value);
            },
            async list(env: { db2: Env["db2"] }, lastSeen_id: number, limit: number): Promise<HttpResult<Self[]>> {
                const stmt = this.listQuery(env, lastSeen_id, limit);
                const res = await CloesceOrm.fromEnv(env).list<Self>(Meta, stmt, this.tree);
                if (res.errors.length > 0) {
                    return HttpResult.fail(400, CloesceError.displayErrors(res));
                }
                return HttpResult.ok(200, res.value!);
            },
            async save(env: { db2: Env["db2"] }, model: DeepPartial<Self>): Promise<HttpResult<Self | null>> {
                let res = await CloesceOrm.fromEnv(env).upsert<Self>(Meta, model, this.tree);
                if (res.errors.length > 0) {
                    return HttpResult.fail(400, CloesceError.displayErrors(res));
                }
                if (res.value === null) {
                    return HttpResult.fail(404);
                }
                return HttpResult.ok(200, res.value);
            },
        };
    }

    export function impl<Impl extends Api & Sources>(implObj: Impl & ThisType<{ tag: string; Orm: typeof Orm; Default: typeof GeneratedSource.Default } & Impl>): { tag: string; Orm: typeof Orm; Default: typeof GeneratedSource.Default } & Impl {
        return _impl("DB2Model", { Orm, Default: GeneratedSource.Default }, implObj) as any;
    }

    export namespace Orm {
        export async function save(env: { db2: CfEnv["db2"] }, newModel: DeepPartial<Self>, include: IncludeTree<Self> = GeneratedSource.Default.tree): Promise<CloesceResult<Self | null>> {
            return await CloesceOrm.fromEnv(env).upsert<Self>(Meta, newModel, include);
        }

        export async function get(env: { db2: CfEnv["db2"] }, args: { query?: D1PreparedStatement, include?: IncludeTree<Self> }): Promise<CloesceResult<Self | null>> {
            args.include ??= GeneratedSource.Default.tree
            return await CloesceOrm.fromEnv(env).get<Self>(Meta, args.query, args.include);
        }

        export async function list(env: { db2: CfEnv["db2"] }, args: { query?: D1PreparedStatement, include?: IncludeTree<Self> }): Promise<CloesceResult<DB2Model.Self[]>> {
            args.include ??= GeneratedSource.Default.tree;
            return await CloesceOrm.fromEnv(env).list<Self>(Meta, args.query, args.include);
        }

        export function map(result: D1Result, include: IncludeTree<Self> = GeneratedSource.Default.tree): Self[] {
            return CloesceOrm.map<Self>(Meta, result, include);
        }

        export async function hydrate(env: { db2: CfEnv["db2"] }, base: DeepPartial<Self>, include: IncludeTree<Self> = GeneratedSource.Default.tree): Promise<CloesceResult<Self>> {
            return await CloesceOrm.fromEnv(env).hydrate<Self>(Meta, base, include);
        }
    }
}

function _impl(modelName: string, extras: Record<string, any>, implObj: any) {
    const base: any = { ...implObj, ...extras, tag: modelName };
    for (const key of Object.keys(base)) {
        const v = base[key];
        if (typeof v === "function") base[key] = v.bind(base);
    }
    return base;
}

function _implDs(generated: Record<string, any>, user: Record<string, any>) {
    const merged: any = { ...generated, ...user };
    for (const key of Object.keys(merged)) {
        const v = merged[key];
        if (typeof v === "function") merged[key] = v.bind(merged);
    }
    return merged;
}

import cidl from "./cidl.json" with { type: "json" };

export function cloesce(env: CfEnv): CloesceApp {
    // @ts-expect-error
    return new CloesceApp(cidl as any, "http://localhost:5291/api", upgradeEnv(env));
}

// Default entrypoint for a Cloesce app.
// Replace with a custom fetch handler to register API implementations, add middleware, etc.
export default {
    async fetch(request: Request, env: CfEnv): Promise<Response> {
        const app = cloesce(env);
        return await app.run(request);
    }
}