// GENERATED BY CLOESCE. DO NOT MODIFY.
import { HttpResult, KValue, CloesceApp, Orm, IncludeTree, DeepPartial, Paginated } from "cloesce";
import { R2Bucket, KVNamespace, D1Database, R2Object, D1PreparedStatement, D1Result, R2ObjectBody, ReadableStream } from "@cloudflare/workers-types";

export type CfReadableStream = ReadableStream;
export type MaybePromise<T> = T | Promise<T>;
export type MaybeHttpResult<T> = T | HttpResult<T>;
export interface Env {
    db: D1Database;
}
export abstract class InjectedThing {
    readonly tag = "InjectedThing";
}
export namespace Foo {
    export const Tag = "Foo";
    export const Meta = cidl.models.Foo as any;

    export interface Self {
        id: string;
    }

    export namespace KeyFormat {
    }

    export abstract class Api {
        readonly tag = Tag;
        abstract blockedMethod(): MaybePromise<MaybeHttpResult<void>>;
        abstract getInjectedThing(thing: InjectedThing): MaybePromise<MaybeHttpResult<string>>;
    }

    export namespace DataSources {
        export const Default = {
            include: {},
            getQuery: (env: Env, id: string) => env.db.prepare(`SELECT "Foo"."id" AS "id" FROM "Foo" WHERE "Foo"."id" = ?1`).bind(id),
            async get(env: Env, id: string): Promise<Foo.Self | null> {
                return await Orm.fromEnv(env).get<Foo.Self>(Foo.Meta, Foo.DataSources.Default.getQuery(env, id), Foo.DataSources.Default.include, {  });
            },
            listQuery: (env: Env, lastSeen_id: string, limit: number) => env.db.prepare(`SELECT "Foo"."id" AS "id" FROM "Foo" WHERE "Foo"."id" > ?1 ORDER BY "Foo"."id" ASC LIMIT ?2`).bind(lastSeen_id, limit),
            async list(env: Env, lastSeen_id: string, limit: number): Promise<Foo.Self[]> {
                return await Orm.fromEnv(env).list<Foo.Self>(Foo.Meta, Foo.DataSources.Default.listQuery(env, lastSeen_id, limit), Foo.DataSources.Default.include);
            },
        }
    }

    export async function save(env: Env, newModel: DeepPartial<Self>, include: IncludeTree<Self> = DataSources.Default.include): Promise<Self | null> {
        return await Orm.fromEnv(env).upsert<Self>(Meta, newModel, include);
    }

    export async function get(env: Env, args: { query?: D1PreparedStatement, include?: IncludeTree<Self> }): Promise<Self | null> {
        args.include ??= DataSources.Default.include;
        return await Orm.fromEnv(env).get<Self>(Meta, args.query, args.include, {});
    }

    export async function list(env: Env, args: { query?: D1PreparedStatement, include?: IncludeTree<Self> }): Promise<Self[]> {
        args.include ??= DataSources.Default.include;
        return await Orm.fromEnv(env).list<Self>(Meta, args.query, args.include);
    }

    export function select(include: IncludeTree<Self> = DataSources.Default.include, from?: string): string {
        return Orm.select(Meta, from ?? null, include);
    }

    export function map(result: D1Result): Self[] {
        return Orm.map<Self>(Meta, result, DataSources.Default.include);
    }

    export async function hydrate(env: Env, base: DeepPartial<Self>, include: IncludeTree<Self> = DataSources.Default.include): Promise<Self> {
        return await Orm.fromEnv(env).hydrate<Self>(Meta, base, {  }, include);
    }
}
import cidl from "./cidl.json" with { type: "json" };
(cidl.models.Foo.data_sources["Default"] as any).gen = Foo.DataSources.Default;

export async function cloesce(): Promise<CloesceApp> {
    return await CloesceApp.init(cidl as any, "http://localhost:5560/api")
}

// Default entrypoint for a Cloesce app. 
// Replace with a custom fetch handler to register API implementations, add middleware, etc.
export default {
    async fetch(request: Request, env: Env): Promise<Response> {
        const app = await cloesce();
        return await app.run(request, env);
    }
}