// GENERATED BY CLOESCE. DO NOT MODIFY.
import { HttpResult, KValue, CloesceApp, Orm as CloesceOrm, IncludeTree, DeepPartial, Paginated, CloesceResult, CloesceError, InternalError } from "cloesce";
import { R2Bucket, KVNamespace, D1Database, R2Object, D1PreparedStatement, D1Result, R2ObjectBody, ReadableStream } from "@cloudflare/workers-types";

export type CfReadableStream = ReadableStream;
export type MaybePromise<T> = T | Promise<T>;
export type MaybeHttpResult<T> = T | HttpResult<T>;
export type ApiResult<T> = MaybePromise<MaybeHttpResult<T>>;

export interface Env {
    db: D1Database;
}
export namespace DefaultOverride {
    export const Tag = "DefaultOverride" as const;
    export const Meta = cidl.models.DefaultOverride as any;

    export interface Self {
        id: number;
    }

    export interface Api {
    }
    export const _api = undefined as unknown as Api;

    export interface Sources {
        Default: Default.Impl;
    }

    export namespace GeneratedSource {
        export const Default = {
            tree: {},
            selectQueryRaw: `SELECT "DefaultOverride"."id" AS "id" FROM "DefaultOverride"`,
            getQueryRaw: `SELECT "DefaultOverride"."id" AS "id" FROM "DefaultOverride" WHERE "DefaultOverride"."id" = ?1`,
            listQueryRaw: `SELECT "DefaultOverride"."id" AS "id" FROM "DefaultOverride" WHERE "DefaultOverride"."id" > ?1 ORDER BY "DefaultOverride"."id" ASC LIMIT ?2`,

            selectQuery(env: { db: Env["db"] }): D1PreparedStatement {
                return env.db.prepare(this.selectQueryRaw);
            },
            getQuery(env: { db: Env["db"] }): D1PreparedStatement {
                return env.db.prepare(this.getQueryRaw).bind();
            },
            listQuery(env: { db: Env["db"] }): D1PreparedStatement {
                return env.db.prepare(this.listQueryRaw).bind();
            },
            async save(env: { db: Env["db"] }, model: DeepPartial<Self>): Promise<HttpResult<Self | null>> {
                let res: CloesceResult<Self | null>;
                try {
                    res = await CloesceOrm.fromEnv(env).upsert<Self>(Meta, model, this.tree);
                } catch (e) {
                    throw new InternalError(`Upsert failed: ${JSON.stringify(e)}`);
                }
                if (res.errors.length > 0) {
                    return HttpResult.fail(400, CloesceError.displayErrors(res));
                }
                if (res.value === null) {
                    return HttpResult.fail(404);
                }
                return HttpResult.ok(200, res.value);
            },
        };
    }
    export namespace Default {
        export interface Stubs {
            get(env: { db: Env["db"] }): ApiResult<Self>;
            list(env: { db: Env["db"] }): ApiResult<Self[]>;
        }
        export type Impl = typeof GeneratedSource.Default & Stubs;
        export function impl<I extends Stubs>(implObj: I & ThisType<typeof GeneratedSource.Default & I>): typeof GeneratedSource.Default & I {
            return _implDs(GeneratedSource.Default, implObj);
        }
    }

    export function impl<Impl extends Api & Sources>(implObj: Impl & ThisType<{ tag: string; Orm: typeof Orm } & Impl>): { tag: string; Orm: typeof Orm } & Impl {
        return _impl("DefaultOverride", { Orm }, implObj) as any;
    }

    export namespace Orm {
        export async function save(env: { db: Env["db"] }, newModel: DeepPartial<Self>, include: IncludeTree<Self> = GeneratedSource.Default.tree): Promise<CloesceResult<Self | null>> {
            return await CloesceOrm.fromEnv(env).upsert<Self>(Meta, newModel, include);
        }

        export async function get(env: { db: Env["db"] }, args: { query?: D1PreparedStatement, include?: IncludeTree<Self> }): Promise<CloesceResult<Self | null>> {
            args.include ??= GeneratedSource.Default.tree
            return await CloesceOrm.fromEnv(env).get<Self>(Meta, args.query, args.include);
        }

        export async function list(env: { db: Env["db"] }, args: { query?: D1PreparedStatement, include?: IncludeTree<Self> }): Promise<CloesceResult<DefaultOverride.Self[]>> {
            args.include ??= GeneratedSource.Default.tree;
            return await CloesceOrm.fromEnv(env).list<Self>(Meta, args.query, args.include);
        }

        export function select(include: IncludeTree<Self> = GeneratedSource.Default.tree, from?: string): string {
            return CloesceOrm.select(Meta, from ?? null, include);
        }

        export function map(result: D1Result, include: IncludeTree<Self> = GeneratedSource.Default.tree): Self[] {
            return CloesceOrm.map<Self>(Meta, result, include);
        }

        export async function hydrate(env: { db: Env["db"] }, base: DeepPartial<Self>, include: IncludeTree<Self> = GeneratedSource.Default.tree): Promise<CloesceResult<Self>> {
            return await CloesceOrm.fromEnv(env).hydrate<Self>(Meta, base, include);
        }
    }
}
export namespace Hamburger {
    export const Tag = "Hamburger" as const;
    export const Meta = cidl.models.Hamburger as any;

    export interface Self {
        id: number;
        name: string;
        toppings: Topping.Self[];
    }

    export interface Api {
        noLettuceToppings(
            self: Hamburger.Self,
        ): ApiResult<Topping.Self[]>;
        onlyBaconToppings(
            self: Hamburger.Self,
        ): ApiResult<Topping.Self[]>;
    }
    export const _api = undefined as unknown as Api;

    export interface Sources {
        BurgersWithLettuceOrdered: BurgersWithLettuceOrdered.Impl;
        NoLettuce: NoLettuce.Impl;
        OnlyBacon: OnlyBacon.Impl;
    }

    export namespace GeneratedSource {
        export const BurgersWithLettuceOrdered = {
            tree: {"toppings":{}},
            selectQueryRaw: `SELECT "Hamburger"."id" AS "id", "Hamburger"."name" AS "name", "HamburgerTopping_2"."right" AS "toppings.id", "Topping_1"."name" AS "toppings.name" FROM "Hamburger" LEFT JOIN "HamburgerTopping" AS "HamburgerTopping_2" ON "Hamburger"."id" = "HamburgerTopping_2"."left" LEFT JOIN "Topping" AS "Topping_1" ON "HamburgerTopping_2"."right" = "Topping_1"."id"`,
            getQueryRaw: `SELECT "Hamburger"."id" AS "id", "Hamburger"."name" AS "name", "HamburgerTopping_2"."right" AS "toppings.id", "Topping_1"."name" AS "toppings.name" FROM "Hamburger" LEFT JOIN "HamburgerTopping" AS "HamburgerTopping_2" ON "Hamburger"."id" = "HamburgerTopping_2"."left" LEFT JOIN "Topping" AS "Topping_1" ON "HamburgerTopping_2"."right" = "Topping_1"."id" WHERE "Hamburger"."id" = ?1`,
            listQueryRaw: `SELECT "Hamburger"."id" AS "id", "Hamburger"."name" AS "name", "HamburgerTopping_2"."right" AS "toppings.id", "Topping_1"."name" AS "toppings.name" FROM "Hamburger" LEFT JOIN "HamburgerTopping" AS "HamburgerTopping_2" ON "Hamburger"."id" = "HamburgerTopping_2"."left" LEFT JOIN "Topping" AS "Topping_1" ON "HamburgerTopping_2"."right" = "Topping_1"."id" WHERE "Hamburger"."id" > ?1 ORDER BY "Hamburger"."id" ASC LIMIT ?2`,

            selectQuery(env: { db: Env["db"] }): D1PreparedStatement {
                return env.db.prepare(this.selectQueryRaw);
            },
            getQuery(env: { db: Env["db"] }, id: number): D1PreparedStatement {
                return env.db.prepare(this.getQueryRaw).bind(id);
            },
            listQuery(env: { db: Env["db"] }, lastId: number, limit: number): D1PreparedStatement {
                return env.db.prepare(this.listQueryRaw).bind(lastId, limit);
            },
            async get(env: { db: Env["db"] }, id: number): Promise<HttpResult<Self | null>> {
                const stmt = this.getQuery(env, id);
                const res = await CloesceOrm.fromEnv(env).get<Self>(Meta, stmt, this.tree);
                if (res.errors.length > 0) {
                    return HttpResult.fail(400, CloesceError.displayErrors(res));
                }
                if (res.value === null) {
                    return HttpResult.fail(404);
                }
                return HttpResult.ok(200, res.value);
            },
            async save(env: { db: Env["db"] }, model: DeepPartial<Self>): Promise<HttpResult<Self | null>> {
                let res: CloesceResult<Self | null>;
                try {
                    res = await CloesceOrm.fromEnv(env).upsert<Self>(Meta, model, this.tree);
                } catch (e) {
                    throw new InternalError(`Upsert failed: ${JSON.stringify(e)}`);
                }
                if (res.errors.length > 0) {
                    return HttpResult.fail(400, CloesceError.displayErrors(res));
                }
                if (res.value === null) {
                    return HttpResult.fail(404);
                }
                return HttpResult.ok(200, res.value);
            },
        };
        export const Default = {
            tree: {"toppings":{}},
            selectQueryRaw: `SELECT "Hamburger"."id" AS "id", "Hamburger"."name" AS "name", "HamburgerTopping_2"."right" AS "toppings.id", "Topping_1"."name" AS "toppings.name" FROM "Hamburger" LEFT JOIN "HamburgerTopping" AS "HamburgerTopping_2" ON "Hamburger"."id" = "HamburgerTopping_2"."left" LEFT JOIN "Topping" AS "Topping_1" ON "HamburgerTopping_2"."right" = "Topping_1"."id"`,
            getQueryRaw: `SELECT "Hamburger"."id" AS "id", "Hamburger"."name" AS "name", "HamburgerTopping_2"."right" AS "toppings.id", "Topping_1"."name" AS "toppings.name" FROM "Hamburger" LEFT JOIN "HamburgerTopping" AS "HamburgerTopping_2" ON "Hamburger"."id" = "HamburgerTopping_2"."left" LEFT JOIN "Topping" AS "Topping_1" ON "HamburgerTopping_2"."right" = "Topping_1"."id" WHERE "Hamburger"."id" = ?1`,
            listQueryRaw: `SELECT "Hamburger"."id" AS "id", "Hamburger"."name" AS "name", "HamburgerTopping_2"."right" AS "toppings.id", "Topping_1"."name" AS "toppings.name" FROM "Hamburger" LEFT JOIN "HamburgerTopping" AS "HamburgerTopping_2" ON "Hamburger"."id" = "HamburgerTopping_2"."left" LEFT JOIN "Topping" AS "Topping_1" ON "HamburgerTopping_2"."right" = "Topping_1"."id" WHERE "Hamburger"."id" > ?1 ORDER BY "Hamburger"."id" ASC LIMIT ?2`,

            selectQuery(env: { db: Env["db"] }): D1PreparedStatement {
                return env.db.prepare(this.selectQueryRaw);
            },
            getQuery(env: { db: Env["db"] }, id: number): D1PreparedStatement {
                return env.db.prepare(this.getQueryRaw).bind(id);
            },
            listQuery(env: { db: Env["db"] }, lastSeen_id: number, limit: number): D1PreparedStatement {
                return env.db.prepare(this.listQueryRaw).bind(lastSeen_id, limit);
            },
            async get(env: { db: Env["db"] }, id: number): Promise<HttpResult<Self | null>> {
                const stmt = this.getQuery(env, id);
                const res = await CloesceOrm.fromEnv(env).get<Self>(Meta, stmt, this.tree);
                if (res.errors.length > 0) {
                    return HttpResult.fail(400, CloesceError.displayErrors(res));
                }
                if (res.value === null) {
                    return HttpResult.fail(404);
                }
                return HttpResult.ok(200, res.value);
            },
            async list(env: { db: Env["db"] }, lastSeen_id: number, limit: number): Promise<HttpResult<Self[]>> {
                const stmt = this.listQuery(env, lastSeen_id, limit);
                const res = await CloesceOrm.fromEnv(env).list<Self>(Meta, stmt, this.tree);
                if (res.errors.length > 0) {
                    return HttpResult.fail(400, CloesceError.displayErrors(res));
                }
                return HttpResult.ok(200, res.value!);
            },
            async save(env: { db: Env["db"] }, model: DeepPartial<Self>): Promise<HttpResult<Self | null>> {
                let res: CloesceResult<Self | null>;
                try {
                    res = await CloesceOrm.fromEnv(env).upsert<Self>(Meta, model, this.tree);
                } catch (e) {
                    throw new InternalError(`Upsert failed: ${JSON.stringify(e)}`);
                }
                if (res.errors.length > 0) {
                    return HttpResult.fail(400, CloesceError.displayErrors(res));
                }
                if (res.value === null) {
                    return HttpResult.fail(404);
                }
                return HttpResult.ok(200, res.value);
            },
        };
        export const NoLettuce = {
            tree: {"toppings":{}},
            selectQueryRaw: `SELECT "Hamburger"."id" AS "id", "Hamburger"."name" AS "name", "HamburgerTopping_2"."right" AS "toppings.id", "Topping_1"."name" AS "toppings.name" FROM "Hamburger" LEFT JOIN "HamburgerTopping" AS "HamburgerTopping_2" ON "Hamburger"."id" = "HamburgerTopping_2"."left" LEFT JOIN "Topping" AS "Topping_1" ON "HamburgerTopping_2"."right" = "Topping_1"."id"`,
            getQueryRaw: `SELECT "Hamburger"."id" AS "id", "Hamburger"."name" AS "name", "HamburgerTopping_2"."right" AS "toppings.id", "Topping_1"."name" AS "toppings.name" FROM "Hamburger" LEFT JOIN "HamburgerTopping" AS "HamburgerTopping_2" ON "Hamburger"."id" = "HamburgerTopping_2"."left" LEFT JOIN "Topping" AS "Topping_1" ON "HamburgerTopping_2"."right" = "Topping_1"."id" WHERE "Hamburger"."id" = ?1`,
            listQueryRaw: `SELECT "Hamburger"."id" AS "id", "Hamburger"."name" AS "name", "HamburgerTopping_2"."right" AS "toppings.id", "Topping_1"."name" AS "toppings.name" FROM "Hamburger" LEFT JOIN "HamburgerTopping" AS "HamburgerTopping_2" ON "Hamburger"."id" = "HamburgerTopping_2"."left" LEFT JOIN "Topping" AS "Topping_1" ON "HamburgerTopping_2"."right" = "Topping_1"."id" WHERE "Hamburger"."id" > ?1 ORDER BY "Hamburger"."id" ASC LIMIT ?2`,

            selectQuery(env: { db: Env["db"] }): D1PreparedStatement {
                return env.db.prepare(this.selectQueryRaw);
            },
            getQuery(env: { db: Env["db"] }, id: number): D1PreparedStatement {
                return env.db.prepare(this.getQueryRaw).bind(id);
            },
            listQuery(env: { db: Env["db"] }, lastSeen_id: number, limit: number): D1PreparedStatement {
                return env.db.prepare(this.listQueryRaw).bind(lastSeen_id, limit);
            },
            async list(env: { db: Env["db"] }, lastSeen_id: number, limit: number): Promise<HttpResult<Self[]>> {
                const stmt = this.listQuery(env, lastSeen_id, limit);
                const res = await CloesceOrm.fromEnv(env).list<Self>(Meta, stmt, this.tree);
                if (res.errors.length > 0) {
                    return HttpResult.fail(400, CloesceError.displayErrors(res));
                }
                return HttpResult.ok(200, res.value!);
            },
            async save(env: { db: Env["db"] }, model: DeepPartial<Self>): Promise<HttpResult<Self | null>> {
                let res: CloesceResult<Self | null>;
                try {
                    res = await CloesceOrm.fromEnv(env).upsert<Self>(Meta, model, this.tree);
                } catch (e) {
                    throw new InternalError(`Upsert failed: ${JSON.stringify(e)}`);
                }
                if (res.errors.length > 0) {
                    return HttpResult.fail(400, CloesceError.displayErrors(res));
                }
                if (res.value === null) {
                    return HttpResult.fail(404);
                }
                return HttpResult.ok(200, res.value);
            },
        };
        export const OnlyBacon = {
            tree: {"toppings":{}},
            selectQueryRaw: `SELECT "Hamburger"."id" AS "id", "Hamburger"."name" AS "name", "HamburgerTopping_2"."right" AS "toppings.id", "Topping_1"."name" AS "toppings.name" FROM "Hamburger" LEFT JOIN "HamburgerTopping" AS "HamburgerTopping_2" ON "Hamburger"."id" = "HamburgerTopping_2"."left" LEFT JOIN "Topping" AS "Topping_1" ON "HamburgerTopping_2"."right" = "Topping_1"."id"`,
            getQueryRaw: `SELECT "Hamburger"."id" AS "id", "Hamburger"."name" AS "name", "HamburgerTopping_2"."right" AS "toppings.id", "Topping_1"."name" AS "toppings.name" FROM "Hamburger" LEFT JOIN "HamburgerTopping" AS "HamburgerTopping_2" ON "Hamburger"."id" = "HamburgerTopping_2"."left" LEFT JOIN "Topping" AS "Topping_1" ON "HamburgerTopping_2"."right" = "Topping_1"."id" WHERE "Hamburger"."id" = ?1`,
            listQueryRaw: `SELECT "Hamburger"."id" AS "id", "Hamburger"."name" AS "name", "HamburgerTopping_2"."right" AS "toppings.id", "Topping_1"."name" AS "toppings.name" FROM "Hamburger" LEFT JOIN "HamburgerTopping" AS "HamburgerTopping_2" ON "Hamburger"."id" = "HamburgerTopping_2"."left" LEFT JOIN "Topping" AS "Topping_1" ON "HamburgerTopping_2"."right" = "Topping_1"."id" WHERE "Hamburger"."id" > ?1 ORDER BY "Hamburger"."id" ASC LIMIT ?2`,

            selectQuery(env: { db: Env["db"] }): D1PreparedStatement {
                return env.db.prepare(this.selectQueryRaw);
            },
            getQuery(env: { db: Env["db"] }, id: number): D1PreparedStatement {
                return env.db.prepare(this.getQueryRaw).bind(id);
            },
            listQuery(env: { db: Env["db"] }, lastSeen_id: number, limit: number): D1PreparedStatement {
                return env.db.prepare(this.listQueryRaw).bind(lastSeen_id, limit);
            },
            async list(env: { db: Env["db"] }, lastSeen_id: number, limit: number): Promise<HttpResult<Self[]>> {
                const stmt = this.listQuery(env, lastSeen_id, limit);
                const res = await CloesceOrm.fromEnv(env).list<Self>(Meta, stmt, this.tree);
                if (res.errors.length > 0) {
                    return HttpResult.fail(400, CloesceError.displayErrors(res));
                }
                return HttpResult.ok(200, res.value!);
            },
            async save(env: { db: Env["db"] }, model: DeepPartial<Self>): Promise<HttpResult<Self | null>> {
                let res: CloesceResult<Self | null>;
                try {
                    res = await CloesceOrm.fromEnv(env).upsert<Self>(Meta, model, this.tree);
                } catch (e) {
                    throw new InternalError(`Upsert failed: ${JSON.stringify(e)}`);
                }
                if (res.errors.length > 0) {
                    return HttpResult.fail(400, CloesceError.displayErrors(res));
                }
                if (res.value === null) {
                    return HttpResult.fail(404);
                }
                return HttpResult.ok(200, res.value);
            },
        };
    }
    export namespace BurgersWithLettuceOrdered {
        export interface Stubs {
            list(env: { db: Env["db"] }, lastId: number, limit: number): ApiResult<Self[]>;
        }
        export type Impl = typeof GeneratedSource.BurgersWithLettuceOrdered & Stubs;
        export function impl<I extends Stubs>(implObj: I & ThisType<typeof GeneratedSource.BurgersWithLettuceOrdered & I>): typeof GeneratedSource.BurgersWithLettuceOrdered & I {
            return _implDs(GeneratedSource.BurgersWithLettuceOrdered, implObj);
        }
    }
    export namespace NoLettuce {
        export interface Stubs {
            get(env: { db: Env["db"] }, id: number): ApiResult<Self>;
        }
        export type Impl = typeof GeneratedSource.NoLettuce & Stubs;
        export function impl<I extends Stubs>(implObj: I & ThisType<typeof GeneratedSource.NoLettuce & I>): typeof GeneratedSource.NoLettuce & I {
            return _implDs(GeneratedSource.NoLettuce, implObj);
        }
    }
    export namespace OnlyBacon {
        export interface Stubs {
            get(env: { db: Env["db"] }, id: number): ApiResult<Self>;
        }
        export type Impl = typeof GeneratedSource.OnlyBacon & Stubs;
        export function impl<I extends Stubs>(implObj: I & ThisType<typeof GeneratedSource.OnlyBacon & I>): typeof GeneratedSource.OnlyBacon & I {
            return _implDs(GeneratedSource.OnlyBacon, implObj);
        }
    }

    export function impl<Impl extends Api & Sources>(implObj: Impl & ThisType<{ tag: string; Orm: typeof Orm; Default: typeof GeneratedSource.Default } & Impl>): { tag: string; Orm: typeof Orm; Default: typeof GeneratedSource.Default } & Impl {
        return _impl("Hamburger", { Orm, Default: GeneratedSource.Default }, implObj) as any;
    }

    export namespace Orm {
        export async function save(env: { db: Env["db"] }, newModel: DeepPartial<Self>, include: IncludeTree<Self> = GeneratedSource.Default.tree): Promise<CloesceResult<Self | null>> {
            return await CloesceOrm.fromEnv(env).upsert<Self>(Meta, newModel, include);
        }

        export async function get(env: { db: Env["db"] }, args: { query?: D1PreparedStatement, include?: IncludeTree<Self> }): Promise<CloesceResult<Self | null>> {
            args.include ??= GeneratedSource.Default.tree
            return await CloesceOrm.fromEnv(env).get<Self>(Meta, args.query, args.include);
        }

        export async function list(env: { db: Env["db"] }, args: { query?: D1PreparedStatement, include?: IncludeTree<Self> }): Promise<CloesceResult<Hamburger.Self[]>> {
            args.include ??= GeneratedSource.Default.tree;
            return await CloesceOrm.fromEnv(env).list<Self>(Meta, args.query, args.include);
        }

        export function select(include: IncludeTree<Self> = GeneratedSource.Default.tree, from?: string): string {
            return CloesceOrm.select(Meta, from ?? null, include);
        }

        export function map(result: D1Result, include: IncludeTree<Self> = GeneratedSource.Default.tree): Self[] {
            return CloesceOrm.map<Self>(Meta, result, include);
        }

        export async function hydrate(env: { db: Env["db"] }, base: DeepPartial<Self>, include: IncludeTree<Self> = GeneratedSource.Default.tree): Promise<CloesceResult<Self>> {
            return await CloesceOrm.fromEnv(env).hydrate<Self>(Meta, base, include);
        }
    }
}
export namespace Topping {
    export const Tag = "Topping" as const;
    export const Meta = cidl.models.Topping as any;

    export interface Self {
        id: number;
        name: string;
        hamburger: Hamburger.Self[];
    }

    export interface Api {
    }
    export const _api = undefined as unknown as Api;

    export interface Sources {
    }

    export namespace GeneratedSource {
        export const Default = {
            tree: {"hamburger":{}},
            selectQueryRaw: `SELECT "Topping"."id" AS "id", "Topping"."name" AS "name", "HamburgerTopping_2"."left" AS "hamburger.id", "Hamburger_1"."name" AS "hamburger.name" FROM "Topping" LEFT JOIN "HamburgerTopping" AS "HamburgerTopping_2" ON "Topping"."id" = "HamburgerTopping_2"."right" LEFT JOIN "Hamburger" AS "Hamburger_1" ON "HamburgerTopping_2"."left" = "Hamburger_1"."id"`,
            getQueryRaw: `SELECT "Topping"."id" AS "id", "Topping"."name" AS "name", "HamburgerTopping_2"."left" AS "hamburger.id", "Hamburger_1"."name" AS "hamburger.name" FROM "Topping" LEFT JOIN "HamburgerTopping" AS "HamburgerTopping_2" ON "Topping"."id" = "HamburgerTopping_2"."right" LEFT JOIN "Hamburger" AS "Hamburger_1" ON "HamburgerTopping_2"."left" = "Hamburger_1"."id" WHERE "Topping"."id" = ?1`,
            listQueryRaw: `SELECT "Topping"."id" AS "id", "Topping"."name" AS "name", "HamburgerTopping_2"."left" AS "hamburger.id", "Hamburger_1"."name" AS "hamburger.name" FROM "Topping" LEFT JOIN "HamburgerTopping" AS "HamburgerTopping_2" ON "Topping"."id" = "HamburgerTopping_2"."right" LEFT JOIN "Hamburger" AS "Hamburger_1" ON "HamburgerTopping_2"."left" = "Hamburger_1"."id" WHERE "Topping"."id" > ?1 ORDER BY "Topping"."id" ASC LIMIT ?2`,

            selectQuery(env: { db: Env["db"] }): D1PreparedStatement {
                return env.db.prepare(this.selectQueryRaw);
            },
            getQuery(env: { db: Env["db"] }, id: number): D1PreparedStatement {
                return env.db.prepare(this.getQueryRaw).bind(id);
            },
            listQuery(env: { db: Env["db"] }, lastSeen_id: number, limit: number): D1PreparedStatement {
                return env.db.prepare(this.listQueryRaw).bind(lastSeen_id, limit);
            },
            async get(env: { db: Env["db"] }, id: number): Promise<HttpResult<Self | null>> {
                const stmt = this.getQuery(env, id);
                const res = await CloesceOrm.fromEnv(env).get<Self>(Meta, stmt, this.tree);
                if (res.errors.length > 0) {
                    return HttpResult.fail(400, CloesceError.displayErrors(res));
                }
                if (res.value === null) {
                    return HttpResult.fail(404);
                }
                return HttpResult.ok(200, res.value);
            },
            async list(env: { db: Env["db"] }, lastSeen_id: number, limit: number): Promise<HttpResult<Self[]>> {
                const stmt = this.listQuery(env, lastSeen_id, limit);
                const res = await CloesceOrm.fromEnv(env).list<Self>(Meta, stmt, this.tree);
                if (res.errors.length > 0) {
                    return HttpResult.fail(400, CloesceError.displayErrors(res));
                }
                return HttpResult.ok(200, res.value!);
            },
            async save(env: { db: Env["db"] }, model: DeepPartial<Self>): Promise<HttpResult<Self | null>> {
                let res: CloesceResult<Self | null>;
                try {
                    res = await CloesceOrm.fromEnv(env).upsert<Self>(Meta, model, this.tree);
                } catch (e) {
                    throw new InternalError(`Upsert failed: ${JSON.stringify(e)}`);
                }
                if (res.errors.length > 0) {
                    return HttpResult.fail(400, CloesceError.displayErrors(res));
                }
                if (res.value === null) {
                    return HttpResult.fail(404);
                }
                return HttpResult.ok(200, res.value);
            },
        };
    }

    export function impl<Impl extends Api & Sources>(implObj: Impl & ThisType<{ tag: string; Orm: typeof Orm; Default: typeof GeneratedSource.Default } & Impl>): { tag: string; Orm: typeof Orm; Default: typeof GeneratedSource.Default } & Impl {
        return _impl("Topping", { Orm, Default: GeneratedSource.Default }, implObj) as any;
    }

    export namespace Orm {
        export async function save(env: { db: Env["db"] }, newModel: DeepPartial<Self>, include: IncludeTree<Self> = GeneratedSource.Default.tree): Promise<CloesceResult<Self | null>> {
            return await CloesceOrm.fromEnv(env).upsert<Self>(Meta, newModel, include);
        }

        export async function get(env: { db: Env["db"] }, args: { query?: D1PreparedStatement, include?: IncludeTree<Self> }): Promise<CloesceResult<Self | null>> {
            args.include ??= GeneratedSource.Default.tree
            return await CloesceOrm.fromEnv(env).get<Self>(Meta, args.query, args.include);
        }

        export async function list(env: { db: Env["db"] }, args: { query?: D1PreparedStatement, include?: IncludeTree<Self> }): Promise<CloesceResult<Topping.Self[]>> {
            args.include ??= GeneratedSource.Default.tree;
            return await CloesceOrm.fromEnv(env).list<Self>(Meta, args.query, args.include);
        }

        export function select(include: IncludeTree<Self> = GeneratedSource.Default.tree, from?: string): string {
            return CloesceOrm.select(Meta, from ?? null, include);
        }

        export function map(result: D1Result, include: IncludeTree<Self> = GeneratedSource.Default.tree): Self[] {
            return CloesceOrm.map<Self>(Meta, result, include);
        }

        export async function hydrate(env: { db: Env["db"] }, base: DeepPartial<Self>, include: IncludeTree<Self> = GeneratedSource.Default.tree): Promise<CloesceResult<Self>> {
            return await CloesceOrm.fromEnv(env).hydrate<Self>(Meta, base, include);
        }
    }
}

function _impl(modelName: string, extras: Record<string, any>, implObj: any) {
    const base: any = { ...implObj, ...extras, tag: modelName };
    for (const key of Object.keys(base)) {
        const v = base[key];
        if (typeof v === "function") base[key] = v.bind(base);
    }
    return base;
}

function _implDs(generated: Record<string, any>, user: Record<string, any>) {
    const merged: any = { ...generated, ...user };
    for (const key of Object.keys(merged)) {
        const v = merged[key];
        if (typeof v === "function") merged[key] = v.bind(merged);
    }
    return merged;
}

import cidl from "./cidl.json" with { type: "json" };

export async function cloesce(): Promise<CloesceApp> {
    return await CloesceApp.init(cidl as any, "http://localhost:5403/api")
}

// Default entrypoint for a Cloesce app.
// Replace with a custom fetch handler to register API implementations, add middleware, etc.
export default {
    async fetch(request: Request, env: Env): Promise<Response> {
        const app = await cloesce();
        return await app.run(request, env);
    }
}