// GENERATED BY CLOESCE. DO NOT MODIFY.
// @ts-nocheck
export class Hamburger {
  id: number;
  name: string;
  toppings: Topping[];
  async noLettuceToppings(
    fetchImpl: typeof fetch = fetch
  ): Promise<HttpResult<Topping[]>> {
    const __$id = [
      encodeURIComponent(String(this.id)),
    ].join("/");
    const __$baseUrl = new URL(
      `http://localhost:5403/api/Hamburger/${__$id}/noLettuceToppings`
    );

    const __$res = await fetchImpl(__$baseUrl, {
      method: "GET",
    });

    return await HttpResult.fromResponse(
      __$res,
      MediaType.Json,
      Topping,
      true
    );
  }
  async onlyBaconToppings(
    fetchImpl: typeof fetch = fetch
  ): Promise<HttpResult<Topping[]>> {
    const __$id = [
      encodeURIComponent(String(this.id)),
    ].join("/");
    const __$baseUrl = new URL(
      `http://localhost:5403/api/Hamburger/${__$id}/onlyBaconToppings`
    );

    const __$res = await fetchImpl(__$baseUrl, {
      method: "GET",
    });

    return await HttpResult.fromResponse(
      __$res,
      MediaType.Json,
      Topping,
      true
    );
  }
  static async $save_BurgersWithLettuceOrdered(
    model: DeepPartial<Hamburger>,
    fetchImpl: typeof fetch = fetch
  ): Promise<HttpResult<Hamburger>> {
    const __$baseUrl = new URL(
      `http://localhost:5403/api/Hamburger/$save_BurgersWithLettuceOrdered`
    );
    const __$payload: any = {};
    __$payload["model"] = model;

    const __$res = await fetchImpl(__$baseUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: requestBody(MediaType.Json, __$payload),
    });

    return await HttpResult.fromResponse(
      __$res,
      MediaType.Json,
      Hamburger,
      false
    );
  }
  static async $save(
    model: DeepPartial<Hamburger>,
    fetchImpl: typeof fetch = fetch
  ): Promise<HttpResult<Hamburger>> {
    const __$baseUrl = new URL(
      `http://localhost:5403/api/Hamburger/$save`
    );
    const __$payload: any = {};
    __$payload["model"] = model;

    const __$res = await fetchImpl(__$baseUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: requestBody(MediaType.Json, __$payload),
    });

    return await HttpResult.fromResponse(
      __$res,
      MediaType.Json,
      Hamburger,
      false
    );
  }
  static async $list_BurgersWithLettuceOrdered(
    lastId: number,
    limit: number,
    fetchImpl: typeof fetch = fetch
  ): Promise<HttpResult<Hamburger[]>> {
    const __$baseUrl = new URL(
      `http://localhost:5403/api/Hamburger/$list_BurgersWithLettuceOrdered`
    );
    __$baseUrl.searchParams.append("lastId", String(lastId));
    __$baseUrl.searchParams.append("limit", String(limit));

    const __$res = await fetchImpl(__$baseUrl, {
      method: "GET",
    });

    return await HttpResult.fromResponse(
      __$res,
      MediaType.Json,
      Hamburger,
      true
    );
  }
  static async $list(
    lastSeen_id: number,
    limit: number,
    fetchImpl: typeof fetch = fetch
  ): Promise<HttpResult<Hamburger[]>> {
    const __$baseUrl = new URL(
      `http://localhost:5403/api/Hamburger/$list`
    );
    __$baseUrl.searchParams.append("lastSeen_id", String(lastSeen_id));
    __$baseUrl.searchParams.append("limit", String(limit));

    const __$res = await fetchImpl(__$baseUrl, {
      method: "GET",
    });

    return await HttpResult.fromResponse(
      __$res,
      MediaType.Json,
      Hamburger,
      true
    );
  }

  static fromJson(data: any): Hamburger {
    const __$res = Object.assign(new Hamburger(), data);
    for (let i = 0; i < __$res.toppings?.length; i++) {
      __$res.toppings[i] = Topping.fromJson(__$res.toppings[i]);
    }
    return __$res;
  }
}
export class Topping {
  id: number;
  name: string;
  hamburger: Hamburger[];
  static async $save(
    model: DeepPartial<Topping>,
    fetchImpl: typeof fetch = fetch
  ): Promise<HttpResult<Topping>> {
    const __$baseUrl = new URL(
      `http://localhost:5403/api/Topping/$save`
    );
    const __$payload: any = {};
    __$payload["model"] = model;

    const __$res = await fetchImpl(__$baseUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: requestBody(MediaType.Json, __$payload),
    });

    return await HttpResult.fromResponse(
      __$res,
      MediaType.Json,
      Topping,
      false
    );
  }

  static fromJson(data: any): Topping {
    const __$res = Object.assign(new Topping(), data);
    for (let i = 0; i < __$res.hamburger?.length; i++) {
      __$res.hamburger[i] = Hamburger.fromJson(__$res.hamburger[i]);
    }
    return __$res;
  }
}
function dsKey(args: object): string {
  return Object.keys(args)[0];
}

type DeepPartialInner<T> = T extends (infer U)[]
  ? DeepPartialInner<U>[]
  : T extends object
  ? { [K in keyof T]?: DeepPartialInner<T[K]> }
  : T | (null extends T ? null : never);
export type DeepPartial<T> = DeepPartialInner<T> & { __$brand?: "Partial" };

export class KValue<V> {
  key!: string;
  raw: unknown | null;
  metadata: unknown | null;
  get value(): V | null {
    return this.raw as V | null;
  }
}

export interface Paginated<T> {
  results: T[];
  cursor: string | null;
  complete: boolean;
}

export enum MediaType {
  Json = "Json",
  Octet = "Octet",
}

declare const Buffer: any;
export function b64ToU8(b64: string): Uint8Array {
  if (typeof Buffer !== "undefined") {
    const buffer = Buffer.from(b64, "base64");
    return new Uint8Array(buffer);
  }
  const s = atob(b64);
  const u8 = new Uint8Array(s.length);
  for (let i = 0; i < s.length; i++) {
    u8[i] = s.charCodeAt(i);
  }
  return u8;
}

export function u8ToB64(u8: Uint8Array): string {
  if (typeof Buffer !== "undefined") {
    return Buffer.from(u8).toString("base64");
  }
  let s = "";
  for (let i = 0; i < u8.length; i++) {
    s += String.fromCharCode(u8[i]);
  }
  return btoa(s);
}

export class R2Object {
  key!: string;
  version!: string;
  size!: number;
  etag!: string;
  httpEtag!: string;
  uploaded!: Date;
  customMetadata?: Record<string, string>;
}

function requestBody(
  mediaType: MediaType,
  data: any | string | undefined,
): BodyInit | undefined {
  switch (mediaType) {
    case MediaType.Json: {
      return JSON.stringify(data ?? {}, (_, v) => {
        if (v instanceof Uint8Array) {
          return u8ToB64(v);
        }
        return v;
      });
    }
    case MediaType.Octet: {
      return Object.values(data)[0] as BodyInit;
    }
  }
}

export class HttpResult<T = unknown> {
  public constructor(
    public ok: boolean,
    public status: number,
    public headers: Headers,
    public data?: T,
    public message?: string,
    public mediaType?: MediaType,
  ) { }

  static async fromResponse(
    response: Response,
    mediaType: MediaType,
    ctor?: any,
    array: boolean = false,
  ): Promise<HttpResult<any>> {
    if (response.status >= 400) {
      return new HttpResult(
        false,
        response.status,
        response.headers,
        undefined,
        await response.text(),
      );
    }

    function instantiate(json: any, ctor?: any) {
      switch (ctor) {
        case Date: {
          return new Date(json);
        }
        case Uint8Array: {
          return b64ToU8(json);
        }
        case undefined: {
          return json;
        }
        default: {
          return ctor.fromJson(json);
        }
      }
    }

    async function data() {
      switch (mediaType) {
        case MediaType.Json: {
          const data = await response.json();

          if (array && Array.isArray(data)) {
            for (let i = 0; i < data.length; i++) {
              data[i] = instantiate(data[i], ctor);
            }
            return data;
          }
          return instantiate(data, ctor);
        }
        case MediaType.Octet: {
          return response;
        }
      }
    }
    return new HttpResult(
      true,
      response.status,
      response.headers,
      await data(),
    );
  }
}