import { D1Database } from "@cloudflare/workers-types/experimental/index.js";

import { OrmWasmExports, mapSql, loadOrmWasm } from "./wasm.js";
import { proxyCrud } from "./crud.js";
import { HttpResult, IncludeTree, Orm } from "../ui/backend.js";
import { Either, KeysOfType } from "../ui/common.js";
import {
  CloesceAst,
  Model,
  ApiMethod,
  NO_DATA_SOURCE,
  Service,
  MediaType,
} from "../ast.js";
import { RuntimeValidator } from "./validator.js";

/**
 * Dependency injection container, mapping an object type name to an instance of that object.
 *
 * Comes with the WranglerEnv and Request by default.
 */
export type DependencyContainer = Map<string, any>;

/**
 * Map of Plain Old Objects, Models and Services to their constructor.
 *
 * Generated by the compiler and guaranteed to contain all CIDL definitions.
 */
export type ConstructorRegistry = Record<string, new () => any>;

/**
 * Singleton instance containing the cidl, constructor registry, and wasm binary.
 * These values are guaranteed to never change throughout a workers lifetime.
 */
export class RuntimeContainer {
  private static instance: RuntimeContainer | undefined;
  private constructor(
    public readonly ast: CloesceAst,
    public readonly constructorRegistry: ConstructorRegistry,
    public readonly wasm: OrmWasmExports,
  ) {}

  static async init(
    ast: CloesceAst,
    constructorRegistry: ConstructorRegistry,
    wasm?: WebAssembly.Instance,
  ) {
    if (this.instance) return;
    const wasmAbi = await loadOrmWasm(ast, wasm);
    this.instance = new RuntimeContainer(ast, constructorRegistry, wasmAbi);
  }

  static get(): RuntimeContainer {
    return this.instance!;
  }
}

/**
 * Given a request, this represents a map of each body / url  param name to
 * its actual value. Unknown, as the a request can be anything.
 */
export type RequestParamMap = Record<string, unknown>;

export type MiddlewareFn = (
  request: Request,
  env: any,
  di: DependencyContainer,
) => Promise<HttpResult | void>;

export type ResultMiddlewareFn = (
  request: Request,
  env: any,
  di: DependencyContainer,
  result: HttpResult,
) => Promise<HttpResult | void>;

type RouterResult<T = unknown> = [HttpResult<T>, MediaType];

/**
 * Expected states in which the router may exit.
 */
export enum RouterError {
  UnknownPrefix,
  UnknownRoute,
  UnmatchedHttpVerb,
  InstantiatedMethodMissingId,
  RequestMissingBody,
  RequestBodyMissingParameters,
  RequestBodyInvalidParameter,
  InstantiatedMethodMissingDataSource,
  MissingDependency,
  InvalidDatabaseQuery,
  ModelNotFound,
  UncaughtException,
}

export class CloesceApp {
  public routePrefix: string = "api";

  private globalMiddleware: MiddlewareFn[] = [];

  /**
   * Registers global middleware which runs before any route matching.
   *
   * TODO: Middleware may violate the API contract and return unexpected types
   *
   * @param m - The middleware function to register.
   */
  public onRequest(m: MiddlewareFn) {
    this.globalMiddleware.push(m);
  }

  private resultMiddleware: ResultMiddlewareFn[] = [];

  /**
   * Registers middleware which runs after the response is generated, but before
   * it is returned to the client.
   *
   * Optionally, return a new HttpResult to short-circuit the response.
   *
   * Errors thrown in response middleware are caught and returned as a 500 response.
   *
   * Errors thrown in earlier middleware or route processing are not caught here.
   *
   * TODO: Middleware may violate the API contract and return unexpected types
   *
   * @param m - The middleware function to register.
   */
  public onResult(m: ResultMiddlewareFn) {
    this.resultMiddleware.push(m);
  }

  private namespaceMiddleware: Map<string, MiddlewareFn[]> = new Map();

  /**
   * Registers middleware for a specific namespace (being, a model or service)
   *
   * Runs before request validation and method middleware.
   *
   * TODO: Middleware may violate the API contract and return unexpected types
   *
   * @typeParam T - The namespace type
   * @param ctor - The namespace's constructor (used to derive its name).
   * @param m - The middleware function to register.
   */
  public onNamespace<T>(ctor: new () => T, m: MiddlewareFn) {
    if (this.namespaceMiddleware.has(ctor.name)) {
      this.namespaceMiddleware.get(ctor.name)!.push(m);
    } else {
      this.namespaceMiddleware.set(ctor.name, [m]);
    }
  }

  private methodMiddleware: Map<string, Map<string, MiddlewareFn[]>> =
    new Map();

  /**
   * Registers middleware for a specific method on a namespace
   *
   * Runs after namespace middleware and request validation.
   *
   * TODO: Middleware may violate the API contract and return unexpected types
   *
   * @typeParam T - The namespace type
   * @param ctor - The namespace constructor
   * @param method - The method name on the namespace.
   * @param m - The middleware function to register.
   */
  public onMethod<T>(
    ctor: new () => T,
    method: KeysOfType<T, (...args: any) => any>,
    m: MiddlewareFn,
  ) {
    if (!this.methodMiddleware.has(ctor.name)) {
      this.methodMiddleware.set(ctor.name, new Map());
    }

    const methods = this.methodMiddleware.get(ctor.name)!;
    if (!methods.has(method)) {
      methods.set(method, []);
    }

    methods.get(method)!.push(m);
  }

  private async router(
    request: Request,
    env: any,
    ast: CloesceAst,
    ctorReg: ConstructorRegistry,
    di: DependencyContainer,
  ): Promise<RouterResult> {
    // Global middleware
    for (const m of this.globalMiddleware) {
      const res = await m(request, env, di);
      if (res) {
        return [res, MediaType.Text];
      }
    }

    // Route match
    const routeRes = matchRoute(request, ast, this.routePrefix);
    if (routeRes.isLeft()) {
      return [routeRes.value, MediaType.Text];
    }
    const route = routeRes.unwrap();

    // Model middleware
    for (const m of this.namespaceMiddleware.get(route.namespace) ?? []) {
      const res = await m(request, env, di);
      if (res) {
        return [res, MediaType.Text];
      }
    }

    // Request validation
    const validation = await validateRequest(request, ast, ctorReg, route);
    if (validation.isLeft()) {
      return [validation.value, MediaType.Text];
    }
    const { params, dataSource } = validation.unwrap();

    // Method middleware
    for (const m of this.methodMiddleware
      .get(route.namespace)
      ?.get(route.method.name) ?? []) {
      const res = await m(request, env, di);
      if (res) {
        return [res, MediaType.Text];
      }
    }

    // Hydration
    const hydrated = await (async () => {
      if (route.kind == "model") {
        // TODO: Support multiple D1 bindings
        // It's been verified by the compiler that wrangler_env exists if a D1 model is present
        const d1: D1Database = env[ast.wrangler_env!.db_binding];

        // Proxy CRUD
        if (route.method.is_static) {
          return Either.right(
            proxyCrud(ctorReg[route.namespace], ctorReg[route.namespace], d1),
          );
        }

        return await hydrateModelD1(
          ctorReg,
          d1,
          route.model!,
          route.id!,
          dataSource!,
        );
      }

      // Services
      if (route.method.is_static) {
        return Either.right(ctorReg[route.namespace]);
      }
      return Either.right(di.get(route.namespace));
    })();

    if (hydrated.isLeft()) {
      return [hydrated.value, MediaType.Text];
    }

    // Method dispatch
    return await methodDispatch(hydrated.unwrap(), di, route, params);
  }

  /**
   * Runs the Cloesce app. Intended to be called from the generated workers code.
   */
  public async run(
    request: Request,
    env: any,
    ast: CloesceAst,
    ctorReg: ConstructorRegistry,
  ): Promise<Response> {
    await RuntimeContainer.init(ast, ctorReg);

    const di: DependencyContainer = new Map();
    if (ast.wrangler_env) {
      di.set(ast.wrangler_env.name, env);
    }
    di.set("Request", request);

    // Note: Services are in topological order
    for (const name in ast.services) {
      const service: any = ast.services[name];

      for (const attr of service.attributes) {
        const injected = di.get(attr.injected);
        if (!injected) {
          return exit(
            500,
            RouterError.MissingDependency,
            `An injected parameter was missing from the instance registry: ${JSON.stringify(attr.injected)}`,
          )
            .unwrapLeft()
            .toResponse(MediaType.Text);
        }

        service[attr.var_name] = injected;
      }

      // Inject services
      di.set(name, Object.assign(new ctorReg[name](), service));
    }

    try {
      const [response, mediaType] = await this.router(
        request,
        env,
        ast,
        ctorReg,
        di,
      );

      // Response middleware
      for (const m of this.resultMiddleware) {
        const res = await m(request, env, di, response);
        if (res) {
          return res.toResponse(MediaType.Text);
        }
      }

      return response.toResponse(mediaType);
    } catch (e: any) {
      console.error(JSON.stringify(e));
      return HttpResult.fail(500, e.toString()).toResponse(MediaType.Text);
    }
  }
}

export type MatchedRoute = {
  kind: "model" | "service";
  namespace: string;
  method: ApiMethod;
  id: string | null;
  model?: Model;
  service?: Service;
};

/**
 * Matches a request to an ApiInvocation
 * @param apiRoute The route from the domain to the actual API, ie https://foo.com/route/to/api => route/to/api/
 * @returns 404 or a matched route.
 */
function matchRoute(
  request: Request,
  ast: CloesceAst,
  routePrefix: string,
): Either<HttpResult, MatchedRoute> {
  const url = new URL(request.url);
  const parts = url.pathname.split("/").filter(Boolean);
  const prefix = routePrefix.split("/").filter(Boolean);

  // Error state: We expect an exact request format, and expect that the model
  // and are apart of the CIDL
  const notFound = (c: RouterError) => exit(404, c, "Unknown route");

  for (const p of prefix) {
    if (parts.shift() !== p) return notFound(RouterError.UnknownPrefix);
  }

  if (parts.length < 2) {
    return notFound(RouterError.UnknownPrefix);
  }

  // Extract pattern
  const namespace = parts[0];
  const methodName = parts[parts.length - 1];
  const id = parts.length === 3 ? parts[1] : null;

  const model = ast.models[namespace];
  if (model) {
    const method = model.methods[methodName];
    if (!method) return notFound(RouterError.UnknownRoute);

    if (request.method !== method.http_verb) {
      return notFound(RouterError.UnmatchedHttpVerb);
    }

    return Either.right({
      kind: "model",
      namespace,
      method,
      model,
      id,
    });
  }

  const service = ast.services[namespace];
  if (service) {
    const method = service.methods[methodName];

    // Services do not have IDs.
    if (!method || id) return notFound(RouterError.UnknownRoute);

    if (request.method !== method.http_verb) {
      return notFound(RouterError.UnmatchedHttpVerb);
    }

    return Either.right({
      kind: "service",
      namespace,
      method,
      service,
      id: null,
    });
  }

  return notFound(RouterError.UnknownRoute);
}

/**
 * Validates the request's body/search params against a ModelMethod
 * @returns 400 or a `RequestParamMap` consisting of each parameters name mapped to its value, and
 * a data source
 */
async function validateRequest(
  request: Request,
  ast: CloesceAst,
  ctorReg: ConstructorRegistry,
  route: MatchedRoute,
): Promise<
  Either<HttpResult, { params: RequestParamMap; dataSource: string | null }>
> {
  // Error state: any missing parameter, body, or malformed input will exit with 400.
  const invalidRequest = (c: RouterError) =>
    exit(400, c, "Invalid Request Body");

  // Models must have an ID on instantiated methods.
  if (route.kind === "model" && !route.method.is_static && route.id == null) {
    return invalidRequest(RouterError.InstantiatedMethodMissingId);
  }

  // Filter out injected parameters
  const requiredParams = route.method.parameters.filter(
    (p) => !(typeof p.cidl_type === "object" && "Inject" in p.cidl_type),
  );

  const url = new URL(request.url);
  let params: RequestParamMap = Object.fromEntries(url.searchParams.entries());

  // Extract all method parameters from the body
  if (route.method.http_verb !== "GET") {
    try {
      switch (route.method.parameters_media) {
        case MediaType.Json: {
          const body = await request.json();
          params = { ...params, ...body };
          break;
        }
        case MediaType.Octet: {
          // Octet streams are verified by the Cloesce compiler to have
          // one Stream type
          const streamParam = requiredParams.find(
            (p) => typeof p.cidl_type === "string" && p.cidl_type === "Stream",
          )!;

          params[streamParam.name] = request.body;
          break;
        }
        default: {
          throw new Error("not implemented");
        }
      }
    } catch {
      return invalidRequest(RouterError.RequestMissingBody);
    }
  }

  if (!requiredParams.every((p) => p.name in params)) {
    return invalidRequest(RouterError.RequestBodyMissingParameters);
  }

  // Validate all parameters type
  // Octet streams can be passed as is
  if (route.method.parameters_media !== MediaType.Octet) {
    for (const p of requiredParams) {
      const res = RuntimeValidator.validate(
        params[p.name],
        p.cidl_type,
        ast,
        ctorReg,
      );
      if (res.isLeft()) {
        return invalidRequest(RouterError.RequestBodyInvalidParameter);
      }

      params[p.name] = res.unwrap();
    }
  }

  // A data source is required for instantiated model methods
  const dataSource: string | undefined = requiredParams
    .filter(
      (p) =>
        typeof p.cidl_type === "object" &&
        "DataSource" in p.cidl_type &&
        p.cidl_type.DataSource === route.namespace,
    )
    .map((p) => params[p.name] as string)[0];
  if (route.kind === "model" && !route.method.is_static && !dataSource) {
    return invalidRequest(RouterError.InstantiatedMethodMissingDataSource);
  }

  return Either.right({ params, dataSource: dataSource ?? null });
}

/**
 * Queries D1 for a particular model's ID, then transforms the SQL column output into
 * an instance of a model using the provided include tree and metadata as a guide.
 * @returns 404 if no record was found for the provided ID
 * @returns 500 if the D1 database is not synced with Cloesce and yields an error
 * @returns The instantiated model on success
 */
async function hydrateModelD1(
  constructorRegistry: ConstructorRegistry,
  d1: D1Database,
  model: Model,
  id: string,
  dataSource: string,
): Promise<Either<HttpResult, object>> {
  // Error state: If the D1 database has been tweaked outside of Cloesce
  // resulting in a malformed query, exit with a 500.
  const malformedQuery = (e: any) =>
    exit(
      500,
      RouterError.InvalidDatabaseQuery,
      `Error in hydration query, is the database out of sync with the backend?: ${e instanceof Error ? e.message : String(e)}`,
    );

  // Query DB
  let records;
  try {
    let includeTree: IncludeTree<any> | null =
      dataSource === NO_DATA_SOURCE
        ? null
        : (constructorRegistry[model.name] as any)[dataSource];

    records = await d1
      .prepare(Orm.getQuery(constructorRegistry[model.name], includeTree))
      .bind(id)
      .run();

    // Error state: If no record is found for the id, return a 404
    if (!records?.results) {
      return exit(404, RouterError.ModelNotFound, "Record not found");
    }

    if (records.error) {
      return malformedQuery(records.error);
    }
  } catch (e) {
    return malformedQuery(e);
  }

  // Hydrate
  const models: object[] = mapSql(
    constructorRegistry[model.name],
    records.results,
    model.data_sources[dataSource]?.tree ?? {},
  ).value as object[];

  return Either.right(models[0]);
}

/**
 * Calls a method on a model given a list of parameters.
 * @returns 500 on an uncaught client error, 200 with a result body on success
 */
async function methodDispatch(
  obj: any,
  di: DependencyContainer,
  route: MatchedRoute,
  params: Record<string, unknown>,
): Promise<RouterResult> {
  const paramArray: any[] = [];
  for (const param of route.method.parameters) {
    if (param.name in params) {
      paramArray.push(params[param.name]);
      continue;
    }

    // Injected type
    const injected = di.get((param.cidl_type as any)["Inject"]);
    if (!injected) {
      // Error state: Injected parameters cannot be found at compile time, only at runtime.
      // If a injected reference does not exist, throw a 500.
      return [
        exit(
          500,
          RouterError.MissingDependency,
          `An injected parameter was missing from the instance registry: ${JSON.stringify(param.cidl_type)}`,
        ).unwrapLeft(),
        MediaType.Text,
      ];
    }

    paramArray.push(injected);
  }

  const wrapResult = (res: any): HttpResult => {
    const rt = route.method.return_type;

    if (rt === "Void") {
      return HttpResult.ok(200);
    }

    if (typeof rt === "object" && rt !== null && "HttpResult" in rt) {
      // The result should already have an HttpResult, return as is
      return res as HttpResult<unknown>;
    }

    // Wrap in an HttpResult
    return HttpResult.ok(200, res);
  };

  try {
    const res = await obj[route.method.name](...paramArray);
    return [wrapResult(res), route.method.return_media];
  } catch (e) {
    // Error state: Client code threw an uncaught exception.
    return [
      exit(
        500,
        RouterError.UncaughtException,
        `Uncaught exception in method dispatch: ${e instanceof Error ? e.message : String(e)}`,
      ).unwrapLeft(),
      MediaType.Text,
    ];
  }
}

function exit(
  status: number,
  state: RouterError,
  message: string,
  debugMessage: string = "",
): Either<HttpResult<void>, never> {
  return Either.left(
    HttpResult.fail(status, `${message} (ErrorCode: ${state}${debugMessage})`),
  );
}

/**
 * For testing purposes
 */
export const _cloesceInternal = {
  matchRoute,
  validateRequest,
  methodDispatch,
  RuntimeContainer,
};
